/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import type { AvitoWebhookPayload } from './avitoWebhookPayload';

/**
 * Payload, который присылает Avito в вебхуке
 */
export interface AvitoWebhook {
  id: string;
  version: string;
  timestamp: number;
  payload: AvitoWebhookPayload;
}
