/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import type { BulkUpdateScheduleItemsDtoItemsItemTimeEndTime } from './bulkUpdateScheduleItemsDtoItemsItemTimeEndTime';
import type { BulkUpdateScheduleItemsDtoItemsItemTimeStartTime } from './bulkUpdateScheduleItemsDtoItemsItemTimeStartTime';

export type BulkUpdateScheduleItemsDtoItemsItemTime = {
  /** Объект с данными о времени */
  startTime: BulkUpdateScheduleItemsDtoItemsItemTimeStartTime;
  /** Объект с данными о времени */
  endTime: BulkUpdateScheduleItemsDtoItemsItemTimeEndTime;
};
