/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import type { BulkCreateScheduleItemsDtoItemsItemTimeEndTime } from './bulkCreateScheduleItemsDtoItemsItemTimeEndTime';
import type { BulkCreateScheduleItemsDtoItemsItemTimeStartTime } from './bulkCreateScheduleItemsDtoItemsItemTimeStartTime';

export type BulkCreateScheduleItemsDtoItemsItemTime = {
  /** Объект с данными о времени */
  startTime: BulkCreateScheduleItemsDtoItemsItemTimeStartTime;
  /** Объект с данными о времени */
  endTime: BulkCreateScheduleItemsDtoItemsItemTimeEndTime;
};
