/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import type { CreateScheduleDtoItemsItem } from './createScheduleDtoItemsItem';

export interface CreateScheduleDto {
  /** @minLength 1 */
  name: string;
  items?: CreateScheduleDtoItemsItem[];
}
