/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import type { CreateScheduleDtoItemsItemTimeEndTime } from './createScheduleDtoItemsItemTimeEndTime';
import type { CreateScheduleDtoItemsItemTimeStartTime } from './createScheduleDtoItemsItemTimeStartTime';

/**
 * Объект с временем начала и окончания в формате [HH, MM]
 */
export type CreateScheduleDtoItemsItemTime = {
  startTime: CreateScheduleDtoItemsItemTimeStartTime;
  endTime: CreateScheduleDtoItemsItemTimeEndTime;
};
