/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */

export * from './avitoCallbackControllerGetBotSettingsParams';
export * from './avitoWebhook';
export * from './avitoWebhookPayload';
export * from './avitoWebhookPayloadType';
export * from './avitoWebhookPayloadValue';
export * from './avitoWebhookPayloadValueChatType';
export * from './bindScheduleDto';
export * from './botDto';
export * from './botSettings';
export * from './botSettingsChatTypesItem';
export * from './bulkCreateScheduleItemsDto';
export * from './bulkCreateScheduleItemsDtoItemsItem';
export * from './bulkCreateScheduleItemsDtoItemsItemTime';
export * from './bulkCreateScheduleItemsDtoItemsItemTimeEndTime';
export * from './bulkCreateScheduleItemsDtoItemsItemTimeStartTime';
export * from './bulkCreateScheduleItemsDtoItemsItemWeekDay';
export * from './bulkUpdateScheduleItemsDto';
export * from './bulkUpdateScheduleItemsDtoItemsItem';
export * from './bulkUpdateScheduleItemsDtoItemsItemTime';
export * from './bulkUpdateScheduleItemsDtoItemsItemTimeEndTime';
export * from './bulkUpdateScheduleItemsDtoItemsItemTimeStartTime';
export * from './bulkUpdateScheduleItemsDtoItemsItemWeekDay';
export * from './createScheduleDto';
export * from './createScheduleItemDto';
export * from './createScheduleItemDtoTime';
export * from './createScheduleItemDtoTimeEndTime';
export * from './createScheduleItemDtoTimeStartTime';
export * from './createScheduleItemDtoWeekDay';
export * from './scheduleItemDto';
export * from './scheduleItemDtoTime';
export * from './scheduleItemDtoTimeEndTime';
export * from './scheduleItemDtoTimeStartTime';
export * from './scheduleItemDtoWeekDay';
export * from './scheduleItemsDto';
export * from './scheduleItemsDtoItem';
export * from './scheduleItemsDtoItemTime';
export * from './scheduleItemsDtoItemTimeEndTime';
export * from './scheduleItemsDtoItemTimeStartTime';
export * from './scheduleItemsDtoItemWeekDay';
export * from './schedulesWithItemsDto';
export * from './schedulesWithItemsDtoItem';
export * from './schedulesWithItemsDtoItemItemsItem';
export * from './schedulesWithItemsDtoItemItemsItemTime';
export * from './schedulesWithItemsDtoItemItemsItemTimeEndTime';
export * from './schedulesWithItemsDtoItemItemsItemTimeStartTime';
export * from './schedulesWithItemsDtoItemItemsItemWeekDay';
export * from './scheduleWithItemsDto';
export * from './scheduleWithItemsDtoItemsItem';
export * from './scheduleWithItemsDtoItemsItemTime';
export * from './scheduleWithItemsDtoItemsItemTimeEndTime';
export * from './scheduleWithItemsDtoItemsItemTimeStartTime';
export * from './scheduleWithItemsDtoItemsItemWeekDay';
export * from './unbindScheduleDto';
export * from './updateBotSettings';
export * from './updateBotSettingsChatTypesItem';
export * from './updateScheduleDto';
export * from './updateScheduleItemDto';
export * from './updateScheduleItemDtoTime';
export * from './updateScheduleItemDtoTimeEndTime';
export * from './updateScheduleItemDtoTimeStartTime';
export * from './updateScheduleItemDtoWeekDay';
