/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import type { ScheduleWithItemsDtoItemsItem } from './scheduleWithItemsDtoItemsItem';

export interface ScheduleWithItemsDto {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @minLength 1 */
  name: string;
  description?: string | null;
  items: ScheduleWithItemsDtoItemsItem[];
}
