/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import type { ScheduleWithItemsDtoItemsItemTime } from './scheduleWithItemsDtoItemsItemTime';
import type { ScheduleWithItemsDtoItemsItemWeekDay } from './scheduleWithItemsDtoItemsItemWeekDay';

export type ScheduleWithItemsDtoItemsItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  weekDay: ScheduleWithItemsDtoItemsItemWeekDay;
  /**
     * @deprecated
     * @pattern ^([01]\d|2[0-3]):([0-5]\d)$
     */
  startTime?: string;
  /**
     * @deprecated
     * @pattern ^([01]\d|2[0-3]):([0-5]\d)$
     */
  endTime?: string;
  /** Объект с временем начала и окончания в формате [HH, MM] */
  time: ScheduleWithItemsDtoItemsItemTime;
  /** @minLength 1 */
  text: string;
};
