/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */

export type ScheduleWithItemsDtoOutputItemsItemWeekDay = typeof ScheduleWithItemsDtoOutputItemsItemWeekDay[keyof typeof ScheduleWithItemsDtoOutputItemsItemWeekDay];


export const ScheduleWithItemsDtoOutputItemsItemWeekDay = {
  mon: 'mon',
  tue: 'tue',
  wed: 'wed',
  thu: 'thu',
  fri: 'fri',
  sat: 'sat',
  sun: 'sun',
} as const;
