/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import type { ScheduleItemsDtoItemTimeEndTime } from './scheduleItemsDtoItemTimeEndTime';
import type { ScheduleItemsDtoItemTimeStartTime } from './scheduleItemsDtoItemTimeStartTime';

export type ScheduleItemsDtoItemTime = {
  /** Объект с данными о времени */
  startTime: ScheduleItemsDtoItemTimeStartTime;
  /** Объект с данными о времени */
  endTime: ScheduleItemsDtoItemTimeEndTime;
};
