/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import type { ScheduleWithItemsDtoItemsItemTimeEndTime } from './scheduleWithItemsDtoItemsItemTimeEndTime';
import type { ScheduleWithItemsDtoItemsItemTimeStartTime } from './scheduleWithItemsDtoItemsItemTimeStartTime';

export type ScheduleWithItemsDtoItemsItemTime = {
  /** Объект с данными о времени */
  startTime: ScheduleWithItemsDtoItemsItemTimeStartTime;
  /** Объект с данными о времени */
  endTime: ScheduleWithItemsDtoItemsItemTimeEndTime;
};
