/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import type { ScheduleItemDtoTimeEndTime } from './scheduleItemDtoTimeEndTime';
import type { ScheduleItemDtoTimeStartTime } from './scheduleItemDtoTimeStartTime';

/**
 * Объект с временем начала и окончания в формате [HH, MM]
 */
export type ScheduleItemDtoTime = {
  startTime: ScheduleItemDtoTimeStartTime;
  endTime: ScheduleItemDtoTimeEndTime;
};
