/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import type { SchedulesWithItemsDtoItem } from './schedulesWithItemsDtoItem';

export type SchedulesWithItemsDto = SchedulesWithItemsDtoItem[];
