/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import type { ScheduleWithItemsDtoItemsItemTimeEndTime } from './scheduleWithItemsDtoItemsItemTimeEndTime';
import type { ScheduleWithItemsDtoItemsItemTimeStartTime } from './scheduleWithItemsDtoItemsItemTimeStartTime';

/**
 * Объект с временем начала и окончания в формате [HH, MM]
 */
export type ScheduleWithItemsDtoItemsItemTime = {
  startTime: ScheduleWithItemsDtoItemsItemTimeStartTime;
  endTime: ScheduleWithItemsDtoItemsItemTimeEndTime;
};
