/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import type { SchedulesWithItemsDtoItemItemsItemTimeEndTime } from './schedulesWithItemsDtoItemItemsItemTimeEndTime';
import type { SchedulesWithItemsDtoItemItemsItemTimeStartTime } from './schedulesWithItemsDtoItemItemsItemTimeStartTime';

export type SchedulesWithItemsDtoItemItemsItemTime = {
  /** Объект с данными о времени */
  startTime: SchedulesWithItemsDtoItemItemsItemTimeStartTime;
  /** Объект с данными о времени */
  endTime: SchedulesWithItemsDtoItemItemsItemTimeEndTime;
};
