/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import type { UpdateScheduleItemDtoTimeEndTime } from './updateScheduleItemDtoTimeEndTime';
import type { UpdateScheduleItemDtoTimeStartTime } from './updateScheduleItemDtoTimeStartTime';

/**
 * Объект с временем начала и окончания в формате [HH, MM]
 */
export type UpdateScheduleItemDtoTime = {
  startTime: UpdateScheduleItemDtoTimeStartTime;
  endTime: UpdateScheduleItemDtoTimeEndTime;
};
