/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import type { UpdateBotSettingsChatTypesItem } from './updateBotSettingsChatTypesItem';

/**
 * Объект с данными для обновления настроек бота
 */
export interface UpdateBotSettings {
  /** Флаг, который отвечает за необходимость ответа только на первое сообщение, отправленное пользователем в чате */
  answerOnFirstMessage?: boolean;
  /** Типы чатов, на которые будет работать автоответ */
  chatTypes?: UpdateBotSettingsChatTypesItem[];
  /** Флаг активности бота */
  isActive?: boolean;
}
