/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import type { UpdateScheduleItemDtoTimeEndTime } from './updateScheduleItemDtoTimeEndTime';
import type { UpdateScheduleItemDtoTimeStartTime } from './updateScheduleItemDtoTimeStartTime';

export type UpdateScheduleItemDtoTime = {
  /** Объект с данными о времени */
  startTime: UpdateScheduleItemDtoTimeStartTime;
  /** Объект с данными о времени */
  endTime: UpdateScheduleItemDtoTimeEndTime;
};
