/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import type { UpdateScheduleDtoItemsItemWeekDay } from './updateScheduleDtoItemsItemWeekDay';

export type UpdateScheduleDtoItemsItem = {
  weekDay: UpdateScheduleDtoItemsItemWeekDay;
  /** @pattern ^([01]\d|2[0-3]):([0-5]\d)$ */
  startTime: string;
  /** @pattern ^([01]\d|2[0-3]):([0-5]\d)$ */
  endTime: string;
  /** @minLength 1 */
  text: string;
};
