/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import type { UpdateScheduleDtoItemsItemTimeEndTime } from './updateScheduleDtoItemsItemTimeEndTime';
import type { UpdateScheduleDtoItemsItemTimeStartTime } from './updateScheduleDtoItemsItemTimeStartTime';

/**
 * Объект с временем начала и окончания в формате [HH, MM]
 */
export type UpdateScheduleDtoItemsItemTime = {
  startTime: UpdateScheduleDtoItemsItemTimeStartTime;
  endTime: UpdateScheduleDtoItemsItemTimeEndTime;
};
