/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import type { UpdateScheduleDtoItemsItemTime } from './updateScheduleDtoItemsItemTime';
import type { UpdateScheduleDtoItemsItemWeekDay } from './updateScheduleDtoItemsItemWeekDay';

export type UpdateScheduleDtoItemsItem = {
  weekDay: UpdateScheduleDtoItemsItemWeekDay;
  /**
     * @deprecated
     * @pattern ^([01]\d|2[0-3]):([0-5]\d)$
     */
  startTime?: string;
  /**
     * @deprecated
     * @pattern ^([01]\d|2[0-3]):([0-5]\d)$
     */
  endTime?: string;
  /** Объект с временем начала и окончания в формате [HH, MM] */
  time: UpdateScheduleDtoItemsItemTime;
  /** @minLength 1 */
  text: string;
};
