/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BindScheduleDto,
  BotDtoOutput,
  BotSettings,
  SchedulesWithItemsDtoOutput,
  UnbindScheduleDto,
  UpdateBotSettings
} from '../../models';

import { customInstance } from '../../../../shared/api/client';
import type { ErrorType , BodyType } from '../../../../shared/api/client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const botControllerGetBot = (
    userId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<BotDtoOutput>(
      {url: `/api/user/${userId}/bot`, method: 'GET', signal
    },
      options);
    }




export const getBotControllerGetBotQueryKey = (userId: string,) => {
    return [
    `/api/user/${userId}/bot`
    ] as const;
    }


export const getBotControllerGetBotQueryOptions = <TData = Awaited<ReturnType<typeof botControllerGetBot>>, TError = ErrorType<unknown>>(userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof botControllerGetBot>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBotControllerGetBotQueryKey(userId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof botControllerGetBot>>> = ({ signal }) => botControllerGetBot(userId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: userId !== null && userId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof botControllerGetBot>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BotControllerGetBotQueryResult = NonNullable<Awaited<ReturnType<typeof botControllerGetBot>>>
export type BotControllerGetBotQueryError = ErrorType<unknown>


export function useBotControllerGetBot<TData = Awaited<ReturnType<typeof botControllerGetBot>>, TError = ErrorType<unknown>>(
 userId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof botControllerGetBot>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof botControllerGetBot>>,
          TError,
          Awaited<ReturnType<typeof botControllerGetBot>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBotControllerGetBot<TData = Awaited<ReturnType<typeof botControllerGetBot>>, TError = ErrorType<unknown>>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof botControllerGetBot>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof botControllerGetBot>>,
          TError,
          Awaited<ReturnType<typeof botControllerGetBot>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBotControllerGetBot<TData = Awaited<ReturnType<typeof botControllerGetBot>>, TError = ErrorType<unknown>>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof botControllerGetBot>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useBotControllerGetBot<TData = Awaited<ReturnType<typeof botControllerGetBot>>, TError = ErrorType<unknown>>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof botControllerGetBot>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBotControllerGetBotQueryOptions(userId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const botControllerDeleteBot = (
    userId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/user/${userId}/bot`, method: 'DELETE', signal
    },
      options);
    }




export const getBotControllerDeleteBotMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof botControllerDeleteBot>>, TError,{userId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof botControllerDeleteBot>>, TError,{userId: string}, TContext> => {

const mutationKey = ['botControllerDeleteBot'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof botControllerDeleteBot>>, {userId: string}> = (props) => {
          const {userId} = props ?? {};

          return  botControllerDeleteBot(userId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BotControllerDeleteBotMutationResult = NonNullable<Awaited<ReturnType<typeof botControllerDeleteBot>>>

    export type BotControllerDeleteBotMutationError = ErrorType<unknown>

    export const useBotControllerDeleteBot = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof botControllerDeleteBot>>, TError,{userId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof botControllerDeleteBot>>,
        TError,
        {userId: string},
        TContext
      > => {
      return useMutation(getBotControllerDeleteBotMutationOptions(options), queryClient);
    }
    export const botControllerBindSchedule = (
    userId: string,
    botId: string,
    bindScheduleDto: BodyType<BindScheduleDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/user/${userId}/bot/${botId}/bind-schedule`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: bindScheduleDto, signal
    },
      options);
    }




export const getBotControllerBindScheduleMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof botControllerBindSchedule>>, TError,{userId: string;botId: string;data: BodyType<BindScheduleDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof botControllerBindSchedule>>, TError,{userId: string;botId: string;data: BodyType<BindScheduleDto>}, TContext> => {

const mutationKey = ['botControllerBindSchedule'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof botControllerBindSchedule>>, {userId: string;botId: string;data: BodyType<BindScheduleDto>}> = (props) => {
          const {userId,botId,data} = props ?? {};

          return  botControllerBindSchedule(userId,botId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BotControllerBindScheduleMutationResult = NonNullable<Awaited<ReturnType<typeof botControllerBindSchedule>>>
    export type BotControllerBindScheduleMutationBody = BodyType<BindScheduleDto>
    export type BotControllerBindScheduleMutationError = ErrorType<unknown>

    export const useBotControllerBindSchedule = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof botControllerBindSchedule>>, TError,{userId: string;botId: string;data: BodyType<BindScheduleDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof botControllerBindSchedule>>,
        TError,
        {userId: string;botId: string;data: BodyType<BindScheduleDto>},
        TContext
      > => {
      return useMutation(getBotControllerBindScheduleMutationOptions(options), queryClient);
    }
    export const botControllerUnbindSchedule = (
    userId: string,
    botId: string,
    unbindScheduleDto: BodyType<UnbindScheduleDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/user/${userId}/bot/${botId}/unbind-schedule`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: unbindScheduleDto, signal
    },
      options);
    }




export const getBotControllerUnbindScheduleMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof botControllerUnbindSchedule>>, TError,{userId: string;botId: string;data: BodyType<UnbindScheduleDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof botControllerUnbindSchedule>>, TError,{userId: string;botId: string;data: BodyType<UnbindScheduleDto>}, TContext> => {

const mutationKey = ['botControllerUnbindSchedule'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof botControllerUnbindSchedule>>, {userId: string;botId: string;data: BodyType<UnbindScheduleDto>}> = (props) => {
          const {userId,botId,data} = props ?? {};

          return  botControllerUnbindSchedule(userId,botId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BotControllerUnbindScheduleMutationResult = NonNullable<Awaited<ReturnType<typeof botControllerUnbindSchedule>>>
    export type BotControllerUnbindScheduleMutationBody = BodyType<UnbindScheduleDto>
    export type BotControllerUnbindScheduleMutationError = ErrorType<unknown>

    export const useBotControllerUnbindSchedule = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof botControllerUnbindSchedule>>, TError,{userId: string;botId: string;data: BodyType<UnbindScheduleDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof botControllerUnbindSchedule>>,
        TError,
        {userId: string;botId: string;data: BodyType<UnbindScheduleDto>},
        TContext
      > => {
      return useMutation(getBotControllerUnbindScheduleMutationOptions(options), queryClient);
    }
    export const botControllerGetBotSchedules = (
    userId: string,
    botId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<SchedulesWithItemsDtoOutput>(
      {url: `/api/user/${userId}/bot/${botId}/schedule`, method: 'GET', signal
    },
      options);
    }




export const getBotControllerGetBotSchedulesQueryKey = (userId: string,
    botId: string,) => {
    return [
    `/api/user/${userId}/bot/${botId}/schedule`
    ] as const;
    }


export const getBotControllerGetBotSchedulesQueryOptions = <TData = Awaited<ReturnType<typeof botControllerGetBotSchedules>>, TError = ErrorType<unknown>>(userId: string,
    botId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof botControllerGetBotSchedules>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBotControllerGetBotSchedulesQueryKey(userId,botId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof botControllerGetBotSchedules>>> = ({ signal }) => botControllerGetBotSchedules(userId,botId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: userId !== null && userId !== undefined && botId !== null && botId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof botControllerGetBotSchedules>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BotControllerGetBotSchedulesQueryResult = NonNullable<Awaited<ReturnType<typeof botControllerGetBotSchedules>>>
export type BotControllerGetBotSchedulesQueryError = ErrorType<unknown>


export function useBotControllerGetBotSchedules<TData = Awaited<ReturnType<typeof botControllerGetBotSchedules>>, TError = ErrorType<unknown>>(
 userId: string,
    botId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof botControllerGetBotSchedules>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof botControllerGetBotSchedules>>,
          TError,
          Awaited<ReturnType<typeof botControllerGetBotSchedules>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBotControllerGetBotSchedules<TData = Awaited<ReturnType<typeof botControllerGetBotSchedules>>, TError = ErrorType<unknown>>(
 userId: string,
    botId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof botControllerGetBotSchedules>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof botControllerGetBotSchedules>>,
          TError,
          Awaited<ReturnType<typeof botControllerGetBotSchedules>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBotControllerGetBotSchedules<TData = Awaited<ReturnType<typeof botControllerGetBotSchedules>>, TError = ErrorType<unknown>>(
 userId: string,
    botId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof botControllerGetBotSchedules>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useBotControllerGetBotSchedules<TData = Awaited<ReturnType<typeof botControllerGetBotSchedules>>, TError = ErrorType<unknown>>(
 userId: string,
    botId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof botControllerGetBotSchedules>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBotControllerGetBotSchedulesQueryOptions(userId,botId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const botControllerGetBotSettings = (
    userId: string,
    botId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<BotSettings>(
      {url: `/api/user/${userId}/bot/${botId}/settings`, method: 'GET', signal
    },
      options);
    }




export const getBotControllerGetBotSettingsQueryKey = (userId: string,
    botId: string,) => {
    return [
    `/api/user/${userId}/bot/${botId}/settings`
    ] as const;
    }


export const getBotControllerGetBotSettingsQueryOptions = <TData = Awaited<ReturnType<typeof botControllerGetBotSettings>>, TError = ErrorType<unknown>>(userId: string,
    botId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof botControllerGetBotSettings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBotControllerGetBotSettingsQueryKey(userId,botId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof botControllerGetBotSettings>>> = ({ signal }) => botControllerGetBotSettings(userId,botId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: userId !== null && userId !== undefined && botId !== null && botId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof botControllerGetBotSettings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BotControllerGetBotSettingsQueryResult = NonNullable<Awaited<ReturnType<typeof botControllerGetBotSettings>>>
export type BotControllerGetBotSettingsQueryError = ErrorType<unknown>


export function useBotControllerGetBotSettings<TData = Awaited<ReturnType<typeof botControllerGetBotSettings>>, TError = ErrorType<unknown>>(
 userId: string,
    botId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof botControllerGetBotSettings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof botControllerGetBotSettings>>,
          TError,
          Awaited<ReturnType<typeof botControllerGetBotSettings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBotControllerGetBotSettings<TData = Awaited<ReturnType<typeof botControllerGetBotSettings>>, TError = ErrorType<unknown>>(
 userId: string,
    botId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof botControllerGetBotSettings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof botControllerGetBotSettings>>,
          TError,
          Awaited<ReturnType<typeof botControllerGetBotSettings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBotControllerGetBotSettings<TData = Awaited<ReturnType<typeof botControllerGetBotSettings>>, TError = ErrorType<unknown>>(
 userId: string,
    botId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof botControllerGetBotSettings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useBotControllerGetBotSettings<TData = Awaited<ReturnType<typeof botControllerGetBotSettings>>, TError = ErrorType<unknown>>(
 userId: string,
    botId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof botControllerGetBotSettings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBotControllerGetBotSettingsQueryOptions(userId,botId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const botControllerUpdateBotSettings = (
    userId: string,
    botId: string,
    updateBotSettings: BodyType<UpdateBotSettings>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<BotSettings>(
      {url: `/api/user/${userId}/bot/${botId}/settings`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateBotSettings, signal
    },
      options);
    }




export const getBotControllerUpdateBotSettingsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof botControllerUpdateBotSettings>>, TError,{userId: string;botId: string;data: BodyType<UpdateBotSettings>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof botControllerUpdateBotSettings>>, TError,{userId: string;botId: string;data: BodyType<UpdateBotSettings>}, TContext> => {

const mutationKey = ['botControllerUpdateBotSettings'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof botControllerUpdateBotSettings>>, {userId: string;botId: string;data: BodyType<UpdateBotSettings>}> = (props) => {
          const {userId,botId,data} = props ?? {};

          return  botControllerUpdateBotSettings(userId,botId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BotControllerUpdateBotSettingsMutationResult = NonNullable<Awaited<ReturnType<typeof botControllerUpdateBotSettings>>>
    export type BotControllerUpdateBotSettingsMutationBody = BodyType<UpdateBotSettings>
    export type BotControllerUpdateBotSettingsMutationError = ErrorType<unknown>

    export const useBotControllerUpdateBotSettings = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof botControllerUpdateBotSettings>>, TError,{userId: string;botId: string;data: BodyType<UpdateBotSettings>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof botControllerUpdateBotSettings>>,
        TError,
        {userId: string;botId: string;data: BodyType<UpdateBotSettings>},
        TContext
      > => {
      return useMutation(getBotControllerUpdateBotSettingsMutationOptions(options), queryClient);
    }
