/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery,
  useQueryClient
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateScheduleDto,
  ScheduleWithItemsDto,
  SchedulesWithItemsDto,
  UpdateScheduleDto
} from '../../models';

import { customInstance } from '../../client';
import type { ErrorType , BodyType } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const scheduleControllerCreateSchedule = (
    userId: string,
    createScheduleDto: BodyType<CreateScheduleDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ScheduleWithItemsDto>(
      {url: `/api/users/${userId}/schedules`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createScheduleDto, signal
    },
      options);
    }




export const getScheduleControllerCreateScheduleMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof scheduleControllerCreateSchedule>>, TError,{userId: string;data: BodyType<CreateScheduleDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof scheduleControllerCreateSchedule>>, TError,{userId: string;data: BodyType<CreateScheduleDto>}, TContext> => {

const mutationKey = ['scheduleControllerCreateSchedule'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof scheduleControllerCreateSchedule>>, {userId: string;data: BodyType<CreateScheduleDto>}> = (props) => {
          const {userId,data} = props ?? {};

          return  scheduleControllerCreateSchedule(userId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ScheduleControllerCreateScheduleMutationResult = NonNullable<Awaited<ReturnType<typeof scheduleControllerCreateSchedule>>>
    export type ScheduleControllerCreateScheduleMutationBody = BodyType<CreateScheduleDto>
    export type ScheduleControllerCreateScheduleMutationError = ErrorType<void>

    export const useScheduleControllerCreateSchedule = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof scheduleControllerCreateSchedule>>, TError,{userId: string;data: BodyType<CreateScheduleDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof scheduleControllerCreateSchedule>>,
        TError,
        {userId: string;data: BodyType<CreateScheduleDto>},
        TContext
      > => {
      return useMutation(getScheduleControllerCreateScheduleMutationOptions(options), queryClient);
    }
    export const scheduleControllerUserScheduleList = (
    userId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<SchedulesWithItemsDto>(
      {url: `/api/users/${userId}/schedules`, method: 'GET', signal
    },
      options);
    }




export const getScheduleControllerUserScheduleListQueryKey = (userId: string,) => {
    return [
    `/api/users/${userId}/schedules`
    ] as const;
    }


export const getScheduleControllerUserScheduleListQueryOptions = <TData = Awaited<ReturnType<typeof scheduleControllerUserScheduleList>>, TError = ErrorType<void>>(userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof scheduleControllerUserScheduleList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getScheduleControllerUserScheduleListQueryKey(userId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof scheduleControllerUserScheduleList>>> = ({ signal }) => scheduleControllerUserScheduleList(userId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: userId !== null && userId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof scheduleControllerUserScheduleList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ScheduleControllerUserScheduleListQueryResult = NonNullable<Awaited<ReturnType<typeof scheduleControllerUserScheduleList>>>
export type ScheduleControllerUserScheduleListQueryError = ErrorType<void>


export function useScheduleControllerUserScheduleList<TData = Awaited<ReturnType<typeof scheduleControllerUserScheduleList>>, TError = ErrorType<void>>(
 userId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof scheduleControllerUserScheduleList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof scheduleControllerUserScheduleList>>,
          TError,
          Awaited<ReturnType<typeof scheduleControllerUserScheduleList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useScheduleControllerUserScheduleList<TData = Awaited<ReturnType<typeof scheduleControllerUserScheduleList>>, TError = ErrorType<void>>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof scheduleControllerUserScheduleList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof scheduleControllerUserScheduleList>>,
          TError,
          Awaited<ReturnType<typeof scheduleControllerUserScheduleList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useScheduleControllerUserScheduleList<TData = Awaited<ReturnType<typeof scheduleControllerUserScheduleList>>, TError = ErrorType<void>>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof scheduleControllerUserScheduleList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useScheduleControllerUserScheduleList<TData = Awaited<ReturnType<typeof scheduleControllerUserScheduleList>>, TError = ErrorType<void>>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof scheduleControllerUserScheduleList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getScheduleControllerUserScheduleListQueryOptions(userId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}



export const useSetScheduleControllerUserScheduleListQueryData = () => {
  const queryClient = useQueryClient();
  return (userId: string,updater: Awaited<ReturnType<typeof scheduleControllerUserScheduleList>> | undefined | ((old: Awaited<ReturnType<typeof scheduleControllerUserScheduleList>> | undefined) => Awaited<ReturnType<typeof scheduleControllerUserScheduleList>> | undefined)) => {
    queryClient.setQueriesData<Awaited<ReturnType<typeof scheduleControllerUserScheduleList>>>({ queryKey: getScheduleControllerUserScheduleListQueryKey(userId) }, updater);
  };
}

export const useGetScheduleControllerUserScheduleListQueryData = () => {
  const queryClient = useQueryClient();
  return (userId: string,) =>
    queryClient.getQueryData<Awaited<ReturnType<typeof scheduleControllerUserScheduleList>>>(getScheduleControllerUserScheduleListQueryKey(userId));
}


export const scheduleControllerGetSchedule = (
    userId: string,
    scheduleId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ScheduleWithItemsDto>(
      {url: `/api/users/${userId}/schedules/${scheduleId}`, method: 'GET', signal
    },
      options);
    }




export const getScheduleControllerGetScheduleQueryKey = (userId: string,
    scheduleId: string,) => {
    return [
    `/api/users/${userId}/schedules/${scheduleId}`
    ] as const;
    }


export const getScheduleControllerGetScheduleQueryOptions = <TData = Awaited<ReturnType<typeof scheduleControllerGetSchedule>>, TError = ErrorType<void>>(userId: string,
    scheduleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof scheduleControllerGetSchedule>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getScheduleControllerGetScheduleQueryKey(userId,scheduleId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof scheduleControllerGetSchedule>>> = ({ signal }) => scheduleControllerGetSchedule(userId,scheduleId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: userId !== null && userId !== undefined && scheduleId !== null && scheduleId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof scheduleControllerGetSchedule>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ScheduleControllerGetScheduleQueryResult = NonNullable<Awaited<ReturnType<typeof scheduleControllerGetSchedule>>>
export type ScheduleControllerGetScheduleQueryError = ErrorType<void>


export function useScheduleControllerGetSchedule<TData = Awaited<ReturnType<typeof scheduleControllerGetSchedule>>, TError = ErrorType<void>>(
 userId: string,
    scheduleId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof scheduleControllerGetSchedule>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof scheduleControllerGetSchedule>>,
          TError,
          Awaited<ReturnType<typeof scheduleControllerGetSchedule>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useScheduleControllerGetSchedule<TData = Awaited<ReturnType<typeof scheduleControllerGetSchedule>>, TError = ErrorType<void>>(
 userId: string,
    scheduleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof scheduleControllerGetSchedule>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof scheduleControllerGetSchedule>>,
          TError,
          Awaited<ReturnType<typeof scheduleControllerGetSchedule>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useScheduleControllerGetSchedule<TData = Awaited<ReturnType<typeof scheduleControllerGetSchedule>>, TError = ErrorType<void>>(
 userId: string,
    scheduleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof scheduleControllerGetSchedule>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useScheduleControllerGetSchedule<TData = Awaited<ReturnType<typeof scheduleControllerGetSchedule>>, TError = ErrorType<void>>(
 userId: string,
    scheduleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof scheduleControllerGetSchedule>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getScheduleControllerGetScheduleQueryOptions(userId,scheduleId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}



export const useSetScheduleControllerGetScheduleQueryData = () => {
  const queryClient = useQueryClient();
  return (userId: string,
    scheduleId: string,updater: Awaited<ReturnType<typeof scheduleControllerGetSchedule>> | undefined | ((old: Awaited<ReturnType<typeof scheduleControllerGetSchedule>> | undefined) => Awaited<ReturnType<typeof scheduleControllerGetSchedule>> | undefined)) => {
    queryClient.setQueriesData<Awaited<ReturnType<typeof scheduleControllerGetSchedule>>>({ queryKey: getScheduleControllerGetScheduleQueryKey(userId,scheduleId) }, updater);
  };
}

export const useGetScheduleControllerGetScheduleQueryData = () => {
  const queryClient = useQueryClient();
  return (userId: string,
    scheduleId: string,) =>
    queryClient.getQueryData<Awaited<ReturnType<typeof scheduleControllerGetSchedule>>>(getScheduleControllerGetScheduleQueryKey(userId,scheduleId));
}


export const scheduleControllerUpdateSchedule = (
    userId: string,
    scheduleId: string,
    updateScheduleDto: BodyType<UpdateScheduleDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ScheduleWithItemsDto>(
      {url: `/api/users/${userId}/schedules/${scheduleId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateScheduleDto, signal
    },
      options);
    }




export const getScheduleControllerUpdateScheduleMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof scheduleControllerUpdateSchedule>>, TError,{userId: string;scheduleId: string;data: BodyType<UpdateScheduleDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof scheduleControllerUpdateSchedule>>, TError,{userId: string;scheduleId: string;data: BodyType<UpdateScheduleDto>}, TContext> => {

const mutationKey = ['scheduleControllerUpdateSchedule'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof scheduleControllerUpdateSchedule>>, {userId: string;scheduleId: string;data: BodyType<UpdateScheduleDto>}> = (props) => {
          const {userId,scheduleId,data} = props ?? {};

          return  scheduleControllerUpdateSchedule(userId,scheduleId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ScheduleControllerUpdateScheduleMutationResult = NonNullable<Awaited<ReturnType<typeof scheduleControllerUpdateSchedule>>>
    export type ScheduleControllerUpdateScheduleMutationBody = BodyType<UpdateScheduleDto>
    export type ScheduleControllerUpdateScheduleMutationError = ErrorType<void>

    export const useScheduleControllerUpdateSchedule = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof scheduleControllerUpdateSchedule>>, TError,{userId: string;scheduleId: string;data: BodyType<UpdateScheduleDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof scheduleControllerUpdateSchedule>>,
        TError,
        {userId: string;scheduleId: string;data: BodyType<UpdateScheduleDto>},
        TContext
      > => {
      return useMutation(getScheduleControllerUpdateScheduleMutationOptions(options), queryClient);
    }
    export const scheduleControllerDeleteSchedule = (
    userId: string,
    scheduleId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/users/${userId}/schedules/${scheduleId}`, method: 'DELETE', signal
    },
      options);
    }




export const getScheduleControllerDeleteScheduleMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof scheduleControllerDeleteSchedule>>, TError,{userId: string;scheduleId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof scheduleControllerDeleteSchedule>>, TError,{userId: string;scheduleId: string}, TContext> => {

const mutationKey = ['scheduleControllerDeleteSchedule'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof scheduleControllerDeleteSchedule>>, {userId: string;scheduleId: string}> = (props) => {
          const {userId,scheduleId} = props ?? {};

          return  scheduleControllerDeleteSchedule(userId,scheduleId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ScheduleControllerDeleteScheduleMutationResult = NonNullable<Awaited<ReturnType<typeof scheduleControllerDeleteSchedule>>>

    export type ScheduleControllerDeleteScheduleMutationError = ErrorType<void>

    export const useScheduleControllerDeleteSchedule = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof scheduleControllerDeleteSchedule>>, TError,{userId: string;scheduleId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof scheduleControllerDeleteSchedule>>,
        TError,
        {userId: string;scheduleId: string},
        TContext
      > => {
      return useMutation(getScheduleControllerDeleteScheduleMutationOptions(options), queryClient);
    }
