/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


export const AvitoCallbackControllerGetBotSettingsQueryParams = zod.object({
  "code": zod.string()
})

export const AvitoCallbackControllerGetBotSettingsResponse = zod.void()


export const BotControllerGetUserBotsParams = zod.object({
  "userId": zod.uuid()
})

export const botControllerGetUserBotsResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const botControllerGetUserBotsResponseUserIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');


export const BotControllerGetUserBotsResponseItem = zod.object({
  "id": zod.uuid().regex(botControllerGetUserBotsResponseIdRegExp),
  "userId": zod.uuid().regex(botControllerGetUserBotsResponseUserIdRegExp)
}).describe('Объект с информацией о боте')
export const BotControllerGetUserBotsResponse = zod.array(BotControllerGetUserBotsResponseItem)


export const BotControllerGetBotParams = zod.object({
  "userId": zod.uuid(),
  "botId": zod.uuid()
})

export const botControllerGetBotResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const botControllerGetBotResponseUserIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');


export const BotControllerGetBotResponse = zod.object({
  "id": zod.uuid().regex(botControllerGetBotResponseIdRegExp),
  "userId": zod.uuid().regex(botControllerGetBotResponseUserIdRegExp)
}).describe('Объект с информацией о боте')


export const BotControllerDeleteBotParams = zod.object({
  "userId": zod.uuid(),
  "botId": zod.uuid()
})

export const BotControllerDeleteBotResponse = zod.unknown()


export const BotControllerBindScheduleParams = zod.object({
  "botId": zod.uuid(),
  "userId": zod.uuid()
})

export const botControllerBindScheduleBodyScheduleIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');


export const BotControllerBindScheduleBody = zod.object({
  "scheduleId": zod.uuid().regex(botControllerBindScheduleBodyScheduleIdRegExp)
})

export const BotControllerBindScheduleResponse = zod.void()


export const BotControllerUnbindScheduleParams = zod.object({
  "botId": zod.uuid(),
  "userId": zod.uuid()
})

export const botControllerUnbindScheduleBodyScheduleIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');


export const BotControllerUnbindScheduleBody = zod.object({
  "scheduleId": zod.uuid().regex(botControllerUnbindScheduleBodyScheduleIdRegExp)
})

export const BotControllerUnbindScheduleResponse = zod.void()


export const BotControllerGetBotSchedulesParams = zod.object({
  "botId": zod.uuid(),
  "userId": zod.uuid()
})

export const botControllerGetBotSchedulesResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');

export const botControllerGetBotSchedulesResponseItemsItemIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const botControllerGetBotSchedulesResponseItemsItemStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const botControllerGetBotSchedulesResponseItemsItemEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const botControllerGetBotSchedulesResponseItemsItemTimeStartTimeHoursMin = 0;
export const botControllerGetBotSchedulesResponseItemsItemTimeStartTimeHoursMax = 23;

export const botControllerGetBotSchedulesResponseItemsItemTimeStartTimeMinutesMin = 0;
export const botControllerGetBotSchedulesResponseItemsItemTimeStartTimeMinutesMax = 59;

export const botControllerGetBotSchedulesResponseItemsItemTimeEndTimeHoursMin = 0;
export const botControllerGetBotSchedulesResponseItemsItemTimeEndTimeHoursMax = 23;

export const botControllerGetBotSchedulesResponseItemsItemTimeEndTimeMinutesMin = 0;
export const botControllerGetBotSchedulesResponseItemsItemTimeEndTimeMinutesMax = 59;




export const BotControllerGetBotSchedulesResponseItem = zod.object({
  "id": zod.uuid().regex(botControllerGetBotSchedulesResponseIdRegExp),
  "name": zod.string().min(1),
  "items": zod.array(zod.object({
  "id": zod.uuid().regex(botControllerGetBotSchedulesResponseItemsItemIdRegExp),
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(botControllerGetBotSchedulesResponseItemsItemStartTimeRegExp).optional().describe('Строка времени в формате [HH:mm]'),
  "endTime": zod.string().regex(botControllerGetBotSchedulesResponseItemsItemEndTimeRegExp).optional().describe('Строка времени в формате [HH:mm]'),
  "time": zod.object({
  "startTime": zod.object({
  "hours": zod.int().min(botControllerGetBotSchedulesResponseItemsItemTimeStartTimeHoursMin).max(botControllerGetBotSchedulesResponseItemsItemTimeStartTimeHoursMax),
  "minutes": zod.int().min(botControllerGetBotSchedulesResponseItemsItemTimeStartTimeMinutesMin).max(botControllerGetBotSchedulesResponseItemsItemTimeStartTimeMinutesMax)
}).describe('Объект с данными о времени'),
  "endTime": zod.object({
  "hours": zod.int().min(botControllerGetBotSchedulesResponseItemsItemTimeEndTimeHoursMin).max(botControllerGetBotSchedulesResponseItemsItemTimeEndTimeHoursMax),
  "minutes": zod.int().min(botControllerGetBotSchedulesResponseItemsItemTimeEndTimeMinutesMin).max(botControllerGetBotSchedulesResponseItemsItemTimeEndTimeMinutesMax)
}).describe('Объект с данными о времени')
}),
  "text": zod.string().min(1)
}))
})
export const BotControllerGetBotSchedulesResponse = zod.array(BotControllerGetBotSchedulesResponseItem)


export const BotControllerGetBotSettingsParams = zod.object({
  "botId": zod.uuid(),
  "userId": zod.uuid()
})

export const BotControllerGetBotSettingsResponse = zod.object({
  "answerOnFirstMessage": zod.boolean().describe('Флаг, который отвечает за необходимость ответа только на первое сообщение, отправленное пользователем в чате'),
  "chatTypes": zod.array(zod.enum(['u2i', 'u2u'])).describe('Типы чатов, на которые будет работать автоответ'),
  "isActive": zod.boolean().describe('Флаг активности бота')
}).describe('Объект с настройками бота')


export const BotControllerUpdateBotSettingsParams = zod.object({
  "botId": zod.uuid(),
  "userId": zod.uuid()
})

export const BotControllerUpdateBotSettingsBody = zod.object({
  "answerOnFirstMessage": zod.boolean().optional().describe('Флаг, который отвечает за необходимость ответа только на первое сообщение, отправленное пользователем в чате'),
  "chatTypes": zod.array(zod.enum(['u2i', 'u2u'])).optional().describe('Типы чатов, на которые будет работать автоответ'),
  "isActive": zod.boolean().optional().describe('Флаг активности бота')
}).describe('Объект с данными для обновления настроек бота')

export const BotControllerUpdateBotSettingsResponse = zod.object({
  "answerOnFirstMessage": zod.boolean().describe('Флаг, который отвечает за необходимость ответа только на первое сообщение, отправленное пользователем в чате'),
  "chatTypes": zod.array(zod.enum(['u2i', 'u2u'])).describe('Типы чатов, на которые будет работать автоответ'),
  "isActive": zod.boolean().describe('Флаг активности бота')
}).describe('Объект с настройками бота')


export const ScheduleControllerCreateScheduleParams = zod.object({
  "userId": zod.uuid()
})




export const ScheduleControllerCreateScheduleBody = zod.object({
  "name": zod.string().min(1),
  "description": zod.string().optional()
})

export const scheduleControllerCreateScheduleResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');

export const scheduleControllerCreateScheduleResponseItemsItemIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const scheduleControllerCreateScheduleResponseItemsItemStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleControllerCreateScheduleResponseItemsItemEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleControllerCreateScheduleResponseItemsItemTimeStartTimeHoursMin = 0;
export const scheduleControllerCreateScheduleResponseItemsItemTimeStartTimeHoursMax = 23;

export const scheduleControllerCreateScheduleResponseItemsItemTimeStartTimeMinutesMin = 0;
export const scheduleControllerCreateScheduleResponseItemsItemTimeStartTimeMinutesMax = 59;

export const scheduleControllerCreateScheduleResponseItemsItemTimeEndTimeHoursMin = 0;
export const scheduleControllerCreateScheduleResponseItemsItemTimeEndTimeHoursMax = 23;

export const scheduleControllerCreateScheduleResponseItemsItemTimeEndTimeMinutesMin = 0;
export const scheduleControllerCreateScheduleResponseItemsItemTimeEndTimeMinutesMax = 59;




export const ScheduleControllerCreateScheduleResponse = zod.object({
  "id": zod.uuid().regex(scheduleControllerCreateScheduleResponseIdRegExp),
  "name": zod.string().min(1),
  "items": zod.array(zod.object({
  "id": zod.uuid().regex(scheduleControllerCreateScheduleResponseItemsItemIdRegExp),
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(scheduleControllerCreateScheduleResponseItemsItemStartTimeRegExp).optional().describe('Строка времени в формате [HH:mm]'),
  "endTime": zod.string().regex(scheduleControllerCreateScheduleResponseItemsItemEndTimeRegExp).optional().describe('Строка времени в формате [HH:mm]'),
  "time": zod.object({
  "startTime": zod.object({
  "hours": zod.int().min(scheduleControllerCreateScheduleResponseItemsItemTimeStartTimeHoursMin).max(scheduleControllerCreateScheduleResponseItemsItemTimeStartTimeHoursMax),
  "minutes": zod.int().min(scheduleControllerCreateScheduleResponseItemsItemTimeStartTimeMinutesMin).max(scheduleControllerCreateScheduleResponseItemsItemTimeStartTimeMinutesMax)
}).describe('Объект с данными о времени'),
  "endTime": zod.object({
  "hours": zod.int().min(scheduleControllerCreateScheduleResponseItemsItemTimeEndTimeHoursMin).max(scheduleControllerCreateScheduleResponseItemsItemTimeEndTimeHoursMax),
  "minutes": zod.int().min(scheduleControllerCreateScheduleResponseItemsItemTimeEndTimeMinutesMin).max(scheduleControllerCreateScheduleResponseItemsItemTimeEndTimeMinutesMax)
}).describe('Объект с данными о времени')
}),
  "text": zod.string().min(1)
}))
})


export const ScheduleControllerUserScheduleListParams = zod.object({
  "userId": zod.uuid()
})

export const scheduleControllerUserScheduleListResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');

export const scheduleControllerUserScheduleListResponseItemsItemIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const scheduleControllerUserScheduleListResponseItemsItemStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleControllerUserScheduleListResponseItemsItemEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleControllerUserScheduleListResponseItemsItemTimeStartTimeHoursMin = 0;
export const scheduleControllerUserScheduleListResponseItemsItemTimeStartTimeHoursMax = 23;

export const scheduleControllerUserScheduleListResponseItemsItemTimeStartTimeMinutesMin = 0;
export const scheduleControllerUserScheduleListResponseItemsItemTimeStartTimeMinutesMax = 59;

export const scheduleControllerUserScheduleListResponseItemsItemTimeEndTimeHoursMin = 0;
export const scheduleControllerUserScheduleListResponseItemsItemTimeEndTimeHoursMax = 23;

export const scheduleControllerUserScheduleListResponseItemsItemTimeEndTimeMinutesMin = 0;
export const scheduleControllerUserScheduleListResponseItemsItemTimeEndTimeMinutesMax = 59;




export const ScheduleControllerUserScheduleListResponseItem = zod.object({
  "id": zod.uuid().regex(scheduleControllerUserScheduleListResponseIdRegExp),
  "name": zod.string().min(1),
  "items": zod.array(zod.object({
  "id": zod.uuid().regex(scheduleControllerUserScheduleListResponseItemsItemIdRegExp),
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(scheduleControllerUserScheduleListResponseItemsItemStartTimeRegExp).optional().describe('Строка времени в формате [HH:mm]'),
  "endTime": zod.string().regex(scheduleControllerUserScheduleListResponseItemsItemEndTimeRegExp).optional().describe('Строка времени в формате [HH:mm]'),
  "time": zod.object({
  "startTime": zod.object({
  "hours": zod.int().min(scheduleControllerUserScheduleListResponseItemsItemTimeStartTimeHoursMin).max(scheduleControllerUserScheduleListResponseItemsItemTimeStartTimeHoursMax),
  "minutes": zod.int().min(scheduleControllerUserScheduleListResponseItemsItemTimeStartTimeMinutesMin).max(scheduleControllerUserScheduleListResponseItemsItemTimeStartTimeMinutesMax)
}).describe('Объект с данными о времени'),
  "endTime": zod.object({
  "hours": zod.int().min(scheduleControllerUserScheduleListResponseItemsItemTimeEndTimeHoursMin).max(scheduleControllerUserScheduleListResponseItemsItemTimeEndTimeHoursMax),
  "minutes": zod.int().min(scheduleControllerUserScheduleListResponseItemsItemTimeEndTimeMinutesMin).max(scheduleControllerUserScheduleListResponseItemsItemTimeEndTimeMinutesMax)
}).describe('Объект с данными о времени')
}),
  "text": zod.string().min(1)
}))
})
export const ScheduleControllerUserScheduleListResponse = zod.array(ScheduleControllerUserScheduleListResponseItem)


export const ScheduleControllerGetScheduleParams = zod.object({
  "scheduleId": zod.string(),
  "userId": zod.uuid()
})

export const scheduleControllerGetScheduleResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');

export const scheduleControllerGetScheduleResponseItemsItemIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const scheduleControllerGetScheduleResponseItemsItemStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleControllerGetScheduleResponseItemsItemEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleControllerGetScheduleResponseItemsItemTimeStartTimeHoursMin = 0;
export const scheduleControllerGetScheduleResponseItemsItemTimeStartTimeHoursMax = 23;

export const scheduleControllerGetScheduleResponseItemsItemTimeStartTimeMinutesMin = 0;
export const scheduleControllerGetScheduleResponseItemsItemTimeStartTimeMinutesMax = 59;

export const scheduleControllerGetScheduleResponseItemsItemTimeEndTimeHoursMin = 0;
export const scheduleControllerGetScheduleResponseItemsItemTimeEndTimeHoursMax = 23;

export const scheduleControllerGetScheduleResponseItemsItemTimeEndTimeMinutesMin = 0;
export const scheduleControllerGetScheduleResponseItemsItemTimeEndTimeMinutesMax = 59;




export const ScheduleControllerGetScheduleResponse = zod.object({
  "id": zod.uuid().regex(scheduleControllerGetScheduleResponseIdRegExp),
  "name": zod.string().min(1),
  "items": zod.array(zod.object({
  "id": zod.uuid().regex(scheduleControllerGetScheduleResponseItemsItemIdRegExp),
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(scheduleControllerGetScheduleResponseItemsItemStartTimeRegExp).optional().describe('Строка времени в формате [HH:mm]'),
  "endTime": zod.string().regex(scheduleControllerGetScheduleResponseItemsItemEndTimeRegExp).optional().describe('Строка времени в формате [HH:mm]'),
  "time": zod.object({
  "startTime": zod.object({
  "hours": zod.int().min(scheduleControllerGetScheduleResponseItemsItemTimeStartTimeHoursMin).max(scheduleControllerGetScheduleResponseItemsItemTimeStartTimeHoursMax),
  "minutes": zod.int().min(scheduleControllerGetScheduleResponseItemsItemTimeStartTimeMinutesMin).max(scheduleControllerGetScheduleResponseItemsItemTimeStartTimeMinutesMax)
}).describe('Объект с данными о времени'),
  "endTime": zod.object({
  "hours": zod.int().min(scheduleControllerGetScheduleResponseItemsItemTimeEndTimeHoursMin).max(scheduleControllerGetScheduleResponseItemsItemTimeEndTimeHoursMax),
  "minutes": zod.int().min(scheduleControllerGetScheduleResponseItemsItemTimeEndTimeMinutesMin).max(scheduleControllerGetScheduleResponseItemsItemTimeEndTimeMinutesMax)
}).describe('Объект с данными о времени')
}),
  "text": zod.string().min(1)
}))
})


export const ScheduleControllerUpdateScheduleParams = zod.object({
  "scheduleId": zod.string(),
  "userId": zod.uuid()
})




export const ScheduleControllerUpdateScheduleBody = zod.object({
  "name": zod.string().min(1).optional(),
  "description": zod.string().optional()
})

export const scheduleControllerUpdateScheduleResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');

export const scheduleControllerUpdateScheduleResponseItemsItemIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const scheduleControllerUpdateScheduleResponseItemsItemStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleControllerUpdateScheduleResponseItemsItemEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleControllerUpdateScheduleResponseItemsItemTimeStartTimeHoursMin = 0;
export const scheduleControllerUpdateScheduleResponseItemsItemTimeStartTimeHoursMax = 23;

export const scheduleControllerUpdateScheduleResponseItemsItemTimeStartTimeMinutesMin = 0;
export const scheduleControllerUpdateScheduleResponseItemsItemTimeStartTimeMinutesMax = 59;

export const scheduleControllerUpdateScheduleResponseItemsItemTimeEndTimeHoursMin = 0;
export const scheduleControllerUpdateScheduleResponseItemsItemTimeEndTimeHoursMax = 23;

export const scheduleControllerUpdateScheduleResponseItemsItemTimeEndTimeMinutesMin = 0;
export const scheduleControllerUpdateScheduleResponseItemsItemTimeEndTimeMinutesMax = 59;




export const ScheduleControllerUpdateScheduleResponse = zod.object({
  "id": zod.uuid().regex(scheduleControllerUpdateScheduleResponseIdRegExp),
  "name": zod.string().min(1),
  "items": zod.array(zod.object({
  "id": zod.uuid().regex(scheduleControllerUpdateScheduleResponseItemsItemIdRegExp),
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(scheduleControllerUpdateScheduleResponseItemsItemStartTimeRegExp).optional().describe('Строка времени в формате [HH:mm]'),
  "endTime": zod.string().regex(scheduleControllerUpdateScheduleResponseItemsItemEndTimeRegExp).optional().describe('Строка времени в формате [HH:mm]'),
  "time": zod.object({
  "startTime": zod.object({
  "hours": zod.int().min(scheduleControllerUpdateScheduleResponseItemsItemTimeStartTimeHoursMin).max(scheduleControllerUpdateScheduleResponseItemsItemTimeStartTimeHoursMax),
  "minutes": zod.int().min(scheduleControllerUpdateScheduleResponseItemsItemTimeStartTimeMinutesMin).max(scheduleControllerUpdateScheduleResponseItemsItemTimeStartTimeMinutesMax)
}).describe('Объект с данными о времени'),
  "endTime": zod.object({
  "hours": zod.int().min(scheduleControllerUpdateScheduleResponseItemsItemTimeEndTimeHoursMin).max(scheduleControllerUpdateScheduleResponseItemsItemTimeEndTimeHoursMax),
  "minutes": zod.int().min(scheduleControllerUpdateScheduleResponseItemsItemTimeEndTimeMinutesMin).max(scheduleControllerUpdateScheduleResponseItemsItemTimeEndTimeMinutesMax)
}).describe('Объект с данными о времени')
}),
  "text": zod.string().min(1)
}))
})


export const ScheduleControllerDeleteScheduleParams = zod.object({
  "scheduleId": zod.string(),
  "userId": zod.uuid()
})

export const ScheduleControllerDeleteScheduleResponse = zod.void()


export const ScheduleItemControllerCreateScheduleItemParams = zod.object({
  "scheduleId": zod.uuid(),
  "userId": zod.uuid()
})

export const scheduleItemControllerCreateScheduleItemBodyStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleItemControllerCreateScheduleItemBodyEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleItemControllerCreateScheduleItemBodyTimeStartTimeHoursMin = 0;
export const scheduleItemControllerCreateScheduleItemBodyTimeStartTimeHoursMax = 23;

export const scheduleItemControllerCreateScheduleItemBodyTimeStartTimeMinutesMin = 0;
export const scheduleItemControllerCreateScheduleItemBodyTimeStartTimeMinutesMax = 59;

export const scheduleItemControllerCreateScheduleItemBodyTimeEndTimeHoursMin = 0;
export const scheduleItemControllerCreateScheduleItemBodyTimeEndTimeHoursMax = 23;

export const scheduleItemControllerCreateScheduleItemBodyTimeEndTimeMinutesMin = 0;
export const scheduleItemControllerCreateScheduleItemBodyTimeEndTimeMinutesMax = 59;




export const ScheduleItemControllerCreateScheduleItemBody = zod.object({
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(scheduleItemControllerCreateScheduleItemBodyStartTimeRegExp).optional().describe('Строка времени в формате [HH:mm]'),
  "endTime": zod.string().regex(scheduleItemControllerCreateScheduleItemBodyEndTimeRegExp).optional().describe('Строка времени в формате [HH:mm]'),
  "time": zod.object({
  "startTime": zod.object({
  "hours": zod.int().min(scheduleItemControllerCreateScheduleItemBodyTimeStartTimeHoursMin).max(scheduleItemControllerCreateScheduleItemBodyTimeStartTimeHoursMax),
  "minutes": zod.int().min(scheduleItemControllerCreateScheduleItemBodyTimeStartTimeMinutesMin).max(scheduleItemControllerCreateScheduleItemBodyTimeStartTimeMinutesMax)
}).describe('Объект с данными о времени'),
  "endTime": zod.object({
  "hours": zod.int().min(scheduleItemControllerCreateScheduleItemBodyTimeEndTimeHoursMin).max(scheduleItemControllerCreateScheduleItemBodyTimeEndTimeHoursMax),
  "minutes": zod.int().min(scheduleItemControllerCreateScheduleItemBodyTimeEndTimeMinutesMin).max(scheduleItemControllerCreateScheduleItemBodyTimeEndTimeMinutesMax)
}).describe('Объект с данными о времени')
}),
  "text": zod.string().min(1)
}).describe('Объект с данными для создания части расписания')

export const scheduleItemControllerCreateScheduleItemResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const scheduleItemControllerCreateScheduleItemResponseStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleItemControllerCreateScheduleItemResponseEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleItemControllerCreateScheduleItemResponseTimeStartTimeHoursMin = 0;
export const scheduleItemControllerCreateScheduleItemResponseTimeStartTimeHoursMax = 23;

export const scheduleItemControllerCreateScheduleItemResponseTimeStartTimeMinutesMin = 0;
export const scheduleItemControllerCreateScheduleItemResponseTimeStartTimeMinutesMax = 59;

export const scheduleItemControllerCreateScheduleItemResponseTimeEndTimeHoursMin = 0;
export const scheduleItemControllerCreateScheduleItemResponseTimeEndTimeHoursMax = 23;

export const scheduleItemControllerCreateScheduleItemResponseTimeEndTimeMinutesMin = 0;
export const scheduleItemControllerCreateScheduleItemResponseTimeEndTimeMinutesMax = 59;




export const ScheduleItemControllerCreateScheduleItemResponse = zod.object({
  "id": zod.uuid().regex(scheduleItemControllerCreateScheduleItemResponseIdRegExp),
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(scheduleItemControllerCreateScheduleItemResponseStartTimeRegExp).optional().describe('Строка времени в формате [HH:mm]'),
  "endTime": zod.string().regex(scheduleItemControllerCreateScheduleItemResponseEndTimeRegExp).optional().describe('Строка времени в формате [HH:mm]'),
  "time": zod.object({
  "startTime": zod.object({
  "hours": zod.int().min(scheduleItemControllerCreateScheduleItemResponseTimeStartTimeHoursMin).max(scheduleItemControllerCreateScheduleItemResponseTimeStartTimeHoursMax),
  "minutes": zod.int().min(scheduleItemControllerCreateScheduleItemResponseTimeStartTimeMinutesMin).max(scheduleItemControllerCreateScheduleItemResponseTimeStartTimeMinutesMax)
}).describe('Объект с данными о времени'),
  "endTime": zod.object({
  "hours": zod.int().min(scheduleItemControllerCreateScheduleItemResponseTimeEndTimeHoursMin).max(scheduleItemControllerCreateScheduleItemResponseTimeEndTimeHoursMax),
  "minutes": zod.int().min(scheduleItemControllerCreateScheduleItemResponseTimeEndTimeMinutesMin).max(scheduleItemControllerCreateScheduleItemResponseTimeEndTimeMinutesMax)
}).describe('Объект с данными о времени')
}),
  "text": zod.string().min(1)
})


export const ScheduleItemControllerGetScheduleItemsParams = zod.object({
  "scheduleId": zod.uuid(),
  "userId": zod.uuid()
})

export const scheduleItemControllerGetScheduleItemsResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const scheduleItemControllerGetScheduleItemsResponseStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleItemControllerGetScheduleItemsResponseEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleItemControllerGetScheduleItemsResponseTimeStartTimeHoursMin = 0;
export const scheduleItemControllerGetScheduleItemsResponseTimeStartTimeHoursMax = 23;

export const scheduleItemControllerGetScheduleItemsResponseTimeStartTimeMinutesMin = 0;
export const scheduleItemControllerGetScheduleItemsResponseTimeStartTimeMinutesMax = 59;

export const scheduleItemControllerGetScheduleItemsResponseTimeEndTimeHoursMin = 0;
export const scheduleItemControllerGetScheduleItemsResponseTimeEndTimeHoursMax = 23;

export const scheduleItemControllerGetScheduleItemsResponseTimeEndTimeMinutesMin = 0;
export const scheduleItemControllerGetScheduleItemsResponseTimeEndTimeMinutesMax = 59;




export const ScheduleItemControllerGetScheduleItemsResponseItem = zod.object({
  "id": zod.uuid().regex(scheduleItemControllerGetScheduleItemsResponseIdRegExp),
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(scheduleItemControllerGetScheduleItemsResponseStartTimeRegExp).optional().describe('Строка времени в формате [HH:mm]'),
  "endTime": zod.string().regex(scheduleItemControllerGetScheduleItemsResponseEndTimeRegExp).optional().describe('Строка времени в формате [HH:mm]'),
  "time": zod.object({
  "startTime": zod.object({
  "hours": zod.int().min(scheduleItemControllerGetScheduleItemsResponseTimeStartTimeHoursMin).max(scheduleItemControllerGetScheduleItemsResponseTimeStartTimeHoursMax),
  "minutes": zod.int().min(scheduleItemControllerGetScheduleItemsResponseTimeStartTimeMinutesMin).max(scheduleItemControllerGetScheduleItemsResponseTimeStartTimeMinutesMax)
}).describe('Объект с данными о времени'),
  "endTime": zod.object({
  "hours": zod.int().min(scheduleItemControllerGetScheduleItemsResponseTimeEndTimeHoursMin).max(scheduleItemControllerGetScheduleItemsResponseTimeEndTimeHoursMax),
  "minutes": zod.int().min(scheduleItemControllerGetScheduleItemsResponseTimeEndTimeMinutesMin).max(scheduleItemControllerGetScheduleItemsResponseTimeEndTimeMinutesMax)
}).describe('Объект с данными о времени')
}),
  "text": zod.string().min(1)
})
export const ScheduleItemControllerGetScheduleItemsResponse = zod.array(ScheduleItemControllerGetScheduleItemsResponseItem)


export const ScheduleItemControllerBulkCreateScheduleItemsParams = zod.object({
  "scheduleId": zod.uuid(),
  "userId": zod.uuid()
})

export const scheduleItemControllerBulkCreateScheduleItemsBodyItemsItemStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleItemControllerBulkCreateScheduleItemsBodyItemsItemEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleItemControllerBulkCreateScheduleItemsBodyItemsItemTimeStartTimeHoursMin = 0;
export const scheduleItemControllerBulkCreateScheduleItemsBodyItemsItemTimeStartTimeHoursMax = 23;

export const scheduleItemControllerBulkCreateScheduleItemsBodyItemsItemTimeStartTimeMinutesMin = 0;
export const scheduleItemControllerBulkCreateScheduleItemsBodyItemsItemTimeStartTimeMinutesMax = 59;

export const scheduleItemControllerBulkCreateScheduleItemsBodyItemsItemTimeEndTimeHoursMin = 0;
export const scheduleItemControllerBulkCreateScheduleItemsBodyItemsItemTimeEndTimeHoursMax = 23;

export const scheduleItemControllerBulkCreateScheduleItemsBodyItemsItemTimeEndTimeMinutesMin = 0;
export const scheduleItemControllerBulkCreateScheduleItemsBodyItemsItemTimeEndTimeMinutesMax = 59;




export const ScheduleItemControllerBulkCreateScheduleItemsBody = zod.object({
  "items": zod.array(zod.object({
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(scheduleItemControllerBulkCreateScheduleItemsBodyItemsItemStartTimeRegExp).optional().describe('Строка времени в формате [HH:mm]'),
  "endTime": zod.string().regex(scheduleItemControllerBulkCreateScheduleItemsBodyItemsItemEndTimeRegExp).optional().describe('Строка времени в формате [HH:mm]'),
  "time": zod.object({
  "startTime": zod.object({
  "hours": zod.int().min(scheduleItemControllerBulkCreateScheduleItemsBodyItemsItemTimeStartTimeHoursMin).max(scheduleItemControllerBulkCreateScheduleItemsBodyItemsItemTimeStartTimeHoursMax),
  "minutes": zod.int().min(scheduleItemControllerBulkCreateScheduleItemsBodyItemsItemTimeStartTimeMinutesMin).max(scheduleItemControllerBulkCreateScheduleItemsBodyItemsItemTimeStartTimeMinutesMax)
}).describe('Объект с данными о времени'),
  "endTime": zod.object({
  "hours": zod.int().min(scheduleItemControllerBulkCreateScheduleItemsBodyItemsItemTimeEndTimeHoursMin).max(scheduleItemControllerBulkCreateScheduleItemsBodyItemsItemTimeEndTimeHoursMax),
  "minutes": zod.int().min(scheduleItemControllerBulkCreateScheduleItemsBodyItemsItemTimeEndTimeMinutesMin).max(scheduleItemControllerBulkCreateScheduleItemsBodyItemsItemTimeEndTimeMinutesMax)
}).describe('Объект с данными о времени')
}),
  "text": zod.string().min(1)
}).describe('Объект с данными для создания части расписания'))
})

export const scheduleItemControllerBulkCreateScheduleItemsResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const scheduleItemControllerBulkCreateScheduleItemsResponseStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleItemControllerBulkCreateScheduleItemsResponseEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleItemControllerBulkCreateScheduleItemsResponseTimeStartTimeHoursMin = 0;
export const scheduleItemControllerBulkCreateScheduleItemsResponseTimeStartTimeHoursMax = 23;

export const scheduleItemControllerBulkCreateScheduleItemsResponseTimeStartTimeMinutesMin = 0;
export const scheduleItemControllerBulkCreateScheduleItemsResponseTimeStartTimeMinutesMax = 59;

export const scheduleItemControllerBulkCreateScheduleItemsResponseTimeEndTimeHoursMin = 0;
export const scheduleItemControllerBulkCreateScheduleItemsResponseTimeEndTimeHoursMax = 23;

export const scheduleItemControllerBulkCreateScheduleItemsResponseTimeEndTimeMinutesMin = 0;
export const scheduleItemControllerBulkCreateScheduleItemsResponseTimeEndTimeMinutesMax = 59;




export const ScheduleItemControllerBulkCreateScheduleItemsResponseItem = zod.object({
  "id": zod.uuid().regex(scheduleItemControllerBulkCreateScheduleItemsResponseIdRegExp),
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(scheduleItemControllerBulkCreateScheduleItemsResponseStartTimeRegExp).optional().describe('Строка времени в формате [HH:mm]'),
  "endTime": zod.string().regex(scheduleItemControllerBulkCreateScheduleItemsResponseEndTimeRegExp).optional().describe('Строка времени в формате [HH:mm]'),
  "time": zod.object({
  "startTime": zod.object({
  "hours": zod.int().min(scheduleItemControllerBulkCreateScheduleItemsResponseTimeStartTimeHoursMin).max(scheduleItemControllerBulkCreateScheduleItemsResponseTimeStartTimeHoursMax),
  "minutes": zod.int().min(scheduleItemControllerBulkCreateScheduleItemsResponseTimeStartTimeMinutesMin).max(scheduleItemControllerBulkCreateScheduleItemsResponseTimeStartTimeMinutesMax)
}).describe('Объект с данными о времени'),
  "endTime": zod.object({
  "hours": zod.int().min(scheduleItemControllerBulkCreateScheduleItemsResponseTimeEndTimeHoursMin).max(scheduleItemControllerBulkCreateScheduleItemsResponseTimeEndTimeHoursMax),
  "minutes": zod.int().min(scheduleItemControllerBulkCreateScheduleItemsResponseTimeEndTimeMinutesMin).max(scheduleItemControllerBulkCreateScheduleItemsResponseTimeEndTimeMinutesMax)
}).describe('Объект с данными о времени')
}),
  "text": zod.string().min(1)
})
export const ScheduleItemControllerBulkCreateScheduleItemsResponse = zod.array(ScheduleItemControllerBulkCreateScheduleItemsResponseItem)


export const ScheduleItemControllerBulkUpdateScheduleItemsParams = zod.object({
  "scheduleId": zod.uuid(),
  "userId": zod.uuid()
})

export const scheduleItemControllerBulkUpdateScheduleItemsBodyItemsItemIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const scheduleItemControllerBulkUpdateScheduleItemsBodyItemsItemStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleItemControllerBulkUpdateScheduleItemsBodyItemsItemEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleItemControllerBulkUpdateScheduleItemsBodyItemsItemTimeStartTimeHoursMin = 0;
export const scheduleItemControllerBulkUpdateScheduleItemsBodyItemsItemTimeStartTimeHoursMax = 23;

export const scheduleItemControllerBulkUpdateScheduleItemsBodyItemsItemTimeStartTimeMinutesMin = 0;
export const scheduleItemControllerBulkUpdateScheduleItemsBodyItemsItemTimeStartTimeMinutesMax = 59;

export const scheduleItemControllerBulkUpdateScheduleItemsBodyItemsItemTimeEndTimeHoursMin = 0;
export const scheduleItemControllerBulkUpdateScheduleItemsBodyItemsItemTimeEndTimeHoursMax = 23;

export const scheduleItemControllerBulkUpdateScheduleItemsBodyItemsItemTimeEndTimeMinutesMin = 0;
export const scheduleItemControllerBulkUpdateScheduleItemsBodyItemsItemTimeEndTimeMinutesMax = 59;




export const ScheduleItemControllerBulkUpdateScheduleItemsBody = zod.object({
  "items": zod.array(zod.object({
  "id": zod.uuid().regex(scheduleItemControllerBulkUpdateScheduleItemsBodyItemsItemIdRegExp),
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']).optional(),
  "startTime": zod.string().regex(scheduleItemControllerBulkUpdateScheduleItemsBodyItemsItemStartTimeRegExp).optional().describe('Строка времени в формате [HH:mm]'),
  "endTime": zod.string().regex(scheduleItemControllerBulkUpdateScheduleItemsBodyItemsItemEndTimeRegExp).optional().describe('Строка времени в формате [HH:mm]'),
  "time": zod.object({
  "startTime": zod.object({
  "hours": zod.int().min(scheduleItemControllerBulkUpdateScheduleItemsBodyItemsItemTimeStartTimeHoursMin).max(scheduleItemControllerBulkUpdateScheduleItemsBodyItemsItemTimeStartTimeHoursMax),
  "minutes": zod.int().min(scheduleItemControllerBulkUpdateScheduleItemsBodyItemsItemTimeStartTimeMinutesMin).max(scheduleItemControllerBulkUpdateScheduleItemsBodyItemsItemTimeStartTimeMinutesMax)
}).describe('Объект с данными о времени'),
  "endTime": zod.object({
  "hours": zod.int().min(scheduleItemControllerBulkUpdateScheduleItemsBodyItemsItemTimeEndTimeHoursMin).max(scheduleItemControllerBulkUpdateScheduleItemsBodyItemsItemTimeEndTimeHoursMax),
  "minutes": zod.int().min(scheduleItemControllerBulkUpdateScheduleItemsBodyItemsItemTimeEndTimeMinutesMin).max(scheduleItemControllerBulkUpdateScheduleItemsBodyItemsItemTimeEndTimeMinutesMax)
}).describe('Объект с данными о времени')
}).optional(),
  "text": zod.string().min(1).optional()
}).describe('Объект с данными для обновления части расписания'))
})

export const scheduleItemControllerBulkUpdateScheduleItemsResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const scheduleItemControllerBulkUpdateScheduleItemsResponseStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleItemControllerBulkUpdateScheduleItemsResponseEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleItemControllerBulkUpdateScheduleItemsResponseTimeStartTimeHoursMin = 0;
export const scheduleItemControllerBulkUpdateScheduleItemsResponseTimeStartTimeHoursMax = 23;

export const scheduleItemControllerBulkUpdateScheduleItemsResponseTimeStartTimeMinutesMin = 0;
export const scheduleItemControllerBulkUpdateScheduleItemsResponseTimeStartTimeMinutesMax = 59;

export const scheduleItemControllerBulkUpdateScheduleItemsResponseTimeEndTimeHoursMin = 0;
export const scheduleItemControllerBulkUpdateScheduleItemsResponseTimeEndTimeHoursMax = 23;

export const scheduleItemControllerBulkUpdateScheduleItemsResponseTimeEndTimeMinutesMin = 0;
export const scheduleItemControllerBulkUpdateScheduleItemsResponseTimeEndTimeMinutesMax = 59;




export const ScheduleItemControllerBulkUpdateScheduleItemsResponseItem = zod.object({
  "id": zod.uuid().regex(scheduleItemControllerBulkUpdateScheduleItemsResponseIdRegExp),
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(scheduleItemControllerBulkUpdateScheduleItemsResponseStartTimeRegExp).optional().describe('Строка времени в формате [HH:mm]'),
  "endTime": zod.string().regex(scheduleItemControllerBulkUpdateScheduleItemsResponseEndTimeRegExp).optional().describe('Строка времени в формате [HH:mm]'),
  "time": zod.object({
  "startTime": zod.object({
  "hours": zod.int().min(scheduleItemControllerBulkUpdateScheduleItemsResponseTimeStartTimeHoursMin).max(scheduleItemControllerBulkUpdateScheduleItemsResponseTimeStartTimeHoursMax),
  "minutes": zod.int().min(scheduleItemControllerBulkUpdateScheduleItemsResponseTimeStartTimeMinutesMin).max(scheduleItemControllerBulkUpdateScheduleItemsResponseTimeStartTimeMinutesMax)
}).describe('Объект с данными о времени'),
  "endTime": zod.object({
  "hours": zod.int().min(scheduleItemControllerBulkUpdateScheduleItemsResponseTimeEndTimeHoursMin).max(scheduleItemControllerBulkUpdateScheduleItemsResponseTimeEndTimeHoursMax),
  "minutes": zod.int().min(scheduleItemControllerBulkUpdateScheduleItemsResponseTimeEndTimeMinutesMin).max(scheduleItemControllerBulkUpdateScheduleItemsResponseTimeEndTimeMinutesMax)
}).describe('Объект с данными о времени')
}),
  "text": zod.string().min(1)
})
export const ScheduleItemControllerBulkUpdateScheduleItemsResponse = zod.array(ScheduleItemControllerBulkUpdateScheduleItemsResponseItem)


export const ScheduleItemControllerGetScheduleItemParams = zod.object({
  "itemId": zod.string(),
  "scheduleId": zod.uuid(),
  "userId": zod.uuid()
})

export const scheduleItemControllerGetScheduleItemResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const scheduleItemControllerGetScheduleItemResponseStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleItemControllerGetScheduleItemResponseEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleItemControllerGetScheduleItemResponseTimeStartTimeHoursMin = 0;
export const scheduleItemControllerGetScheduleItemResponseTimeStartTimeHoursMax = 23;

export const scheduleItemControllerGetScheduleItemResponseTimeStartTimeMinutesMin = 0;
export const scheduleItemControllerGetScheduleItemResponseTimeStartTimeMinutesMax = 59;

export const scheduleItemControllerGetScheduleItemResponseTimeEndTimeHoursMin = 0;
export const scheduleItemControllerGetScheduleItemResponseTimeEndTimeHoursMax = 23;

export const scheduleItemControllerGetScheduleItemResponseTimeEndTimeMinutesMin = 0;
export const scheduleItemControllerGetScheduleItemResponseTimeEndTimeMinutesMax = 59;




export const ScheduleItemControllerGetScheduleItemResponse = zod.object({
  "id": zod.uuid().regex(scheduleItemControllerGetScheduleItemResponseIdRegExp),
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(scheduleItemControllerGetScheduleItemResponseStartTimeRegExp).optional().describe('Строка времени в формате [HH:mm]'),
  "endTime": zod.string().regex(scheduleItemControllerGetScheduleItemResponseEndTimeRegExp).optional().describe('Строка времени в формате [HH:mm]'),
  "time": zod.object({
  "startTime": zod.object({
  "hours": zod.int().min(scheduleItemControllerGetScheduleItemResponseTimeStartTimeHoursMin).max(scheduleItemControllerGetScheduleItemResponseTimeStartTimeHoursMax),
  "minutes": zod.int().min(scheduleItemControllerGetScheduleItemResponseTimeStartTimeMinutesMin).max(scheduleItemControllerGetScheduleItemResponseTimeStartTimeMinutesMax)
}).describe('Объект с данными о времени'),
  "endTime": zod.object({
  "hours": zod.int().min(scheduleItemControllerGetScheduleItemResponseTimeEndTimeHoursMin).max(scheduleItemControllerGetScheduleItemResponseTimeEndTimeHoursMax),
  "minutes": zod.int().min(scheduleItemControllerGetScheduleItemResponseTimeEndTimeMinutesMin).max(scheduleItemControllerGetScheduleItemResponseTimeEndTimeMinutesMax)
}).describe('Объект с данными о времени')
}),
  "text": zod.string().min(1)
})


export const ScheduleItemControllerUpdateScheduleItemParams = zod.object({
  "itemId": zod.string(),
  "scheduleId": zod.uuid(),
  "userId": zod.uuid()
})

export const scheduleItemControllerUpdateScheduleItemBodyIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const scheduleItemControllerUpdateScheduleItemBodyStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleItemControllerUpdateScheduleItemBodyEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleItemControllerUpdateScheduleItemBodyTimeStartTimeHoursMin = 0;
export const scheduleItemControllerUpdateScheduleItemBodyTimeStartTimeHoursMax = 23;

export const scheduleItemControllerUpdateScheduleItemBodyTimeStartTimeMinutesMin = 0;
export const scheduleItemControllerUpdateScheduleItemBodyTimeStartTimeMinutesMax = 59;

export const scheduleItemControllerUpdateScheduleItemBodyTimeEndTimeHoursMin = 0;
export const scheduleItemControllerUpdateScheduleItemBodyTimeEndTimeHoursMax = 23;

export const scheduleItemControllerUpdateScheduleItemBodyTimeEndTimeMinutesMin = 0;
export const scheduleItemControllerUpdateScheduleItemBodyTimeEndTimeMinutesMax = 59;




export const ScheduleItemControllerUpdateScheduleItemBody = zod.object({
  "id": zod.uuid().regex(scheduleItemControllerUpdateScheduleItemBodyIdRegExp),
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']).optional(),
  "startTime": zod.string().regex(scheduleItemControllerUpdateScheduleItemBodyStartTimeRegExp).optional().describe('Строка времени в формате [HH:mm]'),
  "endTime": zod.string().regex(scheduleItemControllerUpdateScheduleItemBodyEndTimeRegExp).optional().describe('Строка времени в формате [HH:mm]'),
  "time": zod.object({
  "startTime": zod.object({
  "hours": zod.int().min(scheduleItemControllerUpdateScheduleItemBodyTimeStartTimeHoursMin).max(scheduleItemControllerUpdateScheduleItemBodyTimeStartTimeHoursMax),
  "minutes": zod.int().min(scheduleItemControllerUpdateScheduleItemBodyTimeStartTimeMinutesMin).max(scheduleItemControllerUpdateScheduleItemBodyTimeStartTimeMinutesMax)
}).describe('Объект с данными о времени'),
  "endTime": zod.object({
  "hours": zod.int().min(scheduleItemControllerUpdateScheduleItemBodyTimeEndTimeHoursMin).max(scheduleItemControllerUpdateScheduleItemBodyTimeEndTimeHoursMax),
  "minutes": zod.int().min(scheduleItemControllerUpdateScheduleItemBodyTimeEndTimeMinutesMin).max(scheduleItemControllerUpdateScheduleItemBodyTimeEndTimeMinutesMax)
}).describe('Объект с данными о времени')
}).optional(),
  "text": zod.string().min(1).optional()
}).describe('Объект с данными для обновления части расписания')

export const scheduleItemControllerUpdateScheduleItemResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const scheduleItemControllerUpdateScheduleItemResponseStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleItemControllerUpdateScheduleItemResponseEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleItemControllerUpdateScheduleItemResponseTimeStartTimeHoursMin = 0;
export const scheduleItemControllerUpdateScheduleItemResponseTimeStartTimeHoursMax = 23;

export const scheduleItemControllerUpdateScheduleItemResponseTimeStartTimeMinutesMin = 0;
export const scheduleItemControllerUpdateScheduleItemResponseTimeStartTimeMinutesMax = 59;

export const scheduleItemControllerUpdateScheduleItemResponseTimeEndTimeHoursMin = 0;
export const scheduleItemControllerUpdateScheduleItemResponseTimeEndTimeHoursMax = 23;

export const scheduleItemControllerUpdateScheduleItemResponseTimeEndTimeMinutesMin = 0;
export const scheduleItemControllerUpdateScheduleItemResponseTimeEndTimeMinutesMax = 59;




export const ScheduleItemControllerUpdateScheduleItemResponse = zod.object({
  "id": zod.uuid().regex(scheduleItemControllerUpdateScheduleItemResponseIdRegExp),
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(scheduleItemControllerUpdateScheduleItemResponseStartTimeRegExp).optional().describe('Строка времени в формате [HH:mm]'),
  "endTime": zod.string().regex(scheduleItemControllerUpdateScheduleItemResponseEndTimeRegExp).optional().describe('Строка времени в формате [HH:mm]'),
  "time": zod.object({
  "startTime": zod.object({
  "hours": zod.int().min(scheduleItemControllerUpdateScheduleItemResponseTimeStartTimeHoursMin).max(scheduleItemControllerUpdateScheduleItemResponseTimeStartTimeHoursMax),
  "minutes": zod.int().min(scheduleItemControllerUpdateScheduleItemResponseTimeStartTimeMinutesMin).max(scheduleItemControllerUpdateScheduleItemResponseTimeStartTimeMinutesMax)
}).describe('Объект с данными о времени'),
  "endTime": zod.object({
  "hours": zod.int().min(scheduleItemControllerUpdateScheduleItemResponseTimeEndTimeHoursMin).max(scheduleItemControllerUpdateScheduleItemResponseTimeEndTimeHoursMax),
  "minutes": zod.int().min(scheduleItemControllerUpdateScheduleItemResponseTimeEndTimeMinutesMin).max(scheduleItemControllerUpdateScheduleItemResponseTimeEndTimeMinutesMax)
}).describe('Объект с данными о времени')
}),
  "text": zod.string().min(1)
})


export const ScheduleItemControllerDeleteScheduleItemParams = zod.object({
  "itemId": zod.string(),
  "scheduleId": zod.uuid(),
  "userId": zod.uuid()
})

export const ScheduleItemControllerDeleteScheduleItemResponse = zod.void()


export const WebhookControllerAvitoBody = zod.object({
  "id": zod.string(),
  "version": zod.string(),
  "timestamp": zod.number(),
  "payload": zod.object({
  "type": zod.enum(['message']),
  "value": zod.object({
  "id": zod.string(),
  "chat_id": zod.string(),
  "user_id": zod.number(),
  "author_id": zod.number(),
  "created": zod.number(),
  "chat_type": zod.enum(['u2u', 'u2i']),
  "content": zod.unknown(),
  "item_id": zod.number().optional()
})
})
}).describe('Payload, который присылает Avito в вебхуке')

export const WebhookControllerAvitoResponse = zod.void()


