/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


export const AvitoCallbackControllerGetBotSettingsQueryParams = zod.object({
  "code": zod.string()
})

export const AvitoCallbackControllerGetBotSettingsResponse = zod.void()


export const BotControllerGetUserBotsParams = zod.object({
  "userId": zod.uuid()
})

export const botControllerGetUserBotsResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const botControllerGetUserBotsResponseUserIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');


export const BotControllerGetUserBotsResponseItem = zod.object({
  "id": zod.uuid().regex(botControllerGetUserBotsResponseIdRegExp),
  "userId": zod.uuid().regex(botControllerGetUserBotsResponseUserIdRegExp)
}).describe('Объект с информацией о боте')
export const BotControllerGetUserBotsResponse = zod.array(BotControllerGetUserBotsResponseItem)


export const BotControllerGetBotParams = zod.object({
  "userId": zod.uuid(),
  "botId": zod.uuid()
})

export const botControllerGetBotResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const botControllerGetBotResponseUserIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');


export const BotControllerGetBotResponse = zod.object({
  "id": zod.uuid().regex(botControllerGetBotResponseIdRegExp),
  "userId": zod.uuid().regex(botControllerGetBotResponseUserIdRegExp)
}).describe('Объект с информацией о боте')


export const BotControllerDeleteBotParams = zod.object({
  "userId": zod.uuid(),
  "botId": zod.uuid()
})

export const BotControllerDeleteBotResponse = zod.unknown()


export const BotControllerBindScheduleParams = zod.object({
  "botId": zod.uuid(),
  "userId": zod.uuid()
})

export const botControllerBindScheduleBodyScheduleIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');


export const BotControllerBindScheduleBody = zod.object({
  "scheduleId": zod.uuid().regex(botControllerBindScheduleBodyScheduleIdRegExp)
})

export const BotControllerBindScheduleResponse = zod.void()


export const BotControllerUnbindScheduleParams = zod.object({
  "botId": zod.uuid(),
  "userId": zod.uuid()
})

export const botControllerUnbindScheduleBodyScheduleIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');


export const BotControllerUnbindScheduleBody = zod.object({
  "scheduleId": zod.uuid().regex(botControllerUnbindScheduleBodyScheduleIdRegExp)
})

export const BotControllerUnbindScheduleResponse = zod.void()


export const BotControllerGetBotSchedulesParams = zod.object({
  "botId": zod.uuid(),
  "userId": zod.uuid()
})

export const botControllerGetBotSchedulesResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');

export const botControllerGetBotSchedulesResponseItemsItemIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const botControllerGetBotSchedulesResponseItemsItemStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const botControllerGetBotSchedulesResponseItemsItemEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const botControllerGetBotSchedulesResponseItemsItemTimeStartTimeHoursMin = 0;
export const botControllerGetBotSchedulesResponseItemsItemTimeStartTimeHoursMax = 23;

export const botControllerGetBotSchedulesResponseItemsItemTimeStartTimeMinutesMin = 0;
export const botControllerGetBotSchedulesResponseItemsItemTimeStartTimeMinutesMax = 59;

export const botControllerGetBotSchedulesResponseItemsItemTimeEndTimeHoursMin = 0;
export const botControllerGetBotSchedulesResponseItemsItemTimeEndTimeHoursMax = 23;

export const botControllerGetBotSchedulesResponseItemsItemTimeEndTimeMinutesMin = 0;
export const botControllerGetBotSchedulesResponseItemsItemTimeEndTimeMinutesMax = 59;




export const BotControllerGetBotSchedulesResponseItem = zod.object({
  "id": zod.uuid().regex(botControllerGetBotSchedulesResponseIdRegExp),
  "name": zod.string().min(1),
  "items": zod.array(zod.object({
  "id": zod.uuid().regex(botControllerGetBotSchedulesResponseItemsItemIdRegExp),
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(botControllerGetBotSchedulesResponseItemsItemStartTimeRegExp).optional(),
  "endTime": zod.string().regex(botControllerGetBotSchedulesResponseItemsItemEndTimeRegExp).optional(),
  "time": zod.object({
  "startTime": zod.object({
  "hours": zod.int().min(botControllerGetBotSchedulesResponseItemsItemTimeStartTimeHoursMin).max(botControllerGetBotSchedulesResponseItemsItemTimeStartTimeHoursMax),
  "minutes": zod.int().min(botControllerGetBotSchedulesResponseItemsItemTimeStartTimeMinutesMin).max(botControllerGetBotSchedulesResponseItemsItemTimeStartTimeMinutesMax)
}),
  "endTime": zod.object({
  "hours": zod.int().min(botControllerGetBotSchedulesResponseItemsItemTimeEndTimeHoursMin).max(botControllerGetBotSchedulesResponseItemsItemTimeEndTimeHoursMax),
  "minutes": zod.int().min(botControllerGetBotSchedulesResponseItemsItemTimeEndTimeMinutesMin).max(botControllerGetBotSchedulesResponseItemsItemTimeEndTimeMinutesMax)
})
}).describe('Объект с временем начала и окончания в формате [HH, MM]'),
  "text": zod.string().min(1)
}))
})
export const BotControllerGetBotSchedulesResponse = zod.array(BotControllerGetBotSchedulesResponseItem)


export const BotControllerGetBotSettingsParams = zod.object({
  "botId": zod.uuid(),
  "userId": zod.uuid()
})

export const BotControllerGetBotSettingsResponse = zod.object({
  "answerOnFirstMessage": zod.boolean().describe('Флаг, который отвечает за необходимость ответа только на первое сообщение, отправленное пользователем в чате'),
  "chatTypes": zod.array(zod.enum(['u2i', 'u2u'])).describe('Типы чатов, на которые будет работать автоответ'),
  "isActive": zod.boolean().describe('Флаг активности бота')
}).describe('Объект с настройками бота')


export const BotControllerUpdateBotSettingsParams = zod.object({
  "botId": zod.uuid(),
  "userId": zod.uuid()
})

export const BotControllerUpdateBotSettingsBody = zod.object({
  "answerOnFirstMessage": zod.boolean().optional().describe('Флаг, который отвечает за необходимость ответа только на первое сообщение, отправленное пользователем в чате'),
  "chatTypes": zod.array(zod.enum(['u2i', 'u2u'])).optional().describe('Типы чатов, на которые будет работать автоответ'),
  "isActive": zod.boolean().optional().describe('Флаг активности бота')
}).describe('Объект с данными для обновления настроек бота')

export const BotControllerUpdateBotSettingsResponse = zod.object({
  "answerOnFirstMessage": zod.boolean().describe('Флаг, который отвечает за необходимость ответа только на первое сообщение, отправленное пользователем в чате'),
  "chatTypes": zod.array(zod.enum(['u2i', 'u2u'])).describe('Типы чатов, на которые будет работать автоответ'),
  "isActive": zod.boolean().describe('Флаг активности бота')
}).describe('Объект с настройками бота')


export const ScheduleControllerCreateScheduleParams = zod.object({
  "userId": zod.uuid()
})


export const scheduleControllerCreateScheduleBodyItemsItemStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleControllerCreateScheduleBodyItemsItemEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleControllerCreateScheduleBodyItemsItemTimeStartTimeHoursMin = 0;
export const scheduleControllerCreateScheduleBodyItemsItemTimeStartTimeHoursMax = 23;

export const scheduleControllerCreateScheduleBodyItemsItemTimeStartTimeMinutesMin = 0;
export const scheduleControllerCreateScheduleBodyItemsItemTimeStartTimeMinutesMax = 59;

export const scheduleControllerCreateScheduleBodyItemsItemTimeEndTimeHoursMin = 0;
export const scheduleControllerCreateScheduleBodyItemsItemTimeEndTimeHoursMax = 23;

export const scheduleControllerCreateScheduleBodyItemsItemTimeEndTimeMinutesMin = 0;
export const scheduleControllerCreateScheduleBodyItemsItemTimeEndTimeMinutesMax = 59;




export const ScheduleControllerCreateScheduleBody = zod.object({
  "name": zod.string().min(1),
  "items": zod.array(zod.object({
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(scheduleControllerCreateScheduleBodyItemsItemStartTimeRegExp).optional(),
  "endTime": zod.string().regex(scheduleControllerCreateScheduleBodyItemsItemEndTimeRegExp).optional(),
  "time": zod.object({
  "startTime": zod.object({
  "hours": zod.int().min(scheduleControllerCreateScheduleBodyItemsItemTimeStartTimeHoursMin).max(scheduleControllerCreateScheduleBodyItemsItemTimeStartTimeHoursMax),
  "minutes": zod.int().min(scheduleControllerCreateScheduleBodyItemsItemTimeStartTimeMinutesMin).max(scheduleControllerCreateScheduleBodyItemsItemTimeStartTimeMinutesMax)
}),
  "endTime": zod.object({
  "hours": zod.int().min(scheduleControllerCreateScheduleBodyItemsItemTimeEndTimeHoursMin).max(scheduleControllerCreateScheduleBodyItemsItemTimeEndTimeHoursMax),
  "minutes": zod.int().min(scheduleControllerCreateScheduleBodyItemsItemTimeEndTimeMinutesMin).max(scheduleControllerCreateScheduleBodyItemsItemTimeEndTimeMinutesMax)
})
}).describe('Объект с временем начала и окончания в формате [HH, MM]'),
  "text": zod.string().min(1)
})).optional()
})

export const scheduleControllerCreateScheduleResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');



export const ScheduleControllerCreateScheduleResponse = zod.object({
  "id": zod.uuid().regex(scheduleControllerCreateScheduleResponseIdRegExp),
  "name": zod.string().min(1)
})


export const ScheduleControllerUserScheduleListParams = zod.object({
  "userId": zod.uuid()
})

export const scheduleControllerUserScheduleListResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');

export const scheduleControllerUserScheduleListResponseItemsItemIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const scheduleControllerUserScheduleListResponseItemsItemStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleControllerUserScheduleListResponseItemsItemEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleControllerUserScheduleListResponseItemsItemTimeStartTimeHoursMin = 0;
export const scheduleControllerUserScheduleListResponseItemsItemTimeStartTimeHoursMax = 23;

export const scheduleControllerUserScheduleListResponseItemsItemTimeStartTimeMinutesMin = 0;
export const scheduleControllerUserScheduleListResponseItemsItemTimeStartTimeMinutesMax = 59;

export const scheduleControllerUserScheduleListResponseItemsItemTimeEndTimeHoursMin = 0;
export const scheduleControllerUserScheduleListResponseItemsItemTimeEndTimeHoursMax = 23;

export const scheduleControllerUserScheduleListResponseItemsItemTimeEndTimeMinutesMin = 0;
export const scheduleControllerUserScheduleListResponseItemsItemTimeEndTimeMinutesMax = 59;




export const ScheduleControllerUserScheduleListResponseItem = zod.object({
  "id": zod.uuid().regex(scheduleControllerUserScheduleListResponseIdRegExp),
  "name": zod.string().min(1),
  "items": zod.array(zod.object({
  "id": zod.uuid().regex(scheduleControllerUserScheduleListResponseItemsItemIdRegExp),
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(scheduleControllerUserScheduleListResponseItemsItemStartTimeRegExp).optional(),
  "endTime": zod.string().regex(scheduleControllerUserScheduleListResponseItemsItemEndTimeRegExp).optional(),
  "time": zod.object({
  "startTime": zod.object({
  "hours": zod.int().min(scheduleControllerUserScheduleListResponseItemsItemTimeStartTimeHoursMin).max(scheduleControllerUserScheduleListResponseItemsItemTimeStartTimeHoursMax),
  "minutes": zod.int().min(scheduleControllerUserScheduleListResponseItemsItemTimeStartTimeMinutesMin).max(scheduleControllerUserScheduleListResponseItemsItemTimeStartTimeMinutesMax)
}),
  "endTime": zod.object({
  "hours": zod.int().min(scheduleControllerUserScheduleListResponseItemsItemTimeEndTimeHoursMin).max(scheduleControllerUserScheduleListResponseItemsItemTimeEndTimeHoursMax),
  "minutes": zod.int().min(scheduleControllerUserScheduleListResponseItemsItemTimeEndTimeMinutesMin).max(scheduleControllerUserScheduleListResponseItemsItemTimeEndTimeMinutesMax)
})
}).describe('Объект с временем начала и окончания в формате [HH, MM]'),
  "text": zod.string().min(1)
}))
})
export const ScheduleControllerUserScheduleListResponse = zod.array(ScheduleControllerUserScheduleListResponseItem)


export const ScheduleControllerGetScheduleParams = zod.object({
  "scheduleId": zod.string(),
  "userId": zod.uuid()
})

export const scheduleControllerGetScheduleResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');

export const scheduleControllerGetScheduleResponseItemsItemIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const scheduleControllerGetScheduleResponseItemsItemStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleControllerGetScheduleResponseItemsItemEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleControllerGetScheduleResponseItemsItemTimeStartTimeHoursMin = 0;
export const scheduleControllerGetScheduleResponseItemsItemTimeStartTimeHoursMax = 23;

export const scheduleControllerGetScheduleResponseItemsItemTimeStartTimeMinutesMin = 0;
export const scheduleControllerGetScheduleResponseItemsItemTimeStartTimeMinutesMax = 59;

export const scheduleControllerGetScheduleResponseItemsItemTimeEndTimeHoursMin = 0;
export const scheduleControllerGetScheduleResponseItemsItemTimeEndTimeHoursMax = 23;

export const scheduleControllerGetScheduleResponseItemsItemTimeEndTimeMinutesMin = 0;
export const scheduleControllerGetScheduleResponseItemsItemTimeEndTimeMinutesMax = 59;




export const ScheduleControllerGetScheduleResponse = zod.object({
  "id": zod.uuid().regex(scheduleControllerGetScheduleResponseIdRegExp),
  "name": zod.string().min(1),
  "items": zod.array(zod.object({
  "id": zod.uuid().regex(scheduleControllerGetScheduleResponseItemsItemIdRegExp),
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(scheduleControllerGetScheduleResponseItemsItemStartTimeRegExp).optional(),
  "endTime": zod.string().regex(scheduleControllerGetScheduleResponseItemsItemEndTimeRegExp).optional(),
  "time": zod.object({
  "startTime": zod.object({
  "hours": zod.int().min(scheduleControllerGetScheduleResponseItemsItemTimeStartTimeHoursMin).max(scheduleControllerGetScheduleResponseItemsItemTimeStartTimeHoursMax),
  "minutes": zod.int().min(scheduleControllerGetScheduleResponseItemsItemTimeStartTimeMinutesMin).max(scheduleControllerGetScheduleResponseItemsItemTimeStartTimeMinutesMax)
}),
  "endTime": zod.object({
  "hours": zod.int().min(scheduleControllerGetScheduleResponseItemsItemTimeEndTimeHoursMin).max(scheduleControllerGetScheduleResponseItemsItemTimeEndTimeHoursMax),
  "minutes": zod.int().min(scheduleControllerGetScheduleResponseItemsItemTimeEndTimeMinutesMin).max(scheduleControllerGetScheduleResponseItemsItemTimeEndTimeMinutesMax)
})
}).describe('Объект с временем начала и окончания в формате [HH, MM]'),
  "text": zod.string().min(1)
}))
})


export const ScheduleControllerUpdateScheduleParams = zod.object({
  "scheduleId": zod.string(),
  "userId": zod.uuid()
})


export const scheduleControllerUpdateScheduleBodyItemsItemStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleControllerUpdateScheduleBodyItemsItemEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleControllerUpdateScheduleBodyItemsItemTimeStartTimeHoursMin = 0;
export const scheduleControllerUpdateScheduleBodyItemsItemTimeStartTimeHoursMax = 23;

export const scheduleControllerUpdateScheduleBodyItemsItemTimeStartTimeMinutesMin = 0;
export const scheduleControllerUpdateScheduleBodyItemsItemTimeStartTimeMinutesMax = 59;

export const scheduleControllerUpdateScheduleBodyItemsItemTimeEndTimeHoursMin = 0;
export const scheduleControllerUpdateScheduleBodyItemsItemTimeEndTimeHoursMax = 23;

export const scheduleControllerUpdateScheduleBodyItemsItemTimeEndTimeMinutesMin = 0;
export const scheduleControllerUpdateScheduleBodyItemsItemTimeEndTimeMinutesMax = 59;




export const ScheduleControllerUpdateScheduleBody = zod.object({
  "name": zod.string().min(1).optional(),
  "items": zod.array(zod.object({
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(scheduleControllerUpdateScheduleBodyItemsItemStartTimeRegExp).optional(),
  "endTime": zod.string().regex(scheduleControllerUpdateScheduleBodyItemsItemEndTimeRegExp).optional(),
  "time": zod.object({
  "startTime": zod.object({
  "hours": zod.int().min(scheduleControllerUpdateScheduleBodyItemsItemTimeStartTimeHoursMin).max(scheduleControllerUpdateScheduleBodyItemsItemTimeStartTimeHoursMax),
  "minutes": zod.int().min(scheduleControllerUpdateScheduleBodyItemsItemTimeStartTimeMinutesMin).max(scheduleControllerUpdateScheduleBodyItemsItemTimeStartTimeMinutesMax)
}),
  "endTime": zod.object({
  "hours": zod.int().min(scheduleControllerUpdateScheduleBodyItemsItemTimeEndTimeHoursMin).max(scheduleControllerUpdateScheduleBodyItemsItemTimeEndTimeHoursMax),
  "minutes": zod.int().min(scheduleControllerUpdateScheduleBodyItemsItemTimeEndTimeMinutesMin).max(scheduleControllerUpdateScheduleBodyItemsItemTimeEndTimeMinutesMax)
})
}).describe('Объект с временем начала и окончания в формате [HH, MM]'),
  "text": zod.string().min(1)
})).optional()
})

export const scheduleControllerUpdateScheduleResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');

export const scheduleControllerUpdateScheduleResponseItemsItemIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const scheduleControllerUpdateScheduleResponseItemsItemStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleControllerUpdateScheduleResponseItemsItemEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleControllerUpdateScheduleResponseItemsItemTimeStartTimeHoursMin = 0;
export const scheduleControllerUpdateScheduleResponseItemsItemTimeStartTimeHoursMax = 23;

export const scheduleControllerUpdateScheduleResponseItemsItemTimeStartTimeMinutesMin = 0;
export const scheduleControllerUpdateScheduleResponseItemsItemTimeStartTimeMinutesMax = 59;

export const scheduleControllerUpdateScheduleResponseItemsItemTimeEndTimeHoursMin = 0;
export const scheduleControllerUpdateScheduleResponseItemsItemTimeEndTimeHoursMax = 23;

export const scheduleControllerUpdateScheduleResponseItemsItemTimeEndTimeMinutesMin = 0;
export const scheduleControllerUpdateScheduleResponseItemsItemTimeEndTimeMinutesMax = 59;




export const ScheduleControllerUpdateScheduleResponse = zod.object({
  "id": zod.uuid().regex(scheduleControllerUpdateScheduleResponseIdRegExp),
  "name": zod.string().min(1),
  "items": zod.array(zod.object({
  "id": zod.uuid().regex(scheduleControllerUpdateScheduleResponseItemsItemIdRegExp),
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(scheduleControllerUpdateScheduleResponseItemsItemStartTimeRegExp).optional(),
  "endTime": zod.string().regex(scheduleControllerUpdateScheduleResponseItemsItemEndTimeRegExp).optional(),
  "time": zod.object({
  "startTime": zod.object({
  "hours": zod.int().min(scheduleControllerUpdateScheduleResponseItemsItemTimeStartTimeHoursMin).max(scheduleControllerUpdateScheduleResponseItemsItemTimeStartTimeHoursMax),
  "minutes": zod.int().min(scheduleControllerUpdateScheduleResponseItemsItemTimeStartTimeMinutesMin).max(scheduleControllerUpdateScheduleResponseItemsItemTimeStartTimeMinutesMax)
}),
  "endTime": zod.object({
  "hours": zod.int().min(scheduleControllerUpdateScheduleResponseItemsItemTimeEndTimeHoursMin).max(scheduleControllerUpdateScheduleResponseItemsItemTimeEndTimeHoursMax),
  "minutes": zod.int().min(scheduleControllerUpdateScheduleResponseItemsItemTimeEndTimeMinutesMin).max(scheduleControllerUpdateScheduleResponseItemsItemTimeEndTimeMinutesMax)
})
}).describe('Объект с временем начала и окончания в формате [HH, MM]'),
  "text": zod.string().min(1)
}))
})


export const ScheduleControllerDeleteScheduleParams = zod.object({
  "scheduleId": zod.string(),
  "userId": zod.uuid()
})

export const ScheduleControllerDeleteScheduleResponse = zod.void()


export const ScheduleItemControllerCreateScheduleItemParams = zod.object({
  "scheduleId": zod.uuid(),
  "userId": zod.uuid()
})

export const scheduleItemControllerCreateScheduleItemBodyStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleItemControllerCreateScheduleItemBodyEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleItemControllerCreateScheduleItemBodyTimeStartTimeHoursMin = 0;
export const scheduleItemControllerCreateScheduleItemBodyTimeStartTimeHoursMax = 23;

export const scheduleItemControllerCreateScheduleItemBodyTimeStartTimeMinutesMin = 0;
export const scheduleItemControllerCreateScheduleItemBodyTimeStartTimeMinutesMax = 59;

export const scheduleItemControllerCreateScheduleItemBodyTimeEndTimeHoursMin = 0;
export const scheduleItemControllerCreateScheduleItemBodyTimeEndTimeHoursMax = 23;

export const scheduleItemControllerCreateScheduleItemBodyTimeEndTimeMinutesMin = 0;
export const scheduleItemControllerCreateScheduleItemBodyTimeEndTimeMinutesMax = 59;




export const ScheduleItemControllerCreateScheduleItemBody = zod.object({
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(scheduleItemControllerCreateScheduleItemBodyStartTimeRegExp).optional(),
  "endTime": zod.string().regex(scheduleItemControllerCreateScheduleItemBodyEndTimeRegExp).optional(),
  "time": zod.object({
  "startTime": zod.object({
  "hours": zod.int().min(scheduleItemControllerCreateScheduleItemBodyTimeStartTimeHoursMin).max(scheduleItemControllerCreateScheduleItemBodyTimeStartTimeHoursMax),
  "minutes": zod.int().min(scheduleItemControllerCreateScheduleItemBodyTimeStartTimeMinutesMin).max(scheduleItemControllerCreateScheduleItemBodyTimeStartTimeMinutesMax)
}),
  "endTime": zod.object({
  "hours": zod.int().min(scheduleItemControllerCreateScheduleItemBodyTimeEndTimeHoursMin).max(scheduleItemControllerCreateScheduleItemBodyTimeEndTimeHoursMax),
  "minutes": zod.int().min(scheduleItemControllerCreateScheduleItemBodyTimeEndTimeMinutesMin).max(scheduleItemControllerCreateScheduleItemBodyTimeEndTimeMinutesMax)
})
}).describe('Объект с временем начала и окончания в формате [HH, MM]'),
  "text": zod.string().min(1)
})

export const scheduleItemControllerCreateScheduleItemResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const scheduleItemControllerCreateScheduleItemResponseStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleItemControllerCreateScheduleItemResponseEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleItemControllerCreateScheduleItemResponseTimeStartTimeHoursMin = 0;
export const scheduleItemControllerCreateScheduleItemResponseTimeStartTimeHoursMax = 23;

export const scheduleItemControllerCreateScheduleItemResponseTimeStartTimeMinutesMin = 0;
export const scheduleItemControllerCreateScheduleItemResponseTimeStartTimeMinutesMax = 59;

export const scheduleItemControllerCreateScheduleItemResponseTimeEndTimeHoursMin = 0;
export const scheduleItemControllerCreateScheduleItemResponseTimeEndTimeHoursMax = 23;

export const scheduleItemControllerCreateScheduleItemResponseTimeEndTimeMinutesMin = 0;
export const scheduleItemControllerCreateScheduleItemResponseTimeEndTimeMinutesMax = 59;




export const ScheduleItemControllerCreateScheduleItemResponse = zod.object({
  "id": zod.uuid().regex(scheduleItemControllerCreateScheduleItemResponseIdRegExp),
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(scheduleItemControllerCreateScheduleItemResponseStartTimeRegExp).optional(),
  "endTime": zod.string().regex(scheduleItemControllerCreateScheduleItemResponseEndTimeRegExp).optional(),
  "time": zod.object({
  "startTime": zod.object({
  "hours": zod.int().min(scheduleItemControllerCreateScheduleItemResponseTimeStartTimeHoursMin).max(scheduleItemControllerCreateScheduleItemResponseTimeStartTimeHoursMax),
  "minutes": zod.int().min(scheduleItemControllerCreateScheduleItemResponseTimeStartTimeMinutesMin).max(scheduleItemControllerCreateScheduleItemResponseTimeStartTimeMinutesMax)
}),
  "endTime": zod.object({
  "hours": zod.int().min(scheduleItemControllerCreateScheduleItemResponseTimeEndTimeHoursMin).max(scheduleItemControllerCreateScheduleItemResponseTimeEndTimeHoursMax),
  "minutes": zod.int().min(scheduleItemControllerCreateScheduleItemResponseTimeEndTimeMinutesMin).max(scheduleItemControllerCreateScheduleItemResponseTimeEndTimeMinutesMax)
})
}).describe('Объект с временем начала и окончания в формате [HH, MM]'),
  "text": zod.string().min(1)
})


export const ScheduleItemControllerGetScheduleItemsParams = zod.object({
  "scheduleId": zod.uuid(),
  "userId": zod.uuid()
})

export const scheduleItemControllerGetScheduleItemsResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const scheduleItemControllerGetScheduleItemsResponseStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleItemControllerGetScheduleItemsResponseEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleItemControllerGetScheduleItemsResponseTimeStartTimeHoursMin = 0;
export const scheduleItemControllerGetScheduleItemsResponseTimeStartTimeHoursMax = 23;

export const scheduleItemControllerGetScheduleItemsResponseTimeStartTimeMinutesMin = 0;
export const scheduleItemControllerGetScheduleItemsResponseTimeStartTimeMinutesMax = 59;

export const scheduleItemControllerGetScheduleItemsResponseTimeEndTimeHoursMin = 0;
export const scheduleItemControllerGetScheduleItemsResponseTimeEndTimeHoursMax = 23;

export const scheduleItemControllerGetScheduleItemsResponseTimeEndTimeMinutesMin = 0;
export const scheduleItemControllerGetScheduleItemsResponseTimeEndTimeMinutesMax = 59;




export const ScheduleItemControllerGetScheduleItemsResponseItem = zod.object({
  "id": zod.uuid().regex(scheduleItemControllerGetScheduleItemsResponseIdRegExp),
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(scheduleItemControllerGetScheduleItemsResponseStartTimeRegExp).optional(),
  "endTime": zod.string().regex(scheduleItemControllerGetScheduleItemsResponseEndTimeRegExp).optional(),
  "time": zod.object({
  "startTime": zod.object({
  "hours": zod.int().min(scheduleItemControllerGetScheduleItemsResponseTimeStartTimeHoursMin).max(scheduleItemControllerGetScheduleItemsResponseTimeStartTimeHoursMax),
  "minutes": zod.int().min(scheduleItemControllerGetScheduleItemsResponseTimeStartTimeMinutesMin).max(scheduleItemControllerGetScheduleItemsResponseTimeStartTimeMinutesMax)
}),
  "endTime": zod.object({
  "hours": zod.int().min(scheduleItemControllerGetScheduleItemsResponseTimeEndTimeHoursMin).max(scheduleItemControllerGetScheduleItemsResponseTimeEndTimeHoursMax),
  "minutes": zod.int().min(scheduleItemControllerGetScheduleItemsResponseTimeEndTimeMinutesMin).max(scheduleItemControllerGetScheduleItemsResponseTimeEndTimeMinutesMax)
})
}).describe('Объект с временем начала и окончания в формате [HH, MM]'),
  "text": zod.string().min(1)
})
export const ScheduleItemControllerGetScheduleItemsResponse = zod.array(ScheduleItemControllerGetScheduleItemsResponseItem)


export const ScheduleItemControllerGetScheduleItemParams = zod.object({
  "itemId": zod.string(),
  "scheduleId": zod.uuid(),
  "userId": zod.uuid()
})

export const scheduleItemControllerGetScheduleItemResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const scheduleItemControllerGetScheduleItemResponseStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleItemControllerGetScheduleItemResponseEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleItemControllerGetScheduleItemResponseTimeStartTimeHoursMin = 0;
export const scheduleItemControllerGetScheduleItemResponseTimeStartTimeHoursMax = 23;

export const scheduleItemControllerGetScheduleItemResponseTimeStartTimeMinutesMin = 0;
export const scheduleItemControllerGetScheduleItemResponseTimeStartTimeMinutesMax = 59;

export const scheduleItemControllerGetScheduleItemResponseTimeEndTimeHoursMin = 0;
export const scheduleItemControllerGetScheduleItemResponseTimeEndTimeHoursMax = 23;

export const scheduleItemControllerGetScheduleItemResponseTimeEndTimeMinutesMin = 0;
export const scheduleItemControllerGetScheduleItemResponseTimeEndTimeMinutesMax = 59;




export const ScheduleItemControllerGetScheduleItemResponse = zod.object({
  "id": zod.uuid().regex(scheduleItemControllerGetScheduleItemResponseIdRegExp),
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(scheduleItemControllerGetScheduleItemResponseStartTimeRegExp).optional(),
  "endTime": zod.string().regex(scheduleItemControllerGetScheduleItemResponseEndTimeRegExp).optional(),
  "time": zod.object({
  "startTime": zod.object({
  "hours": zod.int().min(scheduleItemControllerGetScheduleItemResponseTimeStartTimeHoursMin).max(scheduleItemControllerGetScheduleItemResponseTimeStartTimeHoursMax),
  "minutes": zod.int().min(scheduleItemControllerGetScheduleItemResponseTimeStartTimeMinutesMin).max(scheduleItemControllerGetScheduleItemResponseTimeStartTimeMinutesMax)
}),
  "endTime": zod.object({
  "hours": zod.int().min(scheduleItemControllerGetScheduleItemResponseTimeEndTimeHoursMin).max(scheduleItemControllerGetScheduleItemResponseTimeEndTimeHoursMax),
  "minutes": zod.int().min(scheduleItemControllerGetScheduleItemResponseTimeEndTimeMinutesMin).max(scheduleItemControllerGetScheduleItemResponseTimeEndTimeMinutesMax)
})
}).describe('Объект с временем начала и окончания в формате [HH, MM]'),
  "text": zod.string().min(1)
})


export const ScheduleItemControllerUpdateScheduleItemParams = zod.object({
  "itemId": zod.string(),
  "scheduleId": zod.uuid(),
  "userId": zod.uuid()
})

export const scheduleItemControllerUpdateScheduleItemBodyStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleItemControllerUpdateScheduleItemBodyEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleItemControllerUpdateScheduleItemBodyTimeStartTimeHoursMin = 0;
export const scheduleItemControllerUpdateScheduleItemBodyTimeStartTimeHoursMax = 23;

export const scheduleItemControllerUpdateScheduleItemBodyTimeStartTimeMinutesMin = 0;
export const scheduleItemControllerUpdateScheduleItemBodyTimeStartTimeMinutesMax = 59;

export const scheduleItemControllerUpdateScheduleItemBodyTimeEndTimeHoursMin = 0;
export const scheduleItemControllerUpdateScheduleItemBodyTimeEndTimeHoursMax = 23;

export const scheduleItemControllerUpdateScheduleItemBodyTimeEndTimeMinutesMin = 0;
export const scheduleItemControllerUpdateScheduleItemBodyTimeEndTimeMinutesMax = 59;




export const ScheduleItemControllerUpdateScheduleItemBody = zod.object({
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']).optional(),
  "startTime": zod.string().regex(scheduleItemControllerUpdateScheduleItemBodyStartTimeRegExp).optional(),
  "endTime": zod.string().regex(scheduleItemControllerUpdateScheduleItemBodyEndTimeRegExp).optional(),
  "time": zod.object({
  "startTime": zod.object({
  "hours": zod.int().min(scheduleItemControllerUpdateScheduleItemBodyTimeStartTimeHoursMin).max(scheduleItemControllerUpdateScheduleItemBodyTimeStartTimeHoursMax),
  "minutes": zod.int().min(scheduleItemControllerUpdateScheduleItemBodyTimeStartTimeMinutesMin).max(scheduleItemControllerUpdateScheduleItemBodyTimeStartTimeMinutesMax)
}),
  "endTime": zod.object({
  "hours": zod.int().min(scheduleItemControllerUpdateScheduleItemBodyTimeEndTimeHoursMin).max(scheduleItemControllerUpdateScheduleItemBodyTimeEndTimeHoursMax),
  "minutes": zod.int().min(scheduleItemControllerUpdateScheduleItemBodyTimeEndTimeMinutesMin).max(scheduleItemControllerUpdateScheduleItemBodyTimeEndTimeMinutesMax)
})
}).optional().describe('Объект с временем начала и окончания в формате [HH, MM]'),
  "text": zod.string().min(1).optional()
})

export const scheduleItemControllerUpdateScheduleItemResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const scheduleItemControllerUpdateScheduleItemResponseStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleItemControllerUpdateScheduleItemResponseEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleItemControllerUpdateScheduleItemResponseTimeStartTimeHoursMin = 0;
export const scheduleItemControllerUpdateScheduleItemResponseTimeStartTimeHoursMax = 23;

export const scheduleItemControllerUpdateScheduleItemResponseTimeStartTimeMinutesMin = 0;
export const scheduleItemControllerUpdateScheduleItemResponseTimeStartTimeMinutesMax = 59;

export const scheduleItemControllerUpdateScheduleItemResponseTimeEndTimeHoursMin = 0;
export const scheduleItemControllerUpdateScheduleItemResponseTimeEndTimeHoursMax = 23;

export const scheduleItemControllerUpdateScheduleItemResponseTimeEndTimeMinutesMin = 0;
export const scheduleItemControllerUpdateScheduleItemResponseTimeEndTimeMinutesMax = 59;




export const ScheduleItemControllerUpdateScheduleItemResponse = zod.object({
  "id": zod.uuid().regex(scheduleItemControllerUpdateScheduleItemResponseIdRegExp),
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(scheduleItemControllerUpdateScheduleItemResponseStartTimeRegExp).optional(),
  "endTime": zod.string().regex(scheduleItemControllerUpdateScheduleItemResponseEndTimeRegExp).optional(),
  "time": zod.object({
  "startTime": zod.object({
  "hours": zod.int().min(scheduleItemControllerUpdateScheduleItemResponseTimeStartTimeHoursMin).max(scheduleItemControllerUpdateScheduleItemResponseTimeStartTimeHoursMax),
  "minutes": zod.int().min(scheduleItemControllerUpdateScheduleItemResponseTimeStartTimeMinutesMin).max(scheduleItemControllerUpdateScheduleItemResponseTimeStartTimeMinutesMax)
}),
  "endTime": zod.object({
  "hours": zod.int().min(scheduleItemControllerUpdateScheduleItemResponseTimeEndTimeHoursMin).max(scheduleItemControllerUpdateScheduleItemResponseTimeEndTimeHoursMax),
  "minutes": zod.int().min(scheduleItemControllerUpdateScheduleItemResponseTimeEndTimeMinutesMin).max(scheduleItemControllerUpdateScheduleItemResponseTimeEndTimeMinutesMax)
})
}).describe('Объект с временем начала и окончания в формате [HH, MM]'),
  "text": zod.string().min(1)
})


export const ScheduleItemControllerDeleteScheduleItemParams = zod.object({
  "itemId": zod.string(),
  "scheduleId": zod.uuid(),
  "userId": zod.uuid()
})

export const ScheduleItemControllerDeleteScheduleItemResponse = zod.void()


export const WebhookControllerAvitoBody = zod.object({
  "id": zod.string(),
  "version": zod.string(),
  "timestamp": zod.number(),
  "payload": zod.object({
  "type": zod.enum(['message']),
  "value": zod.object({
  "id": zod.string(),
  "chat_id": zod.string(),
  "user_id": zod.number(),
  "author_id": zod.number(),
  "created": zod.number(),
  "chat_type": zod.enum(['u2u', 'u2i']),
  "content": zod.unknown(),
  "item_id": zod.number().optional()
})
})
}).describe('Payload, который присылает Avito в вебхуке')

export const WebhookControllerAvitoResponse = zod.void()


