/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


export const ScheduleItemControllerCreateScheduleItemParams = zod.object({
  "scheduleId": zod.uuid(),
  "userId": zod.uuid()
})

export const scheduleItemControllerCreateScheduleItemBodyStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleItemControllerCreateScheduleItemBodyEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');



export const ScheduleItemControllerCreateScheduleItemBody = zod.object({
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(scheduleItemControllerCreateScheduleItemBodyStartTimeRegExp).optional(),
  "endTime": zod.string().regex(scheduleItemControllerCreateScheduleItemBodyEndTimeRegExp).optional(),
  "time": zod.object({
  "startTime": zod.tuple([zod.int().min(scheduleItemControllerCreateScheduleItemBodyTimeStartTime0ItemMin).max(scheduleItemControllerCreateScheduleItemBodyTimeStartTime0ItemMax),
zod.int().min(scheduleItemControllerCreateScheduleItemBodyTimeStartTime1ItemMin).max(scheduleItemControllerCreateScheduleItemBodyTimeStartTime1ItemMax)]),
  "endTime": zod.tuple([zod.number().min(scheduleItemControllerCreateScheduleItemBodyTimeEndTime0ItemMin).max(scheduleItemControllerCreateScheduleItemBodyTimeEndTime0ItemMax),
zod.number().min(scheduleItemControllerCreateScheduleItemBodyTimeEndTime1ItemMin).max(scheduleItemControllerCreateScheduleItemBodyTimeEndTime1ItemMax)])
}).describe('Объект с временем начала и окончания в формате [HH, MM]'),
  "text": zod.string().min(1)
})

export const scheduleItemControllerCreateScheduleItemResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const scheduleItemControllerCreateScheduleItemResponseStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleItemControllerCreateScheduleItemResponseEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');



export const ScheduleItemControllerCreateScheduleItemResponse = zod.object({
  "id": zod.uuid().regex(scheduleItemControllerCreateScheduleItemResponseIdRegExp),
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(scheduleItemControllerCreateScheduleItemResponseStartTimeRegExp).optional(),
  "endTime": zod.string().regex(scheduleItemControllerCreateScheduleItemResponseEndTimeRegExp).optional(),
  "time": zod.object({
  "startTime": zod.tuple([zod.int().min(scheduleItemControllerCreateScheduleItemResponseTimeStartTime0ItemMin).max(scheduleItemControllerCreateScheduleItemResponseTimeStartTime0ItemMax),
zod.int().min(scheduleItemControllerCreateScheduleItemResponseTimeStartTime1ItemMin).max(scheduleItemControllerCreateScheduleItemResponseTimeStartTime1ItemMax)]),
  "endTime": zod.tuple([zod.number().min(scheduleItemControllerCreateScheduleItemResponseTimeEndTime0ItemMin).max(scheduleItemControllerCreateScheduleItemResponseTimeEndTime0ItemMax),
zod.number().min(scheduleItemControllerCreateScheduleItemResponseTimeEndTime1ItemMin).max(scheduleItemControllerCreateScheduleItemResponseTimeEndTime1ItemMax)])
}).describe('Объект с временем начала и окончания в формате [HH, MM]'),
  "text": zod.string().min(1)
})

export const ScheduleItemControllerGetScheduleItemsParams = zod.object({
  "scheduleId": zod.uuid(),
  "userId": zod.uuid()
})

export const scheduleItemControllerGetScheduleItemsResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const scheduleItemControllerGetScheduleItemsResponseStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleItemControllerGetScheduleItemsResponseEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');



export const ScheduleItemControllerGetScheduleItemsResponseItem = zod.object({
  "id": zod.uuid().regex(scheduleItemControllerGetScheduleItemsResponseIdRegExp),
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(scheduleItemControllerGetScheduleItemsResponseStartTimeRegExp).optional(),
  "endTime": zod.string().regex(scheduleItemControllerGetScheduleItemsResponseEndTimeRegExp).optional(),
  "time": zod.object({
  "startTime": zod.tuple([zod.int().min(scheduleItemControllerGetScheduleItemsResponseTimeStartTime0ItemMin).max(scheduleItemControllerGetScheduleItemsResponseTimeStartTime0ItemMax),
zod.int().min(scheduleItemControllerGetScheduleItemsResponseTimeStartTime1ItemMin).max(scheduleItemControllerGetScheduleItemsResponseTimeStartTime1ItemMax)]),
  "endTime": zod.tuple([zod.number().min(scheduleItemControllerGetScheduleItemsResponseTimeEndTime0ItemMin).max(scheduleItemControllerGetScheduleItemsResponseTimeEndTime0ItemMax),
zod.number().min(scheduleItemControllerGetScheduleItemsResponseTimeEndTime1ItemMin).max(scheduleItemControllerGetScheduleItemsResponseTimeEndTime1ItemMax)])
}).describe('Объект с временем начала и окончания в формате [HH, MM]'),
  "text": zod.string().min(1)
})
export const ScheduleItemControllerGetScheduleItemsResponse = zod.array(ScheduleItemControllerGetScheduleItemsResponseItem)

export const ScheduleItemControllerGetScheduleItemParams = zod.object({
  "itemId": zod.string(),
  "scheduleId": zod.uuid(),
  "userId": zod.uuid()
})

export const scheduleItemControllerGetScheduleItemResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const scheduleItemControllerGetScheduleItemResponseStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleItemControllerGetScheduleItemResponseEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');



export const ScheduleItemControllerGetScheduleItemResponse = zod.object({
  "id": zod.uuid().regex(scheduleItemControllerGetScheduleItemResponseIdRegExp),
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(scheduleItemControllerGetScheduleItemResponseStartTimeRegExp).optional(),
  "endTime": zod.string().regex(scheduleItemControllerGetScheduleItemResponseEndTimeRegExp).optional(),
  "time": zod.object({
  "startTime": zod.tuple([zod.int().min(scheduleItemControllerGetScheduleItemResponseTimeStartTime0ItemMin).max(scheduleItemControllerGetScheduleItemResponseTimeStartTime0ItemMax),
zod.int().min(scheduleItemControllerGetScheduleItemResponseTimeStartTime1ItemMin).max(scheduleItemControllerGetScheduleItemResponseTimeStartTime1ItemMax)]),
  "endTime": zod.tuple([zod.number().min(scheduleItemControllerGetScheduleItemResponseTimeEndTime0ItemMin).max(scheduleItemControllerGetScheduleItemResponseTimeEndTime0ItemMax),
zod.number().min(scheduleItemControllerGetScheduleItemResponseTimeEndTime1ItemMin).max(scheduleItemControllerGetScheduleItemResponseTimeEndTime1ItemMax)])
}).describe('Объект с временем начала и окончания в формате [HH, MM]'),
  "text": zod.string().min(1)
})

export const ScheduleItemControllerUpdateScheduleItemParams = zod.object({
  "itemId": zod.string(),
  "scheduleId": zod.uuid(),
  "userId": zod.uuid()
})

export const scheduleItemControllerUpdateScheduleItemBodyStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleItemControllerUpdateScheduleItemBodyEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');



export const ScheduleItemControllerUpdateScheduleItemBody = zod.object({
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']).optional(),
  "startTime": zod.string().regex(scheduleItemControllerUpdateScheduleItemBodyStartTimeRegExp).optional(),
  "endTime": zod.string().regex(scheduleItemControllerUpdateScheduleItemBodyEndTimeRegExp).optional(),
  "time": zod.object({
  "startTime": zod.tuple([zod.int().min(scheduleItemControllerUpdateScheduleItemBodyTimeStartTime0ItemMin).max(scheduleItemControllerUpdateScheduleItemBodyTimeStartTime0ItemMax),
zod.int().min(scheduleItemControllerUpdateScheduleItemBodyTimeStartTime1ItemMin).max(scheduleItemControllerUpdateScheduleItemBodyTimeStartTime1ItemMax)]),
  "endTime": zod.tuple([zod.number().min(scheduleItemControllerUpdateScheduleItemBodyTimeEndTime0ItemMin).max(scheduleItemControllerUpdateScheduleItemBodyTimeEndTime0ItemMax),
zod.number().min(scheduleItemControllerUpdateScheduleItemBodyTimeEndTime1ItemMin).max(scheduleItemControllerUpdateScheduleItemBodyTimeEndTime1ItemMax)])
}).optional().describe('Объект с временем начала и окончания в формате [HH, MM]'),
  "text": zod.string().min(1).optional()
})

export const scheduleItemControllerUpdateScheduleItemResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const scheduleItemControllerUpdateScheduleItemResponseStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleItemControllerUpdateScheduleItemResponseEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');



export const ScheduleItemControllerUpdateScheduleItemResponse = zod.object({
  "id": zod.uuid().regex(scheduleItemControllerUpdateScheduleItemResponseIdRegExp),
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(scheduleItemControllerUpdateScheduleItemResponseStartTimeRegExp).optional(),
  "endTime": zod.string().regex(scheduleItemControllerUpdateScheduleItemResponseEndTimeRegExp).optional(),
  "time": zod.object({
  "startTime": zod.tuple([zod.int().min(scheduleItemControllerUpdateScheduleItemResponseTimeStartTime0ItemMin).max(scheduleItemControllerUpdateScheduleItemResponseTimeStartTime0ItemMax),
zod.int().min(scheduleItemControllerUpdateScheduleItemResponseTimeStartTime1ItemMin).max(scheduleItemControllerUpdateScheduleItemResponseTimeStartTime1ItemMax)]),
  "endTime": zod.tuple([zod.number().min(scheduleItemControllerUpdateScheduleItemResponseTimeEndTime0ItemMin).max(scheduleItemControllerUpdateScheduleItemResponseTimeEndTime0ItemMax),
zod.number().min(scheduleItemControllerUpdateScheduleItemResponseTimeEndTime1ItemMin).max(scheduleItemControllerUpdateScheduleItemResponseTimeEndTime1ItemMax)])
}).describe('Объект с временем начала и окончания в формате [HH, MM]'),
  "text": zod.string().min(1)
})

export const ScheduleItemControllerDeleteScheduleItemParams = zod.object({
  "itemId": zod.string(),
  "scheduleId": zod.uuid(),
  "userId": zod.uuid()
})

export const ScheduleItemControllerDeleteScheduleItemResponse = zod.void()

