/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import {
  useQuery,
  useQueryClient
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AvitoCallbackControllerGetBotSettingsParams
} from '../../models';

import { customInstance } from '../../client';
import type { ErrorType } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const avitoCallbackControllerGetBotSettings = (
    params: AvitoCallbackControllerGetBotSettingsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<unknown>(
      {url: `/api/callback/avito`, method: 'GET',
        params, signal
    },
      options);
    }




export const getAvitoCallbackControllerGetBotSettingsQueryKey = (params?: AvitoCallbackControllerGetBotSettingsParams,) => {
    return [
    `/api/callback/avito`, ...(params ? [params] : [])
    ] as const;
    }


export const getAvitoCallbackControllerGetBotSettingsQueryOptions = <TData = Awaited<ReturnType<typeof avitoCallbackControllerGetBotSettings>>, TError = ErrorType<void>>(params: AvitoCallbackControllerGetBotSettingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof avitoCallbackControllerGetBotSettings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAvitoCallbackControllerGetBotSettingsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof avitoCallbackControllerGetBotSettings>>> = ({ signal }) => avitoCallbackControllerGetBotSettings(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof avitoCallbackControllerGetBotSettings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AvitoCallbackControllerGetBotSettingsQueryResult = NonNullable<Awaited<ReturnType<typeof avitoCallbackControllerGetBotSettings>>>
export type AvitoCallbackControllerGetBotSettingsQueryError = ErrorType<void>


export function useAvitoCallbackControllerGetBotSettings<TData = Awaited<ReturnType<typeof avitoCallbackControllerGetBotSettings>>, TError = ErrorType<void>>(
 params: AvitoCallbackControllerGetBotSettingsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof avitoCallbackControllerGetBotSettings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof avitoCallbackControllerGetBotSettings>>,
          TError,
          Awaited<ReturnType<typeof avitoCallbackControllerGetBotSettings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAvitoCallbackControllerGetBotSettings<TData = Awaited<ReturnType<typeof avitoCallbackControllerGetBotSettings>>, TError = ErrorType<void>>(
 params: AvitoCallbackControllerGetBotSettingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof avitoCallbackControllerGetBotSettings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof avitoCallbackControllerGetBotSettings>>,
          TError,
          Awaited<ReturnType<typeof avitoCallbackControllerGetBotSettings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAvitoCallbackControllerGetBotSettings<TData = Awaited<ReturnType<typeof avitoCallbackControllerGetBotSettings>>, TError = ErrorType<void>>(
 params: AvitoCallbackControllerGetBotSettingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof avitoCallbackControllerGetBotSettings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAvitoCallbackControllerGetBotSettings<TData = Awaited<ReturnType<typeof avitoCallbackControllerGetBotSettings>>, TError = ErrorType<void>>(
 params: AvitoCallbackControllerGetBotSettingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof avitoCallbackControllerGetBotSettings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAvitoCallbackControllerGetBotSettingsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}



export const useSetAvitoCallbackControllerGetBotSettingsQueryData = () => {
  const queryClient = useQueryClient();
  return (params: AvitoCallbackControllerGetBotSettingsParams | undefined,updater: Awaited<ReturnType<typeof avitoCallbackControllerGetBotSettings>> | undefined | ((old: Awaited<ReturnType<typeof avitoCallbackControllerGetBotSettings>> | undefined) => Awaited<ReturnType<typeof avitoCallbackControllerGetBotSettings>> | undefined)) => {
    queryClient.setQueriesData<Awaited<ReturnType<typeof avitoCallbackControllerGetBotSettings>>>({ queryKey: getAvitoCallbackControllerGetBotSettingsQueryKey(params) }, updater);
  };
}

export const useGetAvitoCallbackControllerGetBotSettingsQueryData = () => {
  const queryClient = useQueryClient();
  return (params: AvitoCallbackControllerGetBotSettingsParams,) =>
    queryClient.getQueryData<Awaited<ReturnType<typeof avitoCallbackControllerGetBotSettings>>>(getAvitoCallbackControllerGetBotSettingsQueryKey(params));
}


