/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */

export * from './avitoCallbackControllerGetBotSettingsParams';
export * from './avitoWebhook';
export * from './avitoWebhookPayload';
export * from './avitoWebhookPayloadType';
export * from './avitoWebhookPayloadValue';
export * from './avitoWebhookPayloadValueChatType';
export * from './bindScheduleDto';
export * from './botDtoOutput';
export * from './botSettings';
export * from './botSettingsChatTypesItem';
export * from './createScheduleDto';
export * from './createScheduleDtoItemsItem';
export * from './createScheduleDtoItemsItemWeekDay';
export * from './scheduleDtoOutput';
export * from './schedulesWithItemsDtoOutput';
export * from './schedulesWithItemsDtoOutputItem';
export * from './schedulesWithItemsDtoOutputItemItemsItem';
export * from './schedulesWithItemsDtoOutputItemItemsItemWeekDay';
export * from './scheduleWithItemsDtoOutput';
export * from './scheduleWithItemsDtoOutputItemsItem';
export * from './scheduleWithItemsDtoOutputItemsItemWeekDay';
export * from './unbindScheduleDto';
export * from './updateBotSettings';
export * from './updateBotSettingsChatTypesItem';
export * from './updateScheduleDto';
export * from './updateScheduleDtoItemsItem';
export * from './updateScheduleDtoItemsItemWeekDay';
