/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import {
  faker
} from '@faker-js/faker';

import type {
  ScheduleItemDto,
  ScheduleItemsDto
} from '../../models';


export const getScheduleItemControllerCreateScheduleItemResponseMock = (overrideResponse: Partial<Extract<ScheduleItemDto, object>> = {}): ScheduleItemDto => ({id: faker.string.uuid(), weekDay: faker.helpers.arrayElement(['mon','tue','wed','thu','fri','sat','sun'] as const), startTime: faker.helpers.arrayElement([faker.helpers.fromRegExp("^([01]\\d|2[0-3]):([0-5]\\d)$"), undefined]), endTime: faker.helpers.arrayElement([faker.helpers.fromRegExp("^([01]\\d|2[0-3]):([0-5]\\d)$"), undefined]), time: {startTime: {hours: faker.number.int({min: 0, max: 23}), minutes: faker.number.int({min: 0, max: 59})}, endTime: {hours: faker.number.int({min: 0, max: 23}), minutes: faker.number.int({min: 0, max: 59})}}, text: faker.string.alpha({length: {min: 1, max: 20}}), ...overrideResponse})

export const getScheduleItemControllerGetScheduleItemsResponseMock = (): ScheduleItemsDto => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), weekDay: faker.helpers.arrayElement(['mon','tue','wed','thu','fri','sat','sun'] as const), startTime: faker.helpers.arrayElement([faker.helpers.fromRegExp("^([01]\\d|2[0-3]):([0-5]\\d)$"), undefined]), endTime: faker.helpers.arrayElement([faker.helpers.fromRegExp("^([01]\\d|2[0-3]):([0-5]\\d)$"), undefined]), time: {startTime: {hours: faker.number.int({min: 0, max: 23}), minutes: faker.number.int({min: 0, max: 59})}, endTime: {hours: faker.number.int({min: 0, max: 23}), minutes: faker.number.int({min: 0, max: 59})}}, text: faker.string.alpha({length: {min: 1, max: 20}})})))

export const getScheduleItemControllerBulkCreateScheduleItemsResponseMock = (): ScheduleItemsDto => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), weekDay: faker.helpers.arrayElement(['mon','tue','wed','thu','fri','sat','sun'] as const), startTime: faker.helpers.arrayElement([faker.helpers.fromRegExp("^([01]\\d|2[0-3]):([0-5]\\d)$"), undefined]), endTime: faker.helpers.arrayElement([faker.helpers.fromRegExp("^([01]\\d|2[0-3]):([0-5]\\d)$"), undefined]), time: {startTime: {hours: faker.number.int({min: 0, max: 23}), minutes: faker.number.int({min: 0, max: 59})}, endTime: {hours: faker.number.int({min: 0, max: 23}), minutes: faker.number.int({min: 0, max: 59})}}, text: faker.string.alpha({length: {min: 1, max: 20}})})))

export const getScheduleItemControllerBulkUpdateScheduleItemsResponseMock = (): ScheduleItemsDto => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), weekDay: faker.helpers.arrayElement(['mon','tue','wed','thu','fri','sat','sun'] as const), startTime: faker.helpers.arrayElement([faker.helpers.fromRegExp("^([01]\\d|2[0-3]):([0-5]\\d)$"), undefined]), endTime: faker.helpers.arrayElement([faker.helpers.fromRegExp("^([01]\\d|2[0-3]):([0-5]\\d)$"), undefined]), time: {startTime: {hours: faker.number.int({min: 0, max: 23}), minutes: faker.number.int({min: 0, max: 59})}, endTime: {hours: faker.number.int({min: 0, max: 23}), minutes: faker.number.int({min: 0, max: 59})}}, text: faker.string.alpha({length: {min: 1, max: 20}})})))

export const getScheduleItemControllerGetScheduleItemResponseMock = (overrideResponse: Partial<Extract<ScheduleItemDto, object>> = {}): ScheduleItemDto => ({id: faker.string.uuid(), weekDay: faker.helpers.arrayElement(['mon','tue','wed','thu','fri','sat','sun'] as const), startTime: faker.helpers.arrayElement([faker.helpers.fromRegExp("^([01]\\d|2[0-3]):([0-5]\\d)$"), undefined]), endTime: faker.helpers.arrayElement([faker.helpers.fromRegExp("^([01]\\d|2[0-3]):([0-5]\\d)$"), undefined]), time: {startTime: {hours: faker.number.int({min: 0, max: 23}), minutes: faker.number.int({min: 0, max: 59})}, endTime: {hours: faker.number.int({min: 0, max: 23}), minutes: faker.number.int({min: 0, max: 59})}}, text: faker.string.alpha({length: {min: 1, max: 20}}), ...overrideResponse})

export const getScheduleItemControllerUpdateScheduleItemResponseMock = (overrideResponse: Partial<Extract<ScheduleItemDto, object>> = {}): ScheduleItemDto => ({id: faker.string.uuid(), weekDay: faker.helpers.arrayElement(['mon','tue','wed','thu','fri','sat','sun'] as const), startTime: faker.helpers.arrayElement([faker.helpers.fromRegExp("^([01]\\d|2[0-3]):([0-5]\\d)$"), undefined]), endTime: faker.helpers.arrayElement([faker.helpers.fromRegExp("^([01]\\d|2[0-3]):([0-5]\\d)$"), undefined]), time: {startTime: {hours: faker.number.int({min: 0, max: 23}), minutes: faker.number.int({min: 0, max: 59})}, endTime: {hours: faker.number.int({min: 0, max: 23}), minutes: faker.number.int({min: 0, max: 59})}}, text: faker.string.alpha({length: {min: 1, max: 20}}), ...overrideResponse})

