/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  ScheduleItemDto,
  ScheduleItemsDto
} from '../../models';

import {
  getScheduleItemControllerCreateScheduleItemResponseMock,
  getScheduleItemControllerGetScheduleItemResponseMock,
  getScheduleItemControllerGetScheduleItemsResponseMock,
  getScheduleItemControllerUpdateScheduleItemResponseMock
} from './schedule-item.faker';

export { getScheduleItemControllerCreateScheduleItemResponseMock, getScheduleItemControllerGetScheduleItemsResponseMock, getScheduleItemControllerGetScheduleItemResponseMock, getScheduleItemControllerUpdateScheduleItemResponseMock } from './schedule-item.faker';


export const getScheduleItemControllerCreateScheduleItemMockHandler = (overrideResponse?: ScheduleItemDto | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ScheduleItemDto> | ScheduleItemDto), options?: RequestHandlerOptions) => {
  return http.post('*/api/users/:userId/schedules/:scheduleId/items', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getScheduleItemControllerCreateScheduleItemResponseMock(),
      { status: 200
      })
  }, options)
}

export const getScheduleItemControllerGetScheduleItemsMockHandler = (overrideResponse?: ScheduleItemsDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ScheduleItemsDto> | ScheduleItemsDto), options?: RequestHandlerOptions) => {
  return http.get('*/api/users/:userId/schedules/:scheduleId/items', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getScheduleItemControllerGetScheduleItemsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getScheduleItemControllerGetScheduleItemMockHandler = (overrideResponse?: ScheduleItemDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ScheduleItemDto> | ScheduleItemDto), options?: RequestHandlerOptions) => {
  return http.get('*/api/users/:userId/schedules/:scheduleId/items/:itemId', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getScheduleItemControllerGetScheduleItemResponseMock(),
      { status: 200
      })
  }, options)
}

export const getScheduleItemControllerUpdateScheduleItemMockHandler = (overrideResponse?: ScheduleItemDto | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<ScheduleItemDto> | ScheduleItemDto), options?: RequestHandlerOptions) => {
  return http.patch('*/api/users/:userId/schedules/:scheduleId/items/:itemId', async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getScheduleItemControllerUpdateScheduleItemResponseMock(),
      { status: 200
      })
  }, options)
}

export const getScheduleItemControllerDeleteScheduleItemMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/users/:userId/schedules/:scheduleId/items/:itemId', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}
export const getScheduleItemMock = () => [
  getScheduleItemControllerCreateScheduleItemMockHandler(),
  getScheduleItemControllerGetScheduleItemsMockHandler(),
  getScheduleItemControllerGetScheduleItemMockHandler(),
  getScheduleItemControllerUpdateScheduleItemMockHandler(),
  getScheduleItemControllerDeleteScheduleItemMockHandler()
]
