/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery,
  useQueryClient
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BulkCreateScheduleItemsDto,
  BulkUpdateScheduleItemsDto,
  CreateScheduleItemDto,
  ScheduleItemDto,
  ScheduleItemsDto,
  UpdateScheduleItemDto
} from '../../models';

import { customInstance } from '../../client';
import type { ErrorType , BodyType } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const scheduleItemControllerBulkCreateScheduleItems = (
    userId: string,
    scheduleId: string,
    bulkCreateScheduleItemsDto: BodyType<BulkCreateScheduleItemsDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ScheduleItemsDto>(
      {url: `/api/users/${userId}/schedules/${scheduleId}/items/bulk`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: bulkCreateScheduleItemsDto, signal
    },
      options);
    }




export const getScheduleItemControllerBulkCreateScheduleItemsMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof scheduleItemControllerBulkCreateScheduleItems>>, TError,{userId: string;scheduleId: string;data: BodyType<BulkCreateScheduleItemsDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof scheduleItemControllerBulkCreateScheduleItems>>, TError,{userId: string;scheduleId: string;data: BodyType<BulkCreateScheduleItemsDto>}, TContext> => {

const mutationKey = ['scheduleItemControllerBulkCreateScheduleItems'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof scheduleItemControllerBulkCreateScheduleItems>>, {userId: string;scheduleId: string;data: BodyType<BulkCreateScheduleItemsDto>}> = (props) => {
          const {userId,scheduleId,data} = props ?? {};

          return  scheduleItemControllerBulkCreateScheduleItems(userId,scheduleId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ScheduleItemControllerBulkCreateScheduleItemsMutationResult = NonNullable<Awaited<ReturnType<typeof scheduleItemControllerBulkCreateScheduleItems>>>
    export type ScheduleItemControllerBulkCreateScheduleItemsMutationBody = BodyType<BulkCreateScheduleItemsDto>
    export type ScheduleItemControllerBulkCreateScheduleItemsMutationError = ErrorType<void>

    export const useScheduleItemControllerBulkCreateScheduleItems = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof scheduleItemControllerBulkCreateScheduleItems>>, TError,{userId: string;scheduleId: string;data: BodyType<BulkCreateScheduleItemsDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof scheduleItemControllerBulkCreateScheduleItems>>,
        TError,
        {userId: string;scheduleId: string;data: BodyType<BulkCreateScheduleItemsDto>},
        TContext
      > => {
      return useMutation(getScheduleItemControllerBulkCreateScheduleItemsMutationOptions(options), queryClient);
    }
    export const scheduleItemControllerBulkUpdateScheduleItems = (
    userId: string,
    scheduleId: string,
    bulkUpdateScheduleItemsDto: BodyType<BulkUpdateScheduleItemsDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ScheduleItemsDto>(
      {url: `/api/users/${userId}/schedules/${scheduleId}/items/bulk`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: bulkUpdateScheduleItemsDto, signal
    },
      options);
    }




export const getScheduleItemControllerBulkUpdateScheduleItemsMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof scheduleItemControllerBulkUpdateScheduleItems>>, TError,{userId: string;scheduleId: string;data: BodyType<BulkUpdateScheduleItemsDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof scheduleItemControllerBulkUpdateScheduleItems>>, TError,{userId: string;scheduleId: string;data: BodyType<BulkUpdateScheduleItemsDto>}, TContext> => {

const mutationKey = ['scheduleItemControllerBulkUpdateScheduleItems'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof scheduleItemControllerBulkUpdateScheduleItems>>, {userId: string;scheduleId: string;data: BodyType<BulkUpdateScheduleItemsDto>}> = (props) => {
          const {userId,scheduleId,data} = props ?? {};

          return  scheduleItemControllerBulkUpdateScheduleItems(userId,scheduleId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ScheduleItemControllerBulkUpdateScheduleItemsMutationResult = NonNullable<Awaited<ReturnType<typeof scheduleItemControllerBulkUpdateScheduleItems>>>
    export type ScheduleItemControllerBulkUpdateScheduleItemsMutationBody = BodyType<BulkUpdateScheduleItemsDto>
    export type ScheduleItemControllerBulkUpdateScheduleItemsMutationError = ErrorType<void>

    export const useScheduleItemControllerBulkUpdateScheduleItems = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof scheduleItemControllerBulkUpdateScheduleItems>>, TError,{userId: string;scheduleId: string;data: BodyType<BulkUpdateScheduleItemsDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof scheduleItemControllerBulkUpdateScheduleItems>>,
        TError,
        {userId: string;scheduleId: string;data: BodyType<BulkUpdateScheduleItemsDto>},
        TContext
      > => {
      return useMutation(getScheduleItemControllerBulkUpdateScheduleItemsMutationOptions(options), queryClient);
    }
    export const scheduleItemControllerCreateScheduleItem = (
    userId: string,
    scheduleId: string,
    createScheduleItemDto: BodyType<CreateScheduleItemDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ScheduleItemDto>(
      {url: `/api/users/${userId}/schedules/${scheduleId}/items`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createScheduleItemDto, signal
    },
      options);
    }




export const getScheduleItemControllerCreateScheduleItemMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof scheduleItemControllerCreateScheduleItem>>, TError,{userId: string;scheduleId: string;data: BodyType<CreateScheduleItemDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof scheduleItemControllerCreateScheduleItem>>, TError,{userId: string;scheduleId: string;data: BodyType<CreateScheduleItemDto>}, TContext> => {

const mutationKey = ['scheduleItemControllerCreateScheduleItem'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof scheduleItemControllerCreateScheduleItem>>, {userId: string;scheduleId: string;data: BodyType<CreateScheduleItemDto>}> = (props) => {
          const {userId,scheduleId,data} = props ?? {};

          return  scheduleItemControllerCreateScheduleItem(userId,scheduleId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ScheduleItemControllerCreateScheduleItemMutationResult = NonNullable<Awaited<ReturnType<typeof scheduleItemControllerCreateScheduleItem>>>
    export type ScheduleItemControllerCreateScheduleItemMutationBody = BodyType<CreateScheduleItemDto>
    export type ScheduleItemControllerCreateScheduleItemMutationError = ErrorType<void>

    export const useScheduleItemControllerCreateScheduleItem = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof scheduleItemControllerCreateScheduleItem>>, TError,{userId: string;scheduleId: string;data: BodyType<CreateScheduleItemDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof scheduleItemControllerCreateScheduleItem>>,
        TError,
        {userId: string;scheduleId: string;data: BodyType<CreateScheduleItemDto>},
        TContext
      > => {
      return useMutation(getScheduleItemControllerCreateScheduleItemMutationOptions(options), queryClient);
    }
    export const scheduleItemControllerGetScheduleItems = (
    userId: string,
    scheduleId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ScheduleItemsDto>(
      {url: `/api/users/${userId}/schedules/${scheduleId}/items`, method: 'GET', signal
    },
      options);
    }




export const getScheduleItemControllerGetScheduleItemsQueryKey = (userId: string,
    scheduleId: string,) => {
    return [
    `/api/users/${userId}/schedules/${scheduleId}/items`
    ] as const;
    }


export const getScheduleItemControllerGetScheduleItemsQueryOptions = <TData = Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItems>>, TError = ErrorType<void>>(userId: string,
    scheduleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItems>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getScheduleItemControllerGetScheduleItemsQueryKey(userId,scheduleId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItems>>> = ({ signal }) => scheduleItemControllerGetScheduleItems(userId,scheduleId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: userId !== null && userId !== undefined && scheduleId !== null && scheduleId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItems>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ScheduleItemControllerGetScheduleItemsQueryResult = NonNullable<Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItems>>>
export type ScheduleItemControllerGetScheduleItemsQueryError = ErrorType<void>


export function useScheduleItemControllerGetScheduleItems<TData = Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItems>>, TError = ErrorType<void>>(
 userId: string,
    scheduleId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItems>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItems>>,
          TError,
          Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItems>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useScheduleItemControllerGetScheduleItems<TData = Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItems>>, TError = ErrorType<void>>(
 userId: string,
    scheduleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItems>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItems>>,
          TError,
          Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItems>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useScheduleItemControllerGetScheduleItems<TData = Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItems>>, TError = ErrorType<void>>(
 userId: string,
    scheduleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItems>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useScheduleItemControllerGetScheduleItems<TData = Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItems>>, TError = ErrorType<void>>(
 userId: string,
    scheduleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItems>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getScheduleItemControllerGetScheduleItemsQueryOptions(userId,scheduleId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}



export const useSetScheduleItemControllerGetScheduleItemsQueryData = () => {
  const queryClient = useQueryClient();
  return (userId: string,
    scheduleId: string,updater: Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItems>> | undefined | ((old: Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItems>> | undefined) => Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItems>> | undefined)) => {
    queryClient.setQueriesData<Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItems>>>({ queryKey: getScheduleItemControllerGetScheduleItemsQueryKey(userId,scheduleId) }, updater);
  };
}

export const useGetScheduleItemControllerGetScheduleItemsQueryData = () => {
  const queryClient = useQueryClient();
  return (userId: string,
    scheduleId: string,) =>
    queryClient.getQueryData<Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItems>>>(getScheduleItemControllerGetScheduleItemsQueryKey(userId,scheduleId));
}


export const scheduleItemControllerGetScheduleItem = (
    userId: string,
    scheduleId: string,
    itemId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ScheduleItemDto>(
      {url: `/api/users/${userId}/schedules/${scheduleId}/items/${itemId}`, method: 'GET', signal
    },
      options);
    }




export const getScheduleItemControllerGetScheduleItemQueryKey = (userId: string,
    scheduleId: string,
    itemId: string,) => {
    return [
    `/api/users/${userId}/schedules/${scheduleId}/items/${itemId}`
    ] as const;
    }


export const getScheduleItemControllerGetScheduleItemQueryOptions = <TData = Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItem>>, TError = ErrorType<void>>(userId: string,
    scheduleId: string,
    itemId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItem>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getScheduleItemControllerGetScheduleItemQueryKey(userId,scheduleId,itemId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItem>>> = ({ signal }) => scheduleItemControllerGetScheduleItem(userId,scheduleId,itemId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: userId !== null && userId !== undefined && scheduleId !== null && scheduleId !== undefined && itemId !== null && itemId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItem>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ScheduleItemControllerGetScheduleItemQueryResult = NonNullable<Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItem>>>
export type ScheduleItemControllerGetScheduleItemQueryError = ErrorType<void>


export function useScheduleItemControllerGetScheduleItem<TData = Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItem>>, TError = ErrorType<void>>(
 userId: string,
    scheduleId: string,
    itemId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItem>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItem>>,
          TError,
          Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItem>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useScheduleItemControllerGetScheduleItem<TData = Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItem>>, TError = ErrorType<void>>(
 userId: string,
    scheduleId: string,
    itemId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItem>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItem>>,
          TError,
          Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItem>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useScheduleItemControllerGetScheduleItem<TData = Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItem>>, TError = ErrorType<void>>(
 userId: string,
    scheduleId: string,
    itemId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItem>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useScheduleItemControllerGetScheduleItem<TData = Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItem>>, TError = ErrorType<void>>(
 userId: string,
    scheduleId: string,
    itemId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItem>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getScheduleItemControllerGetScheduleItemQueryOptions(userId,scheduleId,itemId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}



export const useSetScheduleItemControllerGetScheduleItemQueryData = () => {
  const queryClient = useQueryClient();
  return (userId: string,
    scheduleId: string,
    itemId: string,updater: Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItem>> | undefined | ((old: Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItem>> | undefined) => Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItem>> | undefined)) => {
    queryClient.setQueriesData<Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItem>>>({ queryKey: getScheduleItemControllerGetScheduleItemQueryKey(userId,scheduleId,itemId) }, updater);
  };
}

export const useGetScheduleItemControllerGetScheduleItemQueryData = () => {
  const queryClient = useQueryClient();
  return (userId: string,
    scheduleId: string,
    itemId: string,) =>
    queryClient.getQueryData<Awaited<ReturnType<typeof scheduleItemControllerGetScheduleItem>>>(getScheduleItemControllerGetScheduleItemQueryKey(userId,scheduleId,itemId));
}


export const scheduleItemControllerUpdateScheduleItem = (
    userId: string,
    scheduleId: string,
    itemId: string,
    updateScheduleItemDto: BodyType<UpdateScheduleItemDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ScheduleItemDto>(
      {url: `/api/users/${userId}/schedules/${scheduleId}/items/${itemId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateScheduleItemDto, signal
    },
      options);
    }




export const getScheduleItemControllerUpdateScheduleItemMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof scheduleItemControllerUpdateScheduleItem>>, TError,{userId: string;scheduleId: string;itemId: string;data: BodyType<UpdateScheduleItemDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof scheduleItemControllerUpdateScheduleItem>>, TError,{userId: string;scheduleId: string;itemId: string;data: BodyType<UpdateScheduleItemDto>}, TContext> => {

const mutationKey = ['scheduleItemControllerUpdateScheduleItem'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof scheduleItemControllerUpdateScheduleItem>>, {userId: string;scheduleId: string;itemId: string;data: BodyType<UpdateScheduleItemDto>}> = (props) => {
          const {userId,scheduleId,itemId,data} = props ?? {};

          return  scheduleItemControllerUpdateScheduleItem(userId,scheduleId,itemId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ScheduleItemControllerUpdateScheduleItemMutationResult = NonNullable<Awaited<ReturnType<typeof scheduleItemControllerUpdateScheduleItem>>>
    export type ScheduleItemControllerUpdateScheduleItemMutationBody = BodyType<UpdateScheduleItemDto>
    export type ScheduleItemControllerUpdateScheduleItemMutationError = ErrorType<void>

    export const useScheduleItemControllerUpdateScheduleItem = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof scheduleItemControllerUpdateScheduleItem>>, TError,{userId: string;scheduleId: string;itemId: string;data: BodyType<UpdateScheduleItemDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof scheduleItemControllerUpdateScheduleItem>>,
        TError,
        {userId: string;scheduleId: string;itemId: string;data: BodyType<UpdateScheduleItemDto>},
        TContext
      > => {
      return useMutation(getScheduleItemControllerUpdateScheduleItemMutationOptions(options), queryClient);
    }
    export const scheduleItemControllerDeleteScheduleItem = (
    userId: string,
    scheduleId: string,
    itemId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/users/${userId}/schedules/${scheduleId}/items/${itemId}`, method: 'DELETE', signal
    },
      options);
    }




export const getScheduleItemControllerDeleteScheduleItemMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof scheduleItemControllerDeleteScheduleItem>>, TError,{userId: string;scheduleId: string;itemId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof scheduleItemControllerDeleteScheduleItem>>, TError,{userId: string;scheduleId: string;itemId: string}, TContext> => {

const mutationKey = ['scheduleItemControllerDeleteScheduleItem'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof scheduleItemControllerDeleteScheduleItem>>, {userId: string;scheduleId: string;itemId: string}> = (props) => {
          const {userId,scheduleId,itemId} = props ?? {};

          return  scheduleItemControllerDeleteScheduleItem(userId,scheduleId,itemId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ScheduleItemControllerDeleteScheduleItemMutationResult = NonNullable<Awaited<ReturnType<typeof scheduleItemControllerDeleteScheduleItem>>>

    export type ScheduleItemControllerDeleteScheduleItemMutationError = ErrorType<void>

    export const useScheduleItemControllerDeleteScheduleItem = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof scheduleItemControllerDeleteScheduleItem>>, TError,{userId: string;scheduleId: string;itemId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof scheduleItemControllerDeleteScheduleItem>>,
        TError,
        {userId: string;scheduleId: string;itemId: string},
        TContext
      > => {
      return useMutation(getScheduleItemControllerDeleteScheduleItemMutationOptions(options), queryClient);
    }
