/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import type { SchedulesWithItemsDtoOutputItem } from './schedulesWithItemsDtoOutputItem.zod';

export type SchedulesWithItemsDtoOutput = SchedulesWithItemsDtoOutputItem[];
