/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


export const AvitoCallbackControllerGetBotSettingsQueryParams = zod.object({
  "code": zod.string()
})

export const AvitoCallbackControllerGetBotSettingsResponse = zod.void()

