/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


export const AvitoCallbackControllerGetBotSettingsQueryParams = zod.object({
  "code": zod.string()
})

export const AvitoCallbackControllerGetBotSettingsResponse = zod.unknown()


export const BotControllerGetBotParams = zod.object({
  "userId": zod.uuid()
})

export const botControllerGetBotResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const botControllerGetBotResponseUserIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');


export const BotControllerGetBotResponse = zod.object({
  "id": zod.uuid().regex(botControllerGetBotResponseIdRegExp),
  "userId": zod.uuid().regex(botControllerGetBotResponseUserIdRegExp)
})


export const BotControllerDeleteBotParams = zod.object({
  "userId": zod.uuid()
})

export const BotControllerDeleteBotResponse = zod.unknown()


export const BotControllerBindScheduleParams = zod.object({
  "botId": zod.string(),
  "userId": zod.uuid()
})

export const botControllerBindScheduleBodyScheduleIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');


export const BotControllerBindScheduleBody = zod.object({
  "scheduleId": zod.uuid().regex(botControllerBindScheduleBodyScheduleIdRegExp)
})

export const BotControllerBindScheduleResponse = zod.void()


export const BotControllerUnbindScheduleParams = zod.object({
  "botId": zod.string(),
  "userId": zod.uuid()
})

export const botControllerUnbindScheduleBodyScheduleIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');


export const BotControllerUnbindScheduleBody = zod.object({
  "scheduleId": zod.uuid().regex(botControllerUnbindScheduleBodyScheduleIdRegExp)
})

export const BotControllerUnbindScheduleResponse = zod.void()


export const BotControllerGetBotSchedulesParams = zod.object({
  "botId": zod.string(),
  "userId": zod.uuid()
})

export const botControllerGetBotSchedulesResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const botControllerGetBotSchedulesResponseItemsItemStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const botControllerGetBotSchedulesResponseItemsItemEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');



export const BotControllerGetBotSchedulesResponseItem = zod.object({
  "id": zod.uuid().regex(botControllerGetBotSchedulesResponseIdRegExp),
  "name": zod.string(),
  "items": zod.array(zod.object({
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(botControllerGetBotSchedulesResponseItemsItemStartTimeRegExp),
  "endTime": zod.string().regex(botControllerGetBotSchedulesResponseItemsItemEndTimeRegExp),
  "text": zod.string().min(1)
}))
})
export const BotControllerGetBotSchedulesResponse = zod.array(BotControllerGetBotSchedulesResponseItem)


export const BotControllerGetBotSettingsParams = zod.object({
  "botId": zod.string(),
  "userId": zod.uuid()
})

export const BotControllerGetBotSettingsResponse = zod.object({
  "answerOnFirstMessage": zod.boolean().describe('Флаг, который отвечает за необходимость ответа только на первое сообщение, отправленное пользователем в чате'),
  "chatTypes": zod.array(zod.enum(['u2i', 'u2u'])).describe('Типы чатов, на которые будет работать автоответ'),
  "isActive": zod.boolean().describe('Флаг активности бота')
}).describe('Объект с настройками бота')


export const BotControllerUpdateBotSettingsParams = zod.object({
  "botId": zod.string(),
  "userId": zod.uuid()
})

export const BotControllerUpdateBotSettingsBody = zod.object({
  "answerOnFirstMessage": zod.boolean().optional().describe('Флаг, который отвечает за необходимость ответа только на первое сообщение, отправленное пользователем в чате'),
  "chatTypes": zod.array(zod.enum(['u2i', 'u2u'])).optional().describe('Типы чатов, на которые будет работать автоответ'),
  "isActive": zod.boolean().optional().describe('Флаг активности бота')
}).describe('Объект с данными для обновления настроек бота')

export const BotControllerUpdateBotSettingsResponse = zod.object({
  "answerOnFirstMessage": zod.boolean().describe('Флаг, который отвечает за необходимость ответа только на первое сообщение, отправленное пользователем в чате'),
  "chatTypes": zod.array(zod.enum(['u2i', 'u2u'])).describe('Типы чатов, на которые будет работать автоответ'),
  "isActive": zod.boolean().describe('Флаг активности бота')
}).describe('Объект с настройками бота')


export const ScheduleControllerCreateScheduleParams = zod.object({
  "userId": zod.uuid()
})


export const scheduleControllerCreateScheduleBodyItemsItemStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleControllerCreateScheduleBodyItemsItemEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');



export const ScheduleControllerCreateScheduleBody = zod.object({
  "name": zod.string().min(1),
  "items": zod.array(zod.object({
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(scheduleControllerCreateScheduleBodyItemsItemStartTimeRegExp),
  "endTime": zod.string().regex(scheduleControllerCreateScheduleBodyItemsItemEndTimeRegExp),
  "text": zod.string().min(1)
})).optional()
})

export const scheduleControllerCreateScheduleResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');


export const ScheduleControllerCreateScheduleResponse = zod.object({
  "id": zod.uuid().regex(scheduleControllerCreateScheduleResponseIdRegExp),
  "name": zod.string()
})


export const ScheduleControllerUserScheduleListParams = zod.object({
  "userId": zod.uuid()
})

export const scheduleControllerUserScheduleListResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const scheduleControllerUserScheduleListResponseItemsItemStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleControllerUserScheduleListResponseItemsItemEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');



export const ScheduleControllerUserScheduleListResponseItem = zod.object({
  "id": zod.uuid().regex(scheduleControllerUserScheduleListResponseIdRegExp),
  "name": zod.string(),
  "items": zod.array(zod.object({
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(scheduleControllerUserScheduleListResponseItemsItemStartTimeRegExp),
  "endTime": zod.string().regex(scheduleControllerUserScheduleListResponseItemsItemEndTimeRegExp),
  "text": zod.string().min(1)
}))
})
export const ScheduleControllerUserScheduleListResponse = zod.array(ScheduleControllerUserScheduleListResponseItem)


export const ScheduleControllerGetScheduleParams = zod.object({
  "scheduleId": zod.string(),
  "userId": zod.uuid()
})

export const scheduleControllerGetScheduleResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const scheduleControllerGetScheduleResponseItemsItemStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleControllerGetScheduleResponseItemsItemEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');



export const ScheduleControllerGetScheduleResponse = zod.object({
  "id": zod.uuid().regex(scheduleControllerGetScheduleResponseIdRegExp),
  "name": zod.string(),
  "items": zod.array(zod.object({
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(scheduleControllerGetScheduleResponseItemsItemStartTimeRegExp),
  "endTime": zod.string().regex(scheduleControllerGetScheduleResponseItemsItemEndTimeRegExp),
  "text": zod.string().min(1)
}))
})


export const ScheduleControllerUpdateScheduleParams = zod.object({
  "scheduleId": zod.string(),
  "userId": zod.uuid()
})


export const scheduleControllerUpdateScheduleBodyItemsItemStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleControllerUpdateScheduleBodyItemsItemEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');



export const ScheduleControllerUpdateScheduleBody = zod.object({
  "name": zod.string().min(1).optional(),
  "items": zod.array(zod.object({
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(scheduleControllerUpdateScheduleBodyItemsItemStartTimeRegExp),
  "endTime": zod.string().regex(scheduleControllerUpdateScheduleBodyItemsItemEndTimeRegExp),
  "text": zod.string().min(1)
})).optional()
})

export const scheduleControllerUpdateScheduleResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const scheduleControllerUpdateScheduleResponseItemsItemStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleControllerUpdateScheduleResponseItemsItemEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');



export const ScheduleControllerUpdateScheduleResponse = zod.object({
  "id": zod.uuid().regex(scheduleControllerUpdateScheduleResponseIdRegExp),
  "name": zod.string(),
  "items": zod.array(zod.object({
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(scheduleControllerUpdateScheduleResponseItemsItemStartTimeRegExp),
  "endTime": zod.string().regex(scheduleControllerUpdateScheduleResponseItemsItemEndTimeRegExp),
  "text": zod.string().min(1)
}))
})


export const ScheduleControllerDeleteScheduleParams = zod.object({
  "scheduleId": zod.string(),
  "userId": zod.uuid()
})

export const ScheduleControllerDeleteScheduleResponse = zod.unknown()


export const WebhookControllerAvitoBody = zod.object({
  "id": zod.string(),
  "version": zod.string(),
  "timestamp": zod.number(),
  "payload": zod.object({
  "type": zod.enum(['message']),
  "value": zod.object({
  "id": zod.string(),
  "chat_id": zod.string(),
  "user_id": zod.number(),
  "author_id": zod.number(),
  "created": zod.number(),
  "chat_type": zod.enum(['u2u', 'u2i']),
  "content": zod.unknown(),
  "item_id": zod.number().optional()
})
})
}).describe('Payload, который присылает Avito в вебхуке')

export const WebhookControllerAvitoResponse = zod.void()


