/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


export const BotControllerGetUserBotsParams = zod.object({
  "userId": zod.uuid()
})

export const botControllerGetUserBotsResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const botControllerGetUserBotsResponseUserIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');


export const BotControllerGetUserBotsResponseItem = zod.object({
  "id": zod.uuid().regex(botControllerGetUserBotsResponseIdRegExp),
  "userId": zod.uuid().regex(botControllerGetUserBotsResponseUserIdRegExp)
}).describe('Объект с информацией о боте')
export const BotControllerGetUserBotsResponse = zod.array(BotControllerGetUserBotsResponseItem)

export const BotControllerGetBotParams = zod.object({
  "userId": zod.uuid(),
  "botId": zod.uuid()
})

export const botControllerGetBotResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const botControllerGetBotResponseUserIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');


export const BotControllerGetBotResponse = zod.object({
  "id": zod.uuid().regex(botControllerGetBotResponseIdRegExp),
  "userId": zod.uuid().regex(botControllerGetBotResponseUserIdRegExp)
}).describe('Объект с информацией о боте')

export const BotControllerDeleteBotParams = zod.object({
  "userId": zod.uuid(),
  "botId": zod.uuid()
})

export const BotControllerDeleteBotResponse = zod.unknown()

export const BotControllerBindScheduleParams = zod.object({
  "botId": zod.uuid(),
  "userId": zod.uuid()
})

export const botControllerBindScheduleBodyScheduleIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');


export const BotControllerBindScheduleBody = zod.object({
  "scheduleId": zod.uuid().regex(botControllerBindScheduleBodyScheduleIdRegExp)
})

export const BotControllerBindScheduleResponse = zod.void()

export const BotControllerUnbindScheduleParams = zod.object({
  "botId": zod.uuid(),
  "userId": zod.uuid()
})

export const botControllerUnbindScheduleBodyScheduleIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');


export const BotControllerUnbindScheduleBody = zod.object({
  "scheduleId": zod.uuid().regex(botControllerUnbindScheduleBodyScheduleIdRegExp)
})

export const BotControllerUnbindScheduleResponse = zod.void()

export const BotControllerGetBotSchedulesParams = zod.object({
  "botId": zod.uuid(),
  "userId": zod.uuid()
})

export const botControllerGetBotSchedulesResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');

export const botControllerGetBotSchedulesResponseItemsItemIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const botControllerGetBotSchedulesResponseItemsItemStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const botControllerGetBotSchedulesResponseItemsItemEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');



export const BotControllerGetBotSchedulesResponseItem = zod.object({
  "id": zod.uuid().regex(botControllerGetBotSchedulesResponseIdRegExp),
  "name": zod.string().min(1),
  "items": zod.array(zod.object({
  "id": zod.uuid().regex(botControllerGetBotSchedulesResponseItemsItemIdRegExp),
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(botControllerGetBotSchedulesResponseItemsItemStartTimeRegExp).optional(),
  "endTime": zod.string().regex(botControllerGetBotSchedulesResponseItemsItemEndTimeRegExp).optional(),
  "time": zod.object({
  "startTime": zod.tuple([zod.int().min(botControllerGetBotSchedulesResponseItemsItemTimeStartTime0ItemMin).max(botControllerGetBotSchedulesResponseItemsItemTimeStartTime0ItemMax),
zod.int().min(botControllerGetBotSchedulesResponseItemsItemTimeStartTime1ItemMin).max(botControllerGetBotSchedulesResponseItemsItemTimeStartTime1ItemMax)]),
  "endTime": zod.tuple([zod.number().min(botControllerGetBotSchedulesResponseItemsItemTimeEndTime0ItemMin).max(botControllerGetBotSchedulesResponseItemsItemTimeEndTime0ItemMax),
zod.number().min(botControllerGetBotSchedulesResponseItemsItemTimeEndTime1ItemMin).max(botControllerGetBotSchedulesResponseItemsItemTimeEndTime1ItemMax)])
}).describe('Объект с временем начала и окончания в формате [HH, MM]'),
  "text": zod.string().min(1)
}))
})
export const BotControllerGetBotSchedulesResponse = zod.array(BotControllerGetBotSchedulesResponseItem)

export const BotControllerGetBotSettingsParams = zod.object({
  "botId": zod.uuid(),
  "userId": zod.uuid()
})

export const BotControllerGetBotSettingsResponse = zod.object({
  "answerOnFirstMessage": zod.boolean().describe('Флаг, который отвечает за необходимость ответа только на первое сообщение, отправленное пользователем в чате'),
  "chatTypes": zod.array(zod.enum(['u2i', 'u2u'])).describe('Типы чатов, на которые будет работать автоответ'),
  "isActive": zod.boolean().describe('Флаг активности бота')
}).describe('Объект с настройками бота')

export const BotControllerUpdateBotSettingsParams = zod.object({
  "botId": zod.uuid(),
  "userId": zod.uuid()
})

export const BotControllerUpdateBotSettingsBody = zod.object({
  "answerOnFirstMessage": zod.boolean().optional().describe('Флаг, который отвечает за необходимость ответа только на первое сообщение, отправленное пользователем в чате'),
  "chatTypes": zod.array(zod.enum(['u2i', 'u2u'])).optional().describe('Типы чатов, на которые будет работать автоответ'),
  "isActive": zod.boolean().optional().describe('Флаг активности бота')
}).describe('Объект с данными для обновления настроек бота')

export const BotControllerUpdateBotSettingsResponse = zod.object({
  "answerOnFirstMessage": zod.boolean().describe('Флаг, который отвечает за необходимость ответа только на первое сообщение, отправленное пользователем в чате'),
  "chatTypes": zod.array(zod.enum(['u2i', 'u2u'])).describe('Типы чатов, на которые будет работать автоответ'),
  "isActive": zod.boolean().describe('Флаг активности бота')
}).describe('Объект с настройками бота')

