/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


export const ScheduleControllerCreateScheduleParams = zod.object({
  "userId": zod.uuid()
})


export const scheduleControllerCreateScheduleBodyItemsItemStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleControllerCreateScheduleBodyItemsItemEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');



export const ScheduleControllerCreateScheduleBody = zod.object({
  "name": zod.string().min(1),
  "items": zod.array(zod.object({
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(scheduleControllerCreateScheduleBodyItemsItemStartTimeRegExp).optional(),
  "endTime": zod.string().regex(scheduleControllerCreateScheduleBodyItemsItemEndTimeRegExp).optional(),
  "time": zod.object({
  "startTime": zod.tuple([zod.int().min(scheduleControllerCreateScheduleBodyItemsItemTimeStartTime0ItemMin).max(scheduleControllerCreateScheduleBodyItemsItemTimeStartTime0ItemMax),
zod.int().min(scheduleControllerCreateScheduleBodyItemsItemTimeStartTime1ItemMin).max(scheduleControllerCreateScheduleBodyItemsItemTimeStartTime1ItemMax)]),
  "endTime": zod.tuple([zod.number().min(scheduleControllerCreateScheduleBodyItemsItemTimeEndTime0ItemMin).max(scheduleControllerCreateScheduleBodyItemsItemTimeEndTime0ItemMax),
zod.number().min(scheduleControllerCreateScheduleBodyItemsItemTimeEndTime1ItemMin).max(scheduleControllerCreateScheduleBodyItemsItemTimeEndTime1ItemMax)])
}).describe('Объект с временем начала и окончания в формате [HH, MM]'),
  "text": zod.string().min(1)
})).optional()
})

export const scheduleControllerCreateScheduleResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');



export const ScheduleControllerCreateScheduleResponse = zod.object({
  "id": zod.uuid().regex(scheduleControllerCreateScheduleResponseIdRegExp),
  "name": zod.string().min(1)
})

export const ScheduleControllerUserScheduleListParams = zod.object({
  "userId": zod.uuid()
})

export const scheduleControllerUserScheduleListResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');

export const scheduleControllerUserScheduleListResponseItemsItemIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const scheduleControllerUserScheduleListResponseItemsItemStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleControllerUserScheduleListResponseItemsItemEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');



export const ScheduleControllerUserScheduleListResponseItem = zod.object({
  "id": zod.uuid().regex(scheduleControllerUserScheduleListResponseIdRegExp),
  "name": zod.string().min(1),
  "items": zod.array(zod.object({
  "id": zod.uuid().regex(scheduleControllerUserScheduleListResponseItemsItemIdRegExp),
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(scheduleControllerUserScheduleListResponseItemsItemStartTimeRegExp).optional(),
  "endTime": zod.string().regex(scheduleControllerUserScheduleListResponseItemsItemEndTimeRegExp).optional(),
  "time": zod.object({
  "startTime": zod.tuple([zod.int().min(scheduleControllerUserScheduleListResponseItemsItemTimeStartTime0ItemMin).max(scheduleControllerUserScheduleListResponseItemsItemTimeStartTime0ItemMax),
zod.int().min(scheduleControllerUserScheduleListResponseItemsItemTimeStartTime1ItemMin).max(scheduleControllerUserScheduleListResponseItemsItemTimeStartTime1ItemMax)]),
  "endTime": zod.tuple([zod.number().min(scheduleControllerUserScheduleListResponseItemsItemTimeEndTime0ItemMin).max(scheduleControllerUserScheduleListResponseItemsItemTimeEndTime0ItemMax),
zod.number().min(scheduleControllerUserScheduleListResponseItemsItemTimeEndTime1ItemMin).max(scheduleControllerUserScheduleListResponseItemsItemTimeEndTime1ItemMax)])
}).describe('Объект с временем начала и окончания в формате [HH, MM]'),
  "text": zod.string().min(1)
}))
})
export const ScheduleControllerUserScheduleListResponse = zod.array(ScheduleControllerUserScheduleListResponseItem)

export const ScheduleControllerGetScheduleParams = zod.object({
  "scheduleId": zod.string(),
  "userId": zod.uuid()
})

export const scheduleControllerGetScheduleResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');

export const scheduleControllerGetScheduleResponseItemsItemIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const scheduleControllerGetScheduleResponseItemsItemStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleControllerGetScheduleResponseItemsItemEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');



export const ScheduleControllerGetScheduleResponse = zod.object({
  "id": zod.uuid().regex(scheduleControllerGetScheduleResponseIdRegExp),
  "name": zod.string().min(1),
  "items": zod.array(zod.object({
  "id": zod.uuid().regex(scheduleControllerGetScheduleResponseItemsItemIdRegExp),
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(scheduleControllerGetScheduleResponseItemsItemStartTimeRegExp).optional(),
  "endTime": zod.string().regex(scheduleControllerGetScheduleResponseItemsItemEndTimeRegExp).optional(),
  "time": zod.object({
  "startTime": zod.tuple([zod.int().min(scheduleControllerGetScheduleResponseItemsItemTimeStartTime0ItemMin).max(scheduleControllerGetScheduleResponseItemsItemTimeStartTime0ItemMax),
zod.int().min(scheduleControllerGetScheduleResponseItemsItemTimeStartTime1ItemMin).max(scheduleControllerGetScheduleResponseItemsItemTimeStartTime1ItemMax)]),
  "endTime": zod.tuple([zod.number().min(scheduleControllerGetScheduleResponseItemsItemTimeEndTime0ItemMin).max(scheduleControllerGetScheduleResponseItemsItemTimeEndTime0ItemMax),
zod.number().min(scheduleControllerGetScheduleResponseItemsItemTimeEndTime1ItemMin).max(scheduleControllerGetScheduleResponseItemsItemTimeEndTime1ItemMax)])
}).describe('Объект с временем начала и окончания в формате [HH, MM]'),
  "text": zod.string().min(1)
}))
})

export const ScheduleControllerUpdateScheduleParams = zod.object({
  "scheduleId": zod.string(),
  "userId": zod.uuid()
})


export const scheduleControllerUpdateScheduleBodyItemsItemStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleControllerUpdateScheduleBodyItemsItemEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');



export const ScheduleControllerUpdateScheduleBody = zod.object({
  "name": zod.string().min(1).optional(),
  "items": zod.array(zod.object({
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(scheduleControllerUpdateScheduleBodyItemsItemStartTimeRegExp).optional(),
  "endTime": zod.string().regex(scheduleControllerUpdateScheduleBodyItemsItemEndTimeRegExp).optional(),
  "time": zod.object({
  "startTime": zod.tuple([zod.int().min(scheduleControllerUpdateScheduleBodyItemsItemTimeStartTime0ItemMin).max(scheduleControllerUpdateScheduleBodyItemsItemTimeStartTime0ItemMax),
zod.int().min(scheduleControllerUpdateScheduleBodyItemsItemTimeStartTime1ItemMin).max(scheduleControllerUpdateScheduleBodyItemsItemTimeStartTime1ItemMax)]),
  "endTime": zod.tuple([zod.number().min(scheduleControllerUpdateScheduleBodyItemsItemTimeEndTime0ItemMin).max(scheduleControllerUpdateScheduleBodyItemsItemTimeEndTime0ItemMax),
zod.number().min(scheduleControllerUpdateScheduleBodyItemsItemTimeEndTime1ItemMin).max(scheduleControllerUpdateScheduleBodyItemsItemTimeEndTime1ItemMax)])
}).describe('Объект с временем начала и окончания в формате [HH, MM]'),
  "text": zod.string().min(1)
})).optional()
})

export const scheduleControllerUpdateScheduleResponseIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');

export const scheduleControllerUpdateScheduleResponseItemsItemIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const scheduleControllerUpdateScheduleResponseItemsItemStartTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');
export const scheduleControllerUpdateScheduleResponseItemsItemEndTimeRegExp = new RegExp('^([01]\\d|2[0-3]):([0-5]\\d)$');



export const ScheduleControllerUpdateScheduleResponse = zod.object({
  "id": zod.uuid().regex(scheduleControllerUpdateScheduleResponseIdRegExp),
  "name": zod.string().min(1),
  "items": zod.array(zod.object({
  "id": zod.uuid().regex(scheduleControllerUpdateScheduleResponseItemsItemIdRegExp),
  "weekDay": zod.enum(['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']),
  "startTime": zod.string().regex(scheduleControllerUpdateScheduleResponseItemsItemStartTimeRegExp).optional(),
  "endTime": zod.string().regex(scheduleControllerUpdateScheduleResponseItemsItemEndTimeRegExp).optional(),
  "time": zod.object({
  "startTime": zod.tuple([zod.int().min(scheduleControllerUpdateScheduleResponseItemsItemTimeStartTime0ItemMin).max(scheduleControllerUpdateScheduleResponseItemsItemTimeStartTime0ItemMax),
zod.int().min(scheduleControllerUpdateScheduleResponseItemsItemTimeStartTime1ItemMin).max(scheduleControllerUpdateScheduleResponseItemsItemTimeStartTime1ItemMax)]),
  "endTime": zod.tuple([zod.number().min(scheduleControllerUpdateScheduleResponseItemsItemTimeEndTime0ItemMin).max(scheduleControllerUpdateScheduleResponseItemsItemTimeEndTime0ItemMax),
zod.number().min(scheduleControllerUpdateScheduleResponseItemsItemTimeEndTime1ItemMin).max(scheduleControllerUpdateScheduleResponseItemsItemTimeEndTime1ItemMax)])
}).describe('Объект с временем начала и окончания в формате [HH, MM]'),
  "text": zod.string().min(1)
}))
})

export const ScheduleControllerDeleteScheduleParams = zod.object({
  "scheduleId": zod.string(),
  "userId": zod.uuid()
})

export const ScheduleControllerDeleteScheduleResponse = zod.void()

