/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  BotDtoOutput,
  BotSettings,
  SchedulesWithItemsDtoOutput
} from '../../models';

import {
  getBotControllerGetBotResponseMock,
  getBotControllerGetBotSchedulesResponseMock,
  getBotControllerGetBotSettingsResponseMock,
  getBotControllerUpdateBotSettingsResponseMock
} from './bot.faker';

export { getBotControllerGetBotResponseMock, getBotControllerGetBotSchedulesResponseMock, getBotControllerGetBotSettingsResponseMock, getBotControllerUpdateBotSettingsResponseMock } from './bot.faker';


export const getBotControllerGetBotMockHandler = (overrideResponse?: BotDtoOutput | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<BotDtoOutput> | BotDtoOutput), options?: RequestHandlerOptions) => {
  return http.get('*/api/user/:userId/bot/:botId', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getBotControllerGetBotResponseMock(),
      { status: 200
      })
  }, options)
}

export const getBotControllerDeleteBotMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/user/:userId/bot/:botId', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getBotControllerBindScheduleMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/user/:userId/bot/:botId/bind-schedule', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 201
      })
  }, options)
}

export const getBotControllerUnbindScheduleMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/user/:userId/bot/:botId/unbind-schedule', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 201
      })
  }, options)
}

export const getBotControllerGetBotSchedulesMockHandler = (overrideResponse?: SchedulesWithItemsDtoOutput | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<SchedulesWithItemsDtoOutput> | SchedulesWithItemsDtoOutput), options?: RequestHandlerOptions) => {
  return http.get('*/api/user/:userId/bot/:botId/schedule', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getBotControllerGetBotSchedulesResponseMock(),
      { status: 200
      })
  }, options)
}

export const getBotControllerGetBotSettingsMockHandler = (overrideResponse?: BotSettings | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<BotSettings> | BotSettings), options?: RequestHandlerOptions) => {
  return http.get('*/api/user/:userId/bot/:botId/settings', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getBotControllerGetBotSettingsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getBotControllerUpdateBotSettingsMockHandler = (overrideResponse?: BotSettings | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<BotSettings> | BotSettings), options?: RequestHandlerOptions) => {
  return http.patch('*/api/user/:userId/bot/:botId/settings', async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getBotControllerUpdateBotSettingsResponseMock(),
      { status: 200
      })
  }, options)
}
export const getBotMock = () => [
  getBotControllerGetBotMockHandler(),
  getBotControllerDeleteBotMockHandler(),
  getBotControllerBindScheduleMockHandler(),
  getBotControllerUnbindScheduleMockHandler(),
  getBotControllerGetBotSchedulesMockHandler(),
  getBotControllerGetBotSettingsMockHandler(),
  getBotControllerUpdateBotSettingsMockHandler()
]
