/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  BotDto,
  BotSettings,
  SchedulesWithItemsDto
} from '../../models';

import {
  getBotControllerGetBotResponseMock,
  getBotControllerGetBotSchedulesResponseMock,
  getBotControllerGetBotSettingsResponseMock,
  getBotControllerGetUserBotsResponseMock,
  getBotControllerUpdateBotSettingsResponseMock
} from './bot.faker';

export { getBotControllerGetUserBotsResponseMock, getBotControllerGetBotResponseMock, getBotControllerGetBotSchedulesResponseMock, getBotControllerGetBotSettingsResponseMock, getBotControllerUpdateBotSettingsResponseMock } from './bot.faker';


export const getBotControllerGetUserBotsMockHandler = (overrideResponse?: BotDto[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<BotDto[]> | BotDto[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/users/:userId/bots', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getBotControllerGetUserBotsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getBotControllerGetBotMockHandler = (overrideResponse?: BotDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<BotDto> | BotDto), options?: RequestHandlerOptions) => {
  return http.get('*/api/users/:userId/bots/:botId', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getBotControllerGetBotResponseMock(),
      { status: 200
      })
  }, options)
}

export const getBotControllerDeleteBotMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/users/:userId/bots/:botId', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getBotControllerBindScheduleMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/users/:userId/bots/:botId/bind-schedule', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 201
      })
  }, options)
}

export const getBotControllerUnbindScheduleMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/users/:userId/bots/:botId/unbind-schedule', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 201
      })
  }, options)
}

export const getBotControllerGetBotSchedulesMockHandler = (overrideResponse?: SchedulesWithItemsDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<SchedulesWithItemsDto> | SchedulesWithItemsDto), options?: RequestHandlerOptions) => {
  return http.get('*/api/users/:userId/bots/:botId/schedule', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getBotControllerGetBotSchedulesResponseMock(),
      { status: 200
      })
  }, options)
}

export const getBotControllerGetBotSettingsMockHandler = (overrideResponse?: BotSettings | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<BotSettings> | BotSettings), options?: RequestHandlerOptions) => {
  return http.get('*/api/users/:userId/bots/:botId/settings', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getBotControllerGetBotSettingsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getBotControllerUpdateBotSettingsMockHandler = (overrideResponse?: BotSettings | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<BotSettings> | BotSettings), options?: RequestHandlerOptions) => {
  return http.patch('*/api/users/:userId/bots/:botId/settings', async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getBotControllerUpdateBotSettingsResponseMock(),
      { status: 200
      })
  }, options)
}
export const getBotMock = () => [
  getBotControllerGetUserBotsMockHandler(),
  getBotControllerGetBotMockHandler(),
  getBotControllerDeleteBotMockHandler(),
  getBotControllerBindScheduleMockHandler(),
  getBotControllerUnbindScheduleMockHandler(),
  getBotControllerGetBotSchedulesMockHandler(),
  getBotControllerGetBotSettingsMockHandler(),
  getBotControllerUpdateBotSettingsMockHandler()
]
