/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import {
  faker
} from '@faker-js/faker';

import type {
  BotDtoOutput,
  BotSettings,
  SchedulesWithItemsDtoOutput
} from '../../models';


export const getBotControllerGetBotResponseMock = (overrideResponse: Partial<Extract<BotDtoOutput, object>> = {}): BotDtoOutput => ({id: faker.string.uuid(), userId: faker.string.uuid(), ...overrideResponse})

export const getBotControllerGetBotSchedulesResponseMock = (): SchedulesWithItemsDtoOutput => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}}), items: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({weekDay: faker.helpers.arrayElement(['mon','tue','wed','thu','fri','sat','sun'] as const), startTime: faker.helpers.fromRegExp("^([01]\\d|2[0-3]):([0-5]\\d)$"), endTime: faker.helpers.fromRegExp("^([01]\\d|2[0-3]):([0-5]\\d)$"), text: faker.string.alpha({length: {min: 1, max: 20}})}))})))

export const getBotControllerGetBotSettingsResponseMock = (overrideResponse: Partial<Extract<BotSettings, object>> = {}): BotSettings => ({answerOnFirstMessage: faker.datatype.boolean(), chatTypes: faker.helpers.arrayElements(['u2i','u2u'] as const), isActive: faker.datatype.boolean(), ...overrideResponse})

export const getBotControllerUpdateBotSettingsResponseMock = (overrideResponse: Partial<Extract<BotSettings, object>> = {}): BotSettings => ({answerOnFirstMessage: faker.datatype.boolean(), chatTypes: faker.helpers.arrayElements(['u2i','u2u'] as const), isActive: faker.datatype.boolean(), ...overrideResponse})

