/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


export const WebhookControllerAvitoBody = zod.object({
  "id": zod.string(),
  "version": zod.string(),
  "timestamp": zod.number(),
  "payload": zod.object({
  "type": zod.enum(['message']),
  "value": zod.object({
  "id": zod.string(),
  "chat_id": zod.string(),
  "user_id": zod.number(),
  "author_id": zod.number(),
  "created": zod.number(),
  "chat_type": zod.enum(['u2u', 'u2i']),
  "content": zod.unknown(),
  "item_id": zod.number().optional()
})
})
}).describe('Payload, который присылает Avito в вебхуке')

export const WebhookControllerAvitoResponse = zod.void()

