/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  AvitoWebhook
} from '../../models';

import { customInstance } from '../../../../shared/api/client';
import type { ErrorType , BodyType } from '../../../../shared/api/client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const webhookControllerAvito = (
    avitoWebhook: BodyType<AvitoWebhook>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/webhook/avito`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: avitoWebhook, signal
    },
      options);
    }




export const getWebhookControllerAvitoMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof webhookControllerAvito>>, TError,{data: BodyType<AvitoWebhook>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof webhookControllerAvito>>, TError,{data: BodyType<AvitoWebhook>}, TContext> => {

const mutationKey = ['webhookControllerAvito'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof webhookControllerAvito>>, {data: BodyType<AvitoWebhook>}> = (props) => {
          const {data} = props ?? {};

          return  webhookControllerAvito(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type WebhookControllerAvitoMutationResult = NonNullable<Awaited<ReturnType<typeof webhookControllerAvito>>>
    export type WebhookControllerAvitoMutationBody = BodyType<AvitoWebhook>
    export type WebhookControllerAvitoMutationError = ErrorType<unknown>

    export const useWebhookControllerAvito = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof webhookControllerAvito>>, TError,{data: BodyType<AvitoWebhook>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof webhookControllerAvito>>,
        TError,
        {data: BodyType<AvitoWebhook>},
        TContext
      > => {
      return useMutation(getWebhookControllerAvitoMutationOptions(options), queryClient);
    }
