/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  ScheduleDtoOutput,
  ScheduleWithItemsDtoOutput,
  SchedulesWithItemsDtoOutput
} from '../../models';

import {
  getScheduleControllerCreateScheduleResponseMock,
  getScheduleControllerGetScheduleResponseMock,
  getScheduleControllerUpdateScheduleResponseMock,
  getScheduleControllerUserScheduleListResponseMock
} from './schedule.faker';

export { getScheduleControllerCreateScheduleResponseMock, getScheduleControllerUserScheduleListResponseMock, getScheduleControllerGetScheduleResponseMock, getScheduleControllerUpdateScheduleResponseMock } from './schedule.faker';


export const getScheduleControllerCreateScheduleMockHandler = (overrideResponse?: ScheduleDtoOutput | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ScheduleDtoOutput> | ScheduleDtoOutput), options?: RequestHandlerOptions) => {
  return http.post('*/api/user/:userId/schedule', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getScheduleControllerCreateScheduleResponseMock(),
      { status: 201
      })
  }, options)
}

export const getScheduleControllerUserScheduleListMockHandler = (overrideResponse?: SchedulesWithItemsDtoOutput | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<SchedulesWithItemsDtoOutput> | SchedulesWithItemsDtoOutput), options?: RequestHandlerOptions) => {
  return http.get('*/api/user/:userId/schedule', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getScheduleControllerUserScheduleListResponseMock(),
      { status: 200
      })
  }, options)
}

export const getScheduleControllerGetScheduleMockHandler = (overrideResponse?: ScheduleWithItemsDtoOutput | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ScheduleWithItemsDtoOutput> | ScheduleWithItemsDtoOutput), options?: RequestHandlerOptions) => {
  return http.get('*/api/user/:userId/schedule/:scheduleId', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getScheduleControllerGetScheduleResponseMock(),
      { status: 200
      })
  }, options)
}

export const getScheduleControllerUpdateScheduleMockHandler = (overrideResponse?: ScheduleWithItemsDtoOutput | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<ScheduleWithItemsDtoOutput> | ScheduleWithItemsDtoOutput), options?: RequestHandlerOptions) => {
  return http.patch('*/api/user/:userId/schedule/:scheduleId', async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getScheduleControllerUpdateScheduleResponseMock(),
      { status: 200
      })
  }, options)
}

export const getScheduleControllerDeleteScheduleMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/user/:userId/schedule/:scheduleId', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}
export const getScheduleMock = () => [
  getScheduleControllerCreateScheduleMockHandler(),
  getScheduleControllerUserScheduleListMockHandler(),
  getScheduleControllerGetScheduleMockHandler(),
  getScheduleControllerUpdateScheduleMockHandler(),
  getScheduleControllerDeleteScheduleMockHandler()
]
