/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import type { AvitoWebhookPayloadType } from './avitoWebhookPayloadType.zod';
import type { AvitoWebhookPayloadValue } from './avitoWebhookPayloadValue.zod';

export type AvitoWebhookPayload = {
  type: AvitoWebhookPayloadType;
  value: AvitoWebhookPayloadValue;
};
