/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */

export type AvitoWebhookPayloadValueChatType = typeof AvitoWebhookPayloadValueChatType[keyof typeof AvitoWebhookPayloadValueChatType];


export const AvitoWebhookPayloadValueChatType = {
  u2u: 'u2u',
  u2i: 'u2i',
} as const;
