/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */

export type AvitoWebhookPayloadType = typeof AvitoWebhookPayloadType[keyof typeof AvitoWebhookPayloadType];


export const AvitoWebhookPayloadType = {
  message: 'message',
} as const;
