/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import type { AvitoWebhookPayloadValueChatType } from './avitoWebhookPayloadValueChatType.zod';

export type AvitoWebhookPayloadValue = {
  id: string;
  chat_id: string;
  user_id: number;
  author_id: number;
  created: number;
  chat_type: AvitoWebhookPayloadValueChatType;
  content: unknown;
  item_id?: number;
};
