/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */

export type BotSettingsChatTypesItem = typeof BotSettingsChatTypesItem[keyof typeof BotSettingsChatTypesItem];


export const BotSettingsChatTypesItem = {
  u2i: 'u2i',
  u2u: 'u2u',
} as const;
