/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import type { BulkCreateScheduleItemsDtoItemTimeEndTime } from './bulkCreateScheduleItemsDtoItemTimeEndTime.zod';
import type { BulkCreateScheduleItemsDtoItemTimeStartTime } from './bulkCreateScheduleItemsDtoItemTimeStartTime.zod';

export type BulkCreateScheduleItemsDtoItemTime = {
  /** Объект с данными о времени */
  startTime: BulkCreateScheduleItemsDtoItemTimeStartTime;
  /** Объект с данными о времени */
  endTime: BulkCreateScheduleItemsDtoItemTimeEndTime;
};
