/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import type { BulkCreateScheduleItemsDtoItemsItemTime } from './bulkCreateScheduleItemsDtoItemsItemTime.zod';
import type { BulkCreateScheduleItemsDtoItemsItemWeekDay } from './bulkCreateScheduleItemsDtoItemsItemWeekDay.zod';

/**
 * Объект с данными для создания части расписания
 */
export type BulkCreateScheduleItemsDtoItemsItem = {
  weekDay: BulkCreateScheduleItemsDtoItemsItemWeekDay;
  /**
     * Строка времени в формате [HH:mm]
     * @deprecated
     * @pattern ^([01]\d|2[0-3]):([0-5]\d)$
     */
  startTime?: string;
  /**
     * Строка времени в формате [HH:mm]
     * @deprecated
     * @pattern ^([01]\d|2[0-3]):([0-5]\d)$
     */
  endTime?: string;
  time: BulkCreateScheduleItemsDtoItemsItemTime;
  /** @minLength 1 */
  text: string;
};
