/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */

export type BulkCreateScheduleItemsDtoItem = {
  weekDay: 'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun';
  /**
     * Строка времени в формате [HH:mm]
     * @deprecated
     * @pattern ^([01]\d|2[0-3]):([0-5]\d)$
     */
  startTime?: string;
  /**
     * Строка времени в формате [HH:mm]
     * @deprecated
     * @pattern ^([01]\d|2[0-3]):([0-5]\d)$
     */
  endTime?: string;
  time: {
  /** Объект с данными о времени */
  startTime: {
  /**
     * @minimum 0
     * @maximum 23
     */
  hours: number;
  /**
     * @minimum 0
     * @maximum 59
     */
  minutes: number;
};
  /** Объект с данными о времени */
  endTime: {
  /**
     * @minimum 0
     * @maximum 23
     */
  hours: number;
  /**
     * @minimum 0
     * @maximum 59
     */
  minutes: number;
};
};
  /** @minLength 1 */
  text: string;
};
