/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import type { CreateScheduleItemDtoTime } from './createScheduleItemDtoTime.zod';
import type { CreateScheduleItemDtoWeekDay } from './createScheduleItemDtoWeekDay.zod';

export interface CreateScheduleItemDto {
  weekDay: CreateScheduleItemDtoWeekDay;
  /**
     * @deprecated
     * @pattern ^([01]\d|2[0-3]):([0-5]\d)$
     */
  startTime?: string;
  /**
     * @deprecated
     * @pattern ^([01]\d|2[0-3]):([0-5]\d)$
     */
  endTime?: string;
  /** Объект с временем начала и окончания в формате [HH, MM] */
  time: CreateScheduleItemDtoTime;
  /** @minLength 1 */
  text: string;
}
