/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import type { CreateScheduleItemDtoTimeEndTime } from './createScheduleItemDtoTimeEndTime.zod';
import type { CreateScheduleItemDtoTimeStartTime } from './createScheduleItemDtoTimeStartTime.zod';

export type CreateScheduleItemDtoTime = {
  /** Объект с данными о времени */
  startTime: CreateScheduleItemDtoTimeStartTime;
  /** Объект с данными о времени */
  endTime: CreateScheduleItemDtoTimeEndTime;
};
