/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import type { CreateScheduleDtoItemsItemTimeEndTime } from './createScheduleDtoItemsItemTimeEndTime.zod';
import type { CreateScheduleDtoItemsItemTimeStartTime } from './createScheduleDtoItemsItemTimeStartTime.zod';

export type CreateScheduleDtoItemsItemTime = {
  /** Объект с данными о времени */
  startTime: CreateScheduleDtoItemsItemTimeStartTime;
  /** Объект с данными о времени */
  endTime: CreateScheduleDtoItemsItemTimeEndTime;
};
