/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */

export * from './avitoCallbackControllerGetBotSettingsParams.zod';
export * from './avitoWebhook.zod';
export * from './avitoWebhookPayload.zod';
export * from './avitoWebhookPayloadType.zod';
export * from './avitoWebhookPayloadValue.zod';
export * from './avitoWebhookPayloadValueChatType.zod';
export * from './bindScheduleDto.zod';
export * from './botDto.zod';
export * from './botSettings.zod';
export * from './botSettingsChatTypesItem.zod';
export * from './bulkCreateScheduleItemsDto.zod';
export * from './bulkCreateScheduleItemsDtoItemsItem.zod';
export * from './bulkCreateScheduleItemsDtoItemsItemTime.zod';
export * from './bulkCreateScheduleItemsDtoItemsItemTimeEndTime.zod';
export * from './bulkCreateScheduleItemsDtoItemsItemTimeStartTime.zod';
export * from './bulkCreateScheduleItemsDtoItemsItemWeekDay.zod';
export * from './bulkUpdateScheduleItemsDto.zod';
export * from './bulkUpdateScheduleItemsDtoItemsItem.zod';
export * from './bulkUpdateScheduleItemsDtoItemsItemTime.zod';
export * from './bulkUpdateScheduleItemsDtoItemsItemTimeEndTime.zod';
export * from './bulkUpdateScheduleItemsDtoItemsItemTimeStartTime.zod';
export * from './bulkUpdateScheduleItemsDtoItemsItemWeekDay.zod';
export * from './createScheduleDto.zod';
export * from './createScheduleItemDto.zod';
export * from './createScheduleItemDtoTime.zod';
export * from './createScheduleItemDtoTimeEndTime.zod';
export * from './createScheduleItemDtoTimeStartTime.zod';
export * from './createScheduleItemDtoWeekDay.zod';
export * from './scheduleItemDto.zod';
export * from './scheduleItemDtoTime.zod';
export * from './scheduleItemDtoTimeEndTime.zod';
export * from './scheduleItemDtoTimeStartTime.zod';
export * from './scheduleItemDtoWeekDay.zod';
export * from './scheduleItemsDto.zod';
export * from './scheduleItemsDtoItem.zod';
export * from './scheduleItemsDtoItemTime.zod';
export * from './scheduleItemsDtoItemTimeEndTime.zod';
export * from './scheduleItemsDtoItemTimeStartTime.zod';
export * from './scheduleItemsDtoItemWeekDay.zod';
export * from './schedulesWithItemsDto.zod';
export * from './schedulesWithItemsDtoItem.zod';
export * from './schedulesWithItemsDtoItemItemsItem.zod';
export * from './schedulesWithItemsDtoItemItemsItemTime.zod';
export * from './schedulesWithItemsDtoItemItemsItemTimeEndTime.zod';
export * from './schedulesWithItemsDtoItemItemsItemTimeStartTime.zod';
export * from './schedulesWithItemsDtoItemItemsItemWeekDay.zod';
export * from './scheduleWithItemsDto.zod';
export * from './scheduleWithItemsDtoItemsItem.zod';
export * from './scheduleWithItemsDtoItemsItemTime.zod';
export * from './scheduleWithItemsDtoItemsItemTimeEndTime.zod';
export * from './scheduleWithItemsDtoItemsItemTimeStartTime.zod';
export * from './scheduleWithItemsDtoItemsItemWeekDay.zod';
export * from './unbindScheduleDto.zod';
export * from './updateBotSettings.zod';
export * from './updateBotSettingsChatTypesItem.zod';
export * from './updateScheduleDto.zod';
export * from './updateScheduleItemDto.zod';
export * from './updateScheduleItemDtoTime.zod';
export * from './updateScheduleItemDtoTimeEndTime.zod';
export * from './updateScheduleItemDtoTimeStartTime.zod';
export * from './updateScheduleItemDtoWeekDay.zod';
