/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */

export * from './avitoCallbackControllerGetBotSettingsParams.zod';
export * from './avitoWebhook.zod';
export * from './avitoWebhookPayload.zod';
export * from './avitoWebhookPayloadType.zod';
export * from './avitoWebhookPayloadValue.zod';
export * from './avitoWebhookPayloadValueChatType.zod';
export * from './bindScheduleDto.zod';
export * from './botDtoOutput.zod';
export * from './botSettings.zod';
export * from './botSettingsChatTypesItem.zod';
export * from './createScheduleDto.zod';
export * from './createScheduleDtoItemsItem.zod';
export * from './createScheduleDtoItemsItemWeekDay.zod';
export * from './scheduleDtoOutput.zod';
export * from './schedulesWithItemsDtoOutput.zod';
export * from './schedulesWithItemsDtoOutputItem.zod';
export * from './schedulesWithItemsDtoOutputItemItemsItem.zod';
export * from './schedulesWithItemsDtoOutputItemItemsItemWeekDay.zod';
export * from './scheduleWithItemsDtoOutput.zod';
export * from './scheduleWithItemsDtoOutputItemsItem.zod';
export * from './scheduleWithItemsDtoOutputItemsItemWeekDay.zod';
export * from './unbindScheduleDto.zod';
export * from './updateBotSettings.zod';
export * from './updateBotSettingsChatTypesItem.zod';
export * from './updateScheduleDto.zod';
export * from './updateScheduleDtoItemsItem.zod';
export * from './updateScheduleDtoItemsItemWeekDay.zod';
