/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import type { ScheduleItemDtoTimeEndTime } from './scheduleItemDtoTimeEndTime.zod';
import type { ScheduleItemDtoTimeStartTime } from './scheduleItemDtoTimeStartTime.zod';

export type ScheduleItemDtoTime = {
  /** Объект с данными о времени */
  startTime: ScheduleItemDtoTimeStartTime;
  /** Объект с данными о времени */
  endTime: ScheduleItemDtoTimeEndTime;
};
