/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */

export type ScheduleWithItemsDtoItemsItemWeekDay = typeof ScheduleWithItemsDtoItemsItemWeekDay[keyof typeof ScheduleWithItemsDtoItemsItemWeekDay];


export const ScheduleWithItemsDtoItemsItemWeekDay = {
  mon: 'mon',
  tue: 'tue',
  wed: 'wed',
  thu: 'thu',
  fri: 'fri',
  sat: 'sat',
  sun: 'sun',
} as const;
