/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import type { ScheduleItemsDtoItem } from './scheduleItemsDtoItem.zod';

export type ScheduleItemsDto = ScheduleItemsDtoItem[];
