/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import type { SchedulesWithItemsDtoItemItemsItemTimeEndTime } from './schedulesWithItemsDtoItemItemsItemTimeEndTime.zod';
import type { SchedulesWithItemsDtoItemItemsItemTimeStartTime } from './schedulesWithItemsDtoItemItemsItemTimeStartTime.zod';

/**
 * Объект с временем начала и окончания в формате [HH, MM]
 */
export type SchedulesWithItemsDtoItemItemsItemTime = {
  startTime: SchedulesWithItemsDtoItemItemsItemTimeStartTime;
  endTime: SchedulesWithItemsDtoItemItemsItemTimeEndTime;
};
