/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import type { ScheduleItemsDtoItemTimeEndTime } from './scheduleItemsDtoItemTimeEndTime.zod';
import type { ScheduleItemsDtoItemTimeStartTime } from './scheduleItemsDtoItemTimeStartTime.zod';

/**
 * Объект с временем начала и окончания в формате [HH, MM]
 */
export type ScheduleItemsDtoItemTime = {
  startTime: ScheduleItemsDtoItemTimeStartTime;
  endTime: ScheduleItemsDtoItemTimeEndTime;
};
