/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */

export type UpdateScheduleItemDtoWeekDay = typeof UpdateScheduleItemDtoWeekDay[keyof typeof UpdateScheduleItemDtoWeekDay];


export const UpdateScheduleItemDtoWeekDay = {
  mon: 'mon',
  tue: 'tue',
  wed: 'wed',
  thu: 'thu',
  fri: 'fri',
  sat: 'sat',
  sun: 'sun',
} as const;
