/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */
import type { UpdateScheduleItemDtoTime } from './updateScheduleItemDtoTime.zod';
import type { UpdateScheduleItemDtoWeekDay } from './updateScheduleItemDtoWeekDay.zod';

export interface UpdateScheduleItemDto {
  weekDay?: UpdateScheduleItemDtoWeekDay;
  /**
     * @deprecated
     * @pattern ^([01]\d|2[0-3]):([0-5]\d)$
     */
  startTime?: string;
  /**
     * @deprecated
     * @pattern ^([01]\d|2[0-3]):([0-5]\d)$
     */
  endTime?: string;
  /** Объект с временем начала и окончания в формате [HH, MM] */
  time?: UpdateScheduleItemDtoTime;
  /** @minLength 1 */
  text?: string;
}
