/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zhe_nU Tools API
 * API for Zhe_nU Tools
 * OpenAPI spec version: 1.0
 */

export type UpdateScheduleDtoItemsItemTimeEndTime = {
  /**
     * @minimum 0
     * @maximum 23
     */
  hours: number;
  /**
     * @minimum 0
     * @maximum 59
     */
  minutes: number;
};
