name: PROD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    environment: PROD

    steps:
      - uses: actions/checkout@v4

      - name: Build and Deploy
        env:
          NEXT_PUBLIC_AVITO_CLIENT_ID: ${{ vars.NEXT_PUBLIC_AVITO_CLIENT_ID }}
          NEXT_PUBLIC_API_BASE_URL: ${{ vars.NEXT_PUBLIC_API_BASE_URL }}
          NEXT_PUBLIC_FORGOT_PASSWORD_REDIRECT_URL: ${{ vars.NEXT_PUBLIC_FORGOT_PASSWORD_REDIRECT_URL }}
          NEXT_PUBLIC_LOGIN_REDIRECT_URL: ${{ vars.NEXT_PUBLIC_LOGIN_REDIRECT_URL }}
        run: |
          docker compose -f ./.docker/docker-compose-prod.yaml up -d --build
